### ISSUE TITLE
[Uptime] Redirects in UI

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#101]
This is the non-design issue tracking 

With https://github.com/elastic/beats/pull/14125 we will now include a list of redirects traversed in checking a URL. There's currently no way to see this info. A check that involves redirects may be interpreted differently than one that does not, so we should indicate this. One key difference is that redirects can be slower than a non-redirects, so one may interpret latency differently.

See https://github.com/elastic/uptime/issues/99 for the design of this feature

**Comment by katrin-freihofner** [comment]
Monitor page status:
<img width="677" alt="Screenshot 2019-12-02 at 13 25 23" src="https://user-images.githubusercontent.com/20965076/69959345-3c5e7880-1507-11ea-90a9-4186a78b0200.png">


Individual check details:
<img width="426" alt="Screenshot 2019-12-02 at 13 22 09" src="https://user-images.githubusercontent.com/20965076/69959349-3ff1ff80-1507-11ea-8e05-9a33817e8b9f.png">

**Comment by shahzad31** [comment]
@katrin-freihofner are we displaying redirects in expanded row in history panel on details page or on monitor list?

From image 
![image](https://user-images.githubusercontent.com/3505601/79733194-0161b380-82f5-11ea-9d15-c8235278f604.png)

it looks like it's a expanded row in monitor list also figma link images says the same https://www.figma.com/file/lDlGXMzUTnzAlHPQu7lZAH/Uptime?node-id=130%3A1

but andrew comments and expanded row body in above image seems like it's history panel, since it also has Reponse Body.

Are we going to display in both places?

**Comment by katrin-freihofner** [comment]
@shahzad31 I think the redirect info belongs to the details page. cc @andrewvc

**Comment by andrewvc** [comment]
Yes, the mock is for the history panel in the details page. Not sure where the confusing comments are, but I'm on the same page as @katrin-freihofner

**Comment by shahzad31** [comment]
Confusion was from the image actually, row style is from monitor list 
![image](https://user-images.githubusercontent.com/3505601/79752388-84decd00-8314-11ea-9c71-c2c231d400bb.png)

Katrin clarified it.

**Comment by shahzad31** [comment]
I think for the monitor detail, i liked the original idea better 
![image](https://user-images.githubusercontent.com/3505601/79752484-ab9d0380-8314-11ea-8091-23d5de95953f.png)

just displaying text doesn't convery much, we should also display popover with redirect list 
![image](https://user-images.githubusercontent.com/3505601/79752531-c1aac400-8314-11ea-9251-a3c585b64f09.png)

In original issue, i think it was recommended that we update the text but we should keep the popover panel.

WDYT? cc @andrewvc @katrin-freihofner

**Comment by katrin-freihofner** [comment]
The header gives only a quick overview. The details about redirects are further down in the table. That is why we decided to go that way.
