### ISSUE TITLE
[Design] Alerting for Uptime

### ISSUE THREAD

**Issue by katrin-freihofner** [elastic/uptime#102]
This is a pre-requisite for alerting design within Uptime.

Research
- [x] user flow
- [x] how to handle Uptime alerts (covered by alert overall concept)
- [x] requirements for different no. of monitors (not covered for now)
- [x] alerts on all monitors vs. individual ones/groups of monitors (not covered for now)

Related: https://github.com/elastic/uptime/issues/64

**Comment by katrin-freihofner** [comment]
For the first iteration, we are going to address the issue of creating an alert for **all monitors**. Therefore, I would put the button to create an alert on the overview page as part of the **monitor status panel** (because it will alert me about the monitor status).

![uptime-alert](https://user-images.githubusercontent.com/20965076/70219879-e9becf80-1745-11ea-88e5-d5c1d0bcbd7b.png)

@andrewvc this button triggers the alert flyout which is - as far as I know - defined by the alerting team. I think users can create multiple alerts for all monitors, can't they? Editing, deleting, muting... the existing alerts are only possible via the alerts management page. 

Please let me know if you have any feedback, questions or further design work is needed.

**Comment by andrewvc** [comment]
@katrin-freihofner that works for me! Yes, we don't need more than the initial button. Thanks for mocking this up :)
