### ISSUE TITLE
Stop adding _all_ default values to URL when navigating

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#105]
**Is your feature request related to a problem? Please describe.**
Today, we add all the default parameters to the URL path when we navigate the app. This looks bad when the user hasn't specified any custom values, and since they're defaults it does nothing but pollute our URL with lots of unnecessary markup.

**Describe the solution you'd like**
Only add parameters that are not equal to defaults, when the user modifies the app state.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by andrewvc** [comment]
Already fixed.
