### ISSUE TITLE
Easier navigation to downtime details from overview page

### ISSUE THREAD

**Issue by matschaffer** [elastic/uptime#107]
**Is your feature request related to a problem? Please describe.**

When I see downtime on the main overview page, I'd like to investigate it as quickly a possible.

I first tried clicking on these bars, but there's no interaction there.

![Kibana](https://user-images.githubusercontent.com/690/67996447-9ebb2380-fc92-11e9-9f5e-55e5a371fae8.png)

Instead I have to click on the monitor name, then manually select what appears to be the right time frame based on a natural language time string.

![Kibana](https://user-images.githubusercontent.com/690/67996326-25bbcc00-fc92-11e9-9dc7-c46dd4f8974f.png)

**Describe the solution you'd like**

I'd like to be able to view a given failure quickly.

My first intuitive approach to this would be to make the failure bar clickable. 

This would open the single monitor view with with the same timeframe as the failure I clicked already set.

**Describe alternatives you've considered**

When I noticed the bars weren't clickable, the next thing I tried was drag-selection (like on kibana discover and viz support) to set the timeframe.

I hoped I could do this then click on the alert to get just the failure I'm investigating. Drag-selecting timeframe, could possibly be another github issue, but mentioning it here given the "alternatives" header.

**Additional context**

I chatted about this with @justinkambic and @katrin-freihofner who recommended opening the issue.

The use case is for @elastic/cloud-observability so mentioning them for context.

**Comment by andrewvc** [comment]
CC @katrin-freihofner would love to hear your thoughts here on the proposed solutions. They both seem like things we should do. 

Clickable mini-histogram makes sense to me, as does the suggestion for draggable time selections on the details page.

**Comment by andrewvc** [comment]
Closing in favor of making this a feature on timelines.

**Comment by matschaffer** [comment]
@andrewvc can you point me to an appropriate issue to watch on that?

**Comment by matschaffer** [comment]
took a guess that maybe it's https://github.com/elastic/uptime/issues/109 though it doesn't mention "timelines" specifically so let me know if I got it. Thanks!

**Comment by andrewvc** [comment]
@matschaffer sorry I missed your last comment. It's added as an item on https://github.com/elastic/kibana/issues/44546

**Comment by matschaffer** [comment]
Subscribed. Thanks!
