### ISSUE TITLE
[Telemetry] Track feature usage

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#108]
**Is your feature request related to a problem? Please describe.**
One of the future asks from Observability in general is more granular telemetry for solution feature usage. We’ve added numerous interactions in more recent versions of our UI; it would be useful to get more visibility into how frequently our users leverage them.

For example, it will be really useful to track how frequently our integrations are used today, vs. how often they’re leveraged in the future as we enhance them. Another opportunity would be our expanding rows on both pages.

**Describe the solution you'd like**
Today, we have two telemetry shippers running in the app. There is a shared Observability logger, this is what we will expect to use going forward. We also have a custom telemetry collector that we will likely decommission after significant confidence has been developed in the shared solution.

**Describe alternatives you've considered**
N/A

**Additional context**
This means we will need to contribute to the shared telemetry collector, which will mean a more detailed discussion with the rest of the Observability team.

**Comment by andrewvc** [comment]
This feels like two separate issues:

1. Changing the technical infrastructure of telemetry
2. Changing what's measured with telemetry.

@justinkambic do you mind clarifying / refocusing / splitting this issue? Alternatively, I'm fine closing this for now. I think we'll organically get to cleaning up our telemetry code as we expand it.

**Comment by justinkambic** [comment]
@andrewvc there's been a lot of movement on the telemetry front since I created this issue. I think that the scope of what this attempted to address has broadened significantly, and will encompass anything this issue would've covered, so we should just close this.

**Comment by andrewvc** [comment]
Closing in favor of https://github.com/elastic/kibana/issues/57016
