### ISSUE TITLE
Error list should display Monitor's Name/URL before it displays the ID

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#11]
**Is your feature request related to a problem? Please describe.**
We're displaying the ID today, which at one point made sense but for `7.x` data this is no longer useful to our users.

**Describe the solution you'd like**
We should update the Error List to display `Name`, then `URL`, and lastly `ID`. There should almost never be a case where we display the monitor's ID if we do this.

**Describe alternatives you've considered**
We could leave the view as is, but this will likely make the component confusing and hard to use/understand.

**Additional context**
We've had this problem elsewhere within the UI as well.

![image](https://user-images.githubusercontent.com/18429259/53254570-9cc7ac00-3691-11e9-9b50-67d24ba9f546.png)

**Comment by alvarolobato** [comment]
This is now obsolete with the new summaries implementation - https://github.com/elastic/kibana/issues/38786
