### ISSUE TITLE
Enhance Uptime client routing

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#110]
**Is your feature request related to a problem? Please describe.**
There's some weirdness with the way our current routing works that causes some issues when trying to navigate without a `#` in the URL. Mainly this causes the page to reload when navigating between our Detail page and the Overview page, but it's also a pattern that should be improved to make future additions easier.

**Describe the solution you'd like**
Modify the ordering of routes and make it so we don't need a catch-all `/` route to provide URL data to the underlying components.

**Describe alternatives you've considered**
N/A

**Comment by shahzad31** [comment]
@justinkambic i think this is not needed anymore, our routes has been refactored. 

I think presence of # is fine , it aligns with other app APM, Infra, they are also using #. 

So i am closing this.
