### ISSUE TITLE
Click buckets in Uptime charts to navigate to details page

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#111]
**Is your feature request related to a problem? Please describe.**
In https://github.com/elastic/uptime/issues/107 we had a user ask for the ability to click on a single bucket in their uptime chart, and have the app navigate to the details page, scoped to the timespan of that particular bucket.

I'm curious to hear thoughts @katrin-freihofner might have about this, as well as the rest of the team. It sounds like a decent enhancement, but I could see it being a little jarring to suddenly trigger a navigation the first couple of times it happens.

**Comment by katrin-freihofner** [comment]
I understand that this might be convenient. But I'm not convinced that this is a good idea for the current chart. I would prefer to postpone this until we have the new timeline chart. Additionally, if we decide to do something like that, we need to make sure these areas are big enough to be touchable (> 40px).

**Comment by justinkambic** [comment]
Agree we shouldn't invest in visualizations that will go away 👍
