### ISSUE TITLE
Rename all references to `Infra` with `Metrics` in Uptime UI/solution

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#112]
**Is your feature request related to a problem? Please describe.**
The Infrastructure solution has been renamed to Metrics, we should go through our codebase and rename any user-facing text to reflect this, and change it in any code/resource where it's reasonable.

**Describe the solution you'd like**
Rename `Infra` or `Infrastructure` to `Metrics`.

**Describe alternatives you've considered**
N/A

**Additional context**
We have a handful or references to Infra like below.
![image](https://user-images.githubusercontent.com/18429259/68701272-66e69280-0554-11ea-90cb-989d0114db9a.png)

**Comment by andrewvc** [comment]
PR in https://github.com/elastic/kibana/pull/53007

**Comment by andrewvc** [comment]
Closing since the metrics team still uses infra in code.
