### ISSUE TITLE
Monitor expanded list, display Monitor Status info by dns in new design !!

### ISSUE THREAD

**Issue by shahzad31** [elastic/uptime#113]
**Summary of the problem** 
While working on expanded list https://github.com/elastic/kibana/issues/44541, i realized we are omitting monitor status information per dns, which was being displayed in previous design.
Does it make sense to display monitor status up/down information per dns, is it useful for user to see that?
**Ideal solution** (optional)
We can display status up/down for each dns in an accordion in expanded list.

**Old design:**

![image](https://user-images.githubusercontent.com/3505601/69158029-14721c80-0ae6-11ea-9a48-d0c5280009eb.png)

**New Design:**
![image](https://user-images.githubusercontent.com/3505601/69159108-b9412980-0ae7-11ea-8a1d-48b6054984a7.png)

We need to see if can bring back status info by dns.

**Comment by shahzad31** [comment]
@katrin-freihofner can you please give some feedback on this.

**Comment by justinkambic** [comment]
We chatted a bit about this yesterday, it seemed like the consensus was that this isn't a huge pain point for most users. I'm open to suggestions of how we can display DNS data if others want to have it here though; as Shahzad already mentioned, this is something that we've had in the past.

**Comment by shahzad31** [comment]
Yeah i am going to close it, we discussed that this isn't really useful. If anyone has any-other idea, we can reopen it.
