### ISSUE TITLE
Remove reliance on lodash in favor of new TypeScript features

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#118]
We are seeking to replace old framework calls with new features of the standard TS language that have made the older code unnecessary.

This includes:
- [ ] usages of `lodash.get`
- [ ] introduction of nullish coalescing
- [ ] fix static type issues previously masked by framework calls' assumed types

**Comment by andrewvc** [comment]
We'll make this an incremental refactor, no need to track it.
