### ISSUE TITLE
Push Heartbeat dashboards to contrib

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#12]
It's been expressed that there is some dismay amongst current users of Heartbeat dashboards that they're not going to be supported in 7.0. In the last planning meeting, we decided that it would be fairly low-effort to make them available in a new contrib repo for Uptime.

I figured it would be a good idea to track this in a dedicated issue here, especially because members of our team weren't able to make the call and we should have a centralized place to share thoughts on the topic.

**Comment by tbragin** [comment]
We discussed this in a live meeting and concluded that putting dashboards in `uptime-contrib` in the short term makes most sense. This mirrors what we do in APM, and allows us to iterate. For now, we should put the 6.7 dashboard in there. For 7.0 dashboards, we'd still have to build them. 

@jamiesmith @dov0211 It might be interesting to think through and suggest specific visualizations we may consider for Uptime dashboards going forward. What questions could they help the user answer (beyond the curated UI), that show off the power of Elasticsearch and Kibana for ad-hoc analytics and data visualizations. Perhaps you and other PMMs can make suggestions on what the dashboards may show going forward?

**Comment by andrewvc** [comment]
I've created the [uptime-contrib](https://github.com/elastic/uptime-contrib/pull/1) repo initial commit. Could someone review it?

Also, any opposition to closing out this issue?
