### ISSUE TITLE
[Uptime] [Uptime] Make overview heading handle filtered states better 

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#120]
**Is your feature request related to a problem? Please describe.**
While reviewing https://github.com/elastic/kibana/pull/48035 [it was noted](https://github.com/elastic/kibana/pull/48035#issuecomment-555015920) that we should denote to the user that a message like `All monitors are up` should be tempered with some descriptor if a filter is applied.

**Describe the solution you'd like**
If the user has filtered by `up` monitors, it is important for the message to say something like `All selected monitors are up` to denote that they're looking at their environment through a filtered lens. So a message like above is better.

**Describe alternatives you've considered**
It might even be preferable to always include this more descriptive heading when filters are applied. A message like "3/5 of the selected monitors are down" is better than saying "3/5 monitors are down" when a filter is applied. This type of language helps better define what we're looking at, and is part of the reason we've had headaches in the past over whether the values we're showing in the `Snapshot` component are "accurate".

**Additional context**
N/A

**Comment by andrewvc** [comment]
Maybe we should move back to showing an exact count? I think the problem is that `all` implies that every monitor we know about is up, a count seems like its tied more to the search. 

Would love to hear from @katrin-freihofner and @drewpost

**Comment by katrin-freihofner** [comment]
Summary of what we have discussed:
- add the number of monitors to the list.
- move the up/down filters to the table. 
- change the headline to a more generic one (that is not affected by the filtering)

This is how I imagine this could look (edited):
![Overview](https://user-images.githubusercontent.com/20965076/75541744-c8a50c80-5a1e-11ea-88ce-ca4c2e78ca53.png)
