### ISSUE TITLE
Overview Pagination: add ability to specify N of rows/page

### ISSUE THREAD

**Issue by SlavikCA** [elastic/uptime#122]
7.5.0 added Pagination to the overview page.
However, it always 10 rows per page.
Doesn't look good on my 32" 4k monitor.
Previously (without pagination) I can overview all of my entries by opening one page by one click. Now it takes me a few clicks to load a few pages.

**Request:**
- Add the ability to specify N rows per page. With one choice being "All rows"
- Add the ability to make it default. Either by storing the preference in the cookie or by specifying as URI parameter.

**Comment by SlavikCA** [comment]
Here is how it looks on my large monitor:

![Screen Shot 2019-12-02 at 3 09 26 PM](https://user-images.githubusercontent.com/6293679/70003050-cd891b80-1516-11ea-81fd-0741abd849a1.jpg)

**Comment by andrewvc** [comment]
Thanks for the suggestion @SlavikCA  , I think this makes sense, except the 'All Rows' part. That could be quite intense performance-wise if you have 10k+ rows etc.

**Comment by SlavikCA** [comment]
> this makes sense, except the 'All Rows' part. That could be quite intense performance-wise if you have 10k+ rows etc.

In the "10k+ rows" case you just will not select 'All Rows'.
In the previous version (7.4) 'All Rows' was the default. Why we can't have it as an option now?

**Comment by andrewvc** [comment]
In 7.4 all rows wasn't truly all rows. We had a limit built into the server, and it would just select at most that limit. Unbounded data fetching isn't something we can build without causing crashes or adverse performance.

**Comment by andrewvc** [comment]
I've created https://github.com/elastic/kibana/issues/54031 to track work on this issue in greater detail, I'm going to close this issue in favor of that more action oriented one.

**Comment by andrewvc** [comment]
Fixed in https://github.com/elastic/kibana/pull/60573
