### ISSUE TITLE
Should PingList expandable row be disabled if there is no content to show?

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#125]
**Is your feature request related to a problem? Please describe.**
It's possible to create a monitor that has no response body. Today this renders like this:
![image](https://user-images.githubusercontent.com/18429259/70479104-a7c9bc80-1aaa-11ea-9826-4712638f9d3c.png)

**Describe the solution you'd like**
Should we disable the expand button for a monitor when it doesn't have any content?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by katrin-freihofner** [comment]
That's a good idea. Or we could describe that there is no response body. So as a user I see that Uptime did check it but there simply is nothing to show.
