### ISSUE TITLE
Uptime Telemetry

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#13]
We have had numerous discussions about the need to add telemetry to Uptime.

One of the important things we need to decide is what needs to be tracked. I have the bones of a telemetry PR written locally, but until we've made this determination I can't finish the work.

I would say it would be useful to bucket the data by hour, similar to how infra does. Do we want to track the number of requests the app serves, the number of monitors, the type of monitors, etc.?

**Comment by tbragin** [comment]
@dov0211 ^^

**Comment by dov0211** [comment]
I think it makes sense to follow along infra logic, any other information we can gather would be most beneficial.
- Number of time Uptime app is been access
- Types of monitors 
- Number of monitors

**Comment by justinkambic** [comment]
@dov0211 I'm coming back around to this now that 6.7 and 7.0 are releasing.

> Number of time Uptime app is been accessed (this one is the most critical one for uptime)

It's probably best to define exactly what/how we'll be capturing data. Infra's server knows when the user is streaming and does not log those hits to telemetry. It would likely be best for us to detect auto-refresh events and ignore them as well.

Infra buckets their data, so the output for them looks something like:
```JSON
{
  "1553516065000": {
    "infraopsHosts": 23,
    "logs": 42,
  },
  "1553517065000": {
    "infraopsHosts": 19,
    "logs": 47,
  },
  ...
}
```

Does this sort of collection structure sound good to you as well? We'd collect our metrics by hour like they do.

> Types of monitors

We'd maintain a `monitorTypes` count, specifying `http`, `tcp`, and `icmp` for now.

> Number of monitors

Because we are a readonly solution at the moment, we don't have many events we can listen for that will have implications for this count. Do you have any preference for the way we count to generate the most relevant data possible? We could simply track the highest counts per bucket, or do something more elaborate if needed.

**Comment by dov0211** [comment]
Its seems that since we have upgraded our telemetry, we are getting much more info, I am working with @pickypg on fixing some issues before we could get a query on this data, however, I believe that right now all we need is to know how many had accessed the Overview, and how many had accessed the Monitors page
something like that

```
{
  "1553516065000": {
    "Overview": 23,
    "Monitors": 42,
  },
```

**Comment by justinkambic** [comment]
>  I believe that right now all we need is to know how many had accessed the Overview, and how many had accessed the Monitors page

Ok, sounds great. We want it to skip autorefresh requests though, correct?

**Comment by dov0211** [comment]
I think it makes sense.

**Comment by alvarolobato** [comment]
Closing after https://github.com/elastic/kibana/issues/31259
