### ISSUE TITLE
Migrate index pattern fetching from component level effect to state store

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#132]
**Is your feature request related to a problem? Please describe.**
Today we are having multiple components responsible for fetching the index pattern utilized by the application. This is inefficient, because we only have one index pattern, and we shouldn't be pulling it down multiple times for a single run.

**Describe the solution you'd like**
We should add the pattern to our state store, and provide an action type that can be dispatched to refresh it. We can dispatch one of these actions as part of our application's bootstrapping process, and in the future if we want to allow user actions to refresh the pattern the infrastructure will already be present.

**Describe alternatives you've considered**
We are going to create a temporary fix as a solution for https://github.com/elastic/kibana/issues/54151. We could leave that fix in place indefinitely, but this solution is better long-term.

**Additional context**
N/A

**Comment by shahzad31** [comment]
This is fixed by https://github.com/elastic/kibana/pull/55446
