### ISSUE TITLE
Enhanced Uptime Telemetry

### ISSUE THREAD

**Issue by drewpost** [elastic/uptime#133]
As a product engineering team
We want to collect a broader range of user behaviour telemetry from the Uptime app
So that we can make better informed product prioritisation and design decisions

ACs:

The following metrics are captured and available in Elastic Telemetry:

- Count of Monitors
- Count of characters of Monitor names
- Frequency of monitors
- Count of geolocations
- Count of characters of geolocation names
- Referral Source when entering Uptime app
- Count of alerts sent
- Alert Meta Data: metric alerted on, threshold levels, rule set
- Date Range Selected on load
- Changes to date range (event) and new value
- Is auto refresh active?
- What is the auto refresh interval?

**Comment by andrewvc** [comment]
Implementation issue ready here: https://github.com/elastic/kibana/issues/57016
