### ISSUE TITLE
Remove `useUrlParams` hook in favor of `useParams`

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#135]
**Is your feature request related to a problem? Please describe.**
React Router provides hooks for interacting with things like URL params and the History API. We have a custom hook for tracking URL params, and we should see if it's possible for us to do away with this hook and instead leverage the React Router solution.

**Describe the solution you'd like**
Ideally we could just replace the hook altogether. There may be complexity involved because our custom hook also provides capabilities for updating the url parameters, further investigation may be needed.

**Describe alternatives you've considered**
We could also simply replace the usages of `useUrlParams` where we are only utilizing the `get` function for the time being if it's a significantly heavier lift to replace the `update` functionality.

**Additional context**
N/A

**Comment by shahzad31** [comment]
react-router useParams doesn't support queryParams, it is only meants for url params, so we can't use it. We will continue to use for url params, like monitorId in our application.
