### ISSUE TITLE
CM Integration

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#14]
This issue serves to map out an approach to building out CM support for heartbeat.

## Architectural Goals

Before we dive into CM, we should contextualize our plan there with longer term goals for Uptime, namely HA and geographic awareness. This document was created to move us closer to this desired future state of heartbeat. The key components in this future architecture are:

1. Elasticsearch + Kibana as highly available central store of state
2. Clusters of heartbeat instances acting as a single highly available instance divided into logical geographic regions such as `us-east-1a`, or `dc-1-london`.

In this model users configure monitors to be checked from a given list of regions. Elasticsearch maintains the config in a highly available way, Kibana serves it, and one or more Heartbeats in each region work together to ensure that all checks designated as coming from that region are running. A key design consideration that follows from this is that we should de-emphasize users configuring specific heartbeat instances. Users should be encouraged to define their config at a higher level, targeting regions.

### Overview

* `heartbeat-VERSION-DATE` Indices: Time-series indices containing all monitoring data
* `.heartbeat-state`: Non-time-series index containing:
  * The last state of individual heartbeat instances
  * The last state of individual heartbeat monitors per geographic location
* CM API: Authoritative source for heartbeat configs

*Note: We initially thought we might have to store config data in our own proprietary index as well as CM. After some very productive discussions with @mattapperson we believe the CM API is sufficient. By hooking custom javascript into the CM lifecycle we can achieve our goals.*

### `heartbeat-VERSION-DATE` time series index: 

The schema for the time series index is already [documented here](https://www.elastic.co/guide/en/beats/heartbeat/current/exported-fields.html).

#### Beat State

Contains two different logical types.

```javascript
{
  "type": "beat-state",
  "@timestamp": "2019-01-01Z08:08:08", // last updated
  "beat-state": {
    "status": "up" // also can be down if `@timestamp` not updated within the last 60 seconds
   },
   "agent": {"..."}, // all beat agent fields, including IDs
   "geo": {"location": "nyc-dc-1"}
}
```

#### Monitor State
```javascript
{
  "@timestamp": "2019-01-01Z08:08:08", // last updated
  "type": "monitor-state",
  "monitor-state": {
    "id": "ouhth892theou8",
     // lowest common denominator of "checks" below (up/down), or the special 'new' state.
     // 'new' is set after the monitor has been configured, but no heartbeat instances have yet started
     // performing checks
     "status": "down",
     "config_source": "central", // can also be 'local' for yaml configs
     "checks": [ // stored as nested documents, cardinality should be low
     {
        "status": "up",
        "geo": {"location": "nyc-dc-1"},        
         "@timestamp": "2019-01-01Z02:08:08"
        // Rest of event not shown
      },
      {
       "status": "down", // one down monitor will cause the summary to be down
       "error": {"message": "could not connect"},
       "geo": {"location": "lax-dc-1"},
       "@timestamp": "2019-01-01Z08:08:08"
      },
    ]
  }
}
```

### CM Config Blocks

While we don't write to the CM indices directly--we use the CM API--we do attach geolocation metadata using labels such as  `"geolocation": "nyc-dc-1" `.

Initially we will not make use of CM tags for any reasons. We can use a single default tag, which may be a hidden system tag, for all Uptime App created configs (maybe `uptime-app` would be a name), but the tags would be ignored for the time being since there's no key use case that would need them.

### Basic CRUD for configs

This will work using the CM API, and not a custom uptime one as originally proposed.

* One monitor will correspond to one config block in the API.
* Manual setting of `monitor.id` will not be allowed. The value used will be the ES document ID.
* Hooks will be defined updated the `monitor-states` index with a stub value when a monitor is altered. This will let us display a 'no data received' state in the gap between a user hitting save and heartbeat picking up the change. It will also let us display a 'pending approval' state for situations where admins must approve config changes.

### Pulling a location appropriate list of monitors for each heartbeat

Each config block will have location metadata associated with it (note, this is not a tag!) as will each beat.  Each beat will ask for all configs with the same geolocation metadata the beat has. So, if you have a heartbeat in `us-east-1a`, it will ask the CM API only to provide monitors matching that.

## Listing available geo locations

When creating monitors we will need to display a list of available geographic locations. We will create this by running a terms agg on the `heartbeat-state` index for docs of the `beat-state` type.

### Listing monitors for overview page

This operation will work by querying the `heartbeat-state` index which contains the latest info.

### Updating monitor states with monitoring data

State index support in heartbeat will consist of heartbeat sending two documents to Elasticsearch for each check, instead of the current single document. The existing documents will not change, but an additional scripted update to the states index will be performed. This update will replace the check for the given geographic location, and also re-calculate the summary info for the state.

### Scrubbing monitor states and beat states

Querying the monitor states is less useful if the index contains stale monitors that were de-configured from the YAML. We will write a scrubber process in kibana that periodically looks for monitors not updated within some time period configurable in Kibana (say 1 day by default), and removes any entries in the state index. Items configured by central config will not be subject to this, as the hooks in the CM API will remove these docs.

Beat states have a similar issue. Beats may come and go. I propose a similar proposal to amazon EC2 terminated instances where we still show `dead` beats for 24 hours, but scrub them once they haven't sent a ping in that long. It's hard to know if a beat has been deleted, or is only temporarily down.

## Advantages over keeping the current schema

The current schema, which doesn't have the `heartbeat-states` index has some key deficiencies. Namely that some queies are very hard, inefficient, or even impossible. These are enumerated below:

* **It would be much harder to query all `down` monitors across all regions yielding one monitor per row**: This is a key query for alerting.  The closest you could get with a timeseries index is to aggregate by geo region. With read-time queries we'd need to pull all of the latest monitors per region using a `compsite` query with `searchAfter` for pagination in kibana server, iterate through each record in javascript, and then merge geographic regions in kibana to calculate this. 
* **We have a very awkward way of calculating total `up/down` monitors**: This requires the same iteration mentioned in the point above today. See the [code](https://github.com/elastic/kibana/blob/master/x-pack/plugins/uptime/server/lib/adapters/monitors/elasticsearch_monitors_adapter.ts#L192) for more info.
* **With composite queries used today all lists of monitors must be sorted by `@timestamp`**: Otherwise the aggregation will not be based on the latest data, and the result will be garbage. This makes sortable columns in table views impossible.
* **Deletion of monitors is very inefficient and awkward**: With a states index a monitor's data is removed from the states index when deleted. With the current time series ones we would need to create a tombstone record to do it correctly. The alternative is some sort of time based expiry which is also complex to configured.
* **Building Kibana custom dashboards with aggregated data is impossible**: Without the states index it is impossible to build advanced dashboards with aggregated monitor data. The complex queries we rely on require custom code to function.

### Phase 1: Basic CM

1. Add CM support to heartbeat
1. Build Monitor Config UI in Uptime App
1. Add state index support to heartbeat
1. Add pre/post-config hooks to CM (once CM supports this feature) https://github.com/elastic/kibana/issues/33634

### Phase 2: Location Awareness
1. Add support in CM go/JS code for filtering based on location metadata https://github.com/elastic/beats/issues/11358

### Phase 3: Better support for scrubbing stale state
1. YAML state scrubber
1. Beat state scrubber

**Comment by justinkambic** [comment]
> Manual setting of monitor.id will not be allowed.

We had previously discussed the possibility of allowing users to specify custom IDs (like AWS ARNs for instance) when we were considering the need for our own API above CM - will we no longer pursue that concept?

> We will write a scrubber process in kibana that periodically looks for monitors not updated within some time period configurable in Kibana (say 1 day by default), and removes any entries in the state index.

One thought I have regarding this is it may be nicer to label stale monitors as such, and provide the ability to manually delete them, rather than having old monitors silently disappear. The ability to delete them individually, and perhaps providing a one-click solution, may increase user confidence in the system. Perhaps it's also something we could configure from a Kibana standpoint, if users don't care about visual confirmation that their YAML-based monitors have gone away they can opt out.

> Beats may come and go. I propose a similar proposal to amazon EC2 terminated instances where we still show dead beats for 24 hours

I read this after writing the above comment; in my opinion this design mentality reinforces the idea I proposed above, but I'm interested to hear others' thoughts.

> Add CM support to heartbeat

To verify - this is a beat-side change, not a Kibana development task. I guess that would be "Add heartbeat support to CM UI".

> Add pre/post-config hooks to CM (once CM supports this feature)

I got a peek into the primordial state of this feature in a recent code review, Matt's usage of hooks is cool and exciting.

**Comment by andrewvc** [comment]
@justinkambic Good question about external IDs. I'd wanted users to be able to use their own, but given the limitations of CM surfaced in the last review with @mattapperson  I'm fine with that not being in the initial version. Perhaps in a future version we could figure out a way to do this? Perhaps with some sort of custom metadata?

Good points about stale monitors/beats. There's definitely not one 'right' way of doing it. Would be curious to hear from others as well here. 

You are correct that the task indicated was a beat-side change.

Glad to hear that the hooks are coming along!

**Comment by dov0211** [comment]
I like the idea by @justinkambic on staling monitors, I think we should give the user the ability to manually delete them.

**Comment by andrewvc** [comment]
I've added a new section to the issue above titled "Advantages over keeping the current schema" that explains why we should ditch the time series indices more concretely.

**Comment by andrewvc** [comment]
One issue I want to call out here with the current roadmap, is that our current plans are to use the CM API directly. A risk here is that when alerting is added, that probably won't mesh with the CM API. So, we'll need to figure out a story there, potentially using our own API. Alternatively, maybe we could piggy-back on top of the CM API with the aforementioned hooks. @ph @mattapperson WDYT?

**Comment by dov0211** [comment]
you mention

> .heartbeat-state: Non-time-series index containing:> 
> The last state of individual heartbeat instances
> The last state of individual heartbeat monitors per geographic location
is the status gets override on every check?
if so how could we handle the alerting logic of  "Alert on X consecutive down checks" (not to be confused with X out of Y locations)

**Comment by andrewvc** [comment]
I'm closing this because we'll probably take a different approach toward management. Some of this was already effectively merged in https://github.com/elastic/kibana/pull/38895
