### ISSUE TITLE
[Monitor Page] Make empty states for monitor charts more uniform

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#144]
**Summary of the problem** 

Our charts show empty states, which is good. Unfortunately, they are not uniform, and it looks weird. See:
![image](https://user-images.githubusercontent.com/18429259/73539326-241db380-43fb-11ea-8695-c4f9d8c76aa3.png)

**Ideal solution** 

I think we should adapt the empty state on the left to a more general component that takes a few props to specify what the output should show.

**List known (technical) restrictions and requirements**
We have other charts, ideally we could share this component to all of them; this may include some unforeseen layout concerns, but I think it will probably be straightforward.

**Are there any pages or actions that relate to this feature?**
The Overview page has a chart that could probably benefit from this as well.

**Comment by katrin-freihofner** [comment]
Will be solved soon by https://github.com/elastic/eui/issues/3564
