### ISSUE TITLE
Add warning about near-expired SSL to "Overview" page

### ISSUE THREAD

**Issue by SlavikCA** [elastic/uptime#145]
Currently, the overview page will show monitors, which are UP or DOWN explicitly.
However, if endpoint's SSL cert is about to expire - nothing shown in the "Overview" page.
Even, if you open endpoint-specific page - there is only one gray line about it:
![Screen Shot 2020-02-02 at 11 06 01 PM](https://user-images.githubusercontent.com/6293679/73632499-b8ad2f00-4610-11ea-8b81-862b807c646b.jpg)

I'm proposing following feature:
- Add new status "WARNING" to the widget, which shows number of UP and DOWN monitors.
- The monitor is in the WARNING state, if it's SSL will expire in less than 7 days, or is expired.
- Add config option for the monitor to ignore state of SSL cert or configure number of days, when cert expiration becomes WARNING

**Comment by andrewvc** [comment]
This is already merged in, targeting 8.0!

**Comment by andrewvc** [comment]
See https://github.com/elastic/kibana/pull/64059
