### ISSUE TITLE
Overview Expandable Drawer Polish

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#148]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)

In 7.6 we made some last minute changes to the expandable rows. We now duplicate the URL field data in a couple places. I've attached a screenshot below:

![image](https://user-images.githubusercontent.com/131427/74866242-2ac38a80-5318-11ea-9d93-08b374a26571.png)

This differs from the [original mocks](https://github.com/elastic/uptime/issues/79) for the redesign in that the URL is duplicated. 

**Ideal solution** (optional)

Ideally we wouldn't display the URL twice, however, it may make sense in that the drawer always shows the full URL, while on a narrower monitor the URL is truncated. We may want to leave things as they are if we decide that's a valid concern.

**Comment by katrin-freihofner** [comment]
I think it's fine to have the information in both places. Especially if it is a long URL it could be handy to show the full text in the expandable row.

**Comment by andrewvc** [comment]
@katrin-freihofner I think you're right here. In that case I'll close this issue.
