### ISSUE TITLE
Downtime for SLA-Reporting

### ISSUE THREAD

**Issue by icefish-creativ** [elastic/uptime#15]
Uptime is a really great feature.i think it is useful for everybody or rather essential for SLA-Reporting. it would be nice you could set a SLA-Value , so you could also put a monitor on it and see if the service level are violated. And then i could finally throw Nagios/Icinga out the window. 

- a list of downtime per host/services
- via host/service I can set an SLA like 99,9;99,5 etc.
- SLA reporting where downtimes are calculated automatically (GUI vor Live and PDF)

cheers 

Tim

**Comment by andrewvc** [comment]
Thanks for posting this Tim. This is a great idea, and honestly not a heavy lift item as well.

I think a next step for this would be to create mocks.

@dov0211 @justinkambic @makwarth  what are your thoughts for this feature?

From a priority perspective, this feels lower than central management and alerting, so it's probably a ways down the road for now.

**Comment by makwarth** [comment]
Agree this would be a great addition. Thanks for posting, @icefish-creativ. 
I wonder how SLA per service would work with Heartbeat. Grouping of monitors?

**Comment by dov0211** [comment]
We had similar feedback from our SA team, (SLAs & integration within Observability solutions).
I agree with @andrewvc  to consider those 2 items straight after Central management and alerting.
several vendors provide rich capabilities in terms of SLAs calculation (Different KPIs, different calendars and working hours, downtimes, and more)
I believe we should start with calculating endpoint availability as a first phase, and think of those in the aspects of reporting and alerting.

**Comment by icefish-creativ** [comment]
@makwarth 
my pleasure
for example i have 4 Webserver in back of a Loadbalancer , so i need 5 monitors , 4 to Check the Server and 1 over the Loadbalancer with a Application Endpoint Check. I give the Customer a SLA on the Loadbalancer Check. the availability of the server itself is of secondary importance. 

Set Downtime on Groups is of course great :-). groups should base on custom fields , for example i added every message the custom fields host.environment(like prod, test),host.role(like web server,mysql) and host.setup(foobar1,foobar2)

**Comment by alogishetty** [comment]
Hey Guys, can we get this feature implemented? We are looking for these kind of metrics for defining SLO's and SLA's.

**Comment by dwchurch** [comment]
Yes, uptime would be immensely more valuable with this feature.

**Comment by mkkeffeler** [comment]
This is a huge blocker for us in our implementation of the elastic stack. We also are looking for these kind of metrics and think that this product can get far more value by providing these metrics.

**Comment by firewallkevin** [comment]
This is a superlatively useful feature that would extend elastic stack's use in IT Operations and analytics.

**Comment by andrewvc** [comment]
To add to this issue, some of the metadata that's a pre-req for calculating this is here: https://github.com/elastic/beats/pull/13672

I'm thinking we can add this along with this improvement in https://github.com/elastic/kibana/issues/44546 since the timeline calculation gives us that info for free more or less.

It would be great to hear from more people in this thread about what a downtime indicator would be used for.

Would you use it for defining breaches of contract? Purely for internal metrics with less strict guidelines? Something else? Would you use it from multiple geo locations?

**Comment by alogishetty** [comment]
We are mainly looking for internal metric with multiple Geo locations.
Defining contract breaches will also be a great addition to this feature.

Thank you,
Abhishek

**Comment by andrewvc** [comment]
@alogishetty it'd be great to hear more details here about contract breaches and geo locations.

1. Are you looking for individual statistics per geo location?
2. How would you define contract breaches? It may be hard or impossible for us to support custom formulas for SLA.

**Comment by alogishetty** [comment]
For geo locations, we often loose connectivity between data centers, we
would like to track how often we loose connectivity between data centers.

For contract breaches, we haven't considered until I saw it in your
previous email. This is something we would like to start talking about it
to our vendors and uptime will be a great tool to track breaches.

Regards,
Abhishek

**Comment by andrewvc** [comment]
@alogishetty hmmm, how do you track connectivity between data centers? Do you have a heartbeat job in each DC that does nothing but ping the other? Or do all your monitors run once in each DC? Both?

**Comment by andrewvc** [comment]
Fixed in https://github.com/elastic/kibana/pull/67790 (targeting 7.9.0).  If this doesn't resolve anyone in this thread's use cases feel free to open a new issue.
