### ISSUE TITLE
Add design around cert age (not expiry)

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#152]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)

Safari will [soon](https://thenextweb.com/security/2020/02/24/safari-will-soon-reject-any-https-certificate-valid-for-more-than-13-months/) start considering sites with certs > 13mo of age to be expired. We currently have the requisite data in our indices, but don't surface this in our UI at all.

We should add a second warning to our UI, perhaps on the details page, when certs are too old, even if they are close to expiring.

**User stories**

As an SRE I want to know when my sites are approaching the point where their certs will break. I'd like to be informed by the UI when common clients are approaching this limit.

Thanks to @shahzad31 for bringing this issue up

**Comment by katrin-freihofner** [comment]
This is how I imagine we could display this information:
<img width="697" alt="Screenshot 2020-02-28 at 13 02 12" src="https://user-images.githubusercontent.com/20965076/75547144-8eda0300-5a2a-11ea-9bdb-4167912e4bed.png">

I think we should add more information about what can be done to fix this in a link or tooltip. Let me know what's your opinion.

**Comment by andrewvc** [comment]
Closing, we have an in development product brief that covers this.
