### ISSUE TITLE
Certificate status table/list

### ISSUE THREAD

**Issue by katrin-freihofner** [elastic/uptime#159]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)
As someone responsible for managing TLS/SSL Certificates
I want be able to view a table of all my monitors with SSL certificates, the expiration of those certificates and if any are in A"alert" state
So that I have a single source of truth for my certificates that I can check against and proactively plan updates

Unique page in Uptime that shows a table
Table contains Monitor Name, SSL/TLS Certificate yes/no, Expiration Date & time, alert state column
Alert state column rules match triggers for sending an actual alert

**Comment by katrin-freihofner** [comment]
## Certificates page design
![certificate-list](https://user-images.githubusercontent.com/20965076/78560397-5641fc00-7816-11ea-956c-1dd37887db29.png)



Quick walk-through
![uptime-tls](https://user-images.githubusercontent.com/20965076/78559735-34944500-7815-11ea-83b2-18fc3149c305.gif)


## Navigating to the certificates page

### From the overview
There is a button in the top right corner of the monitor list panel.

<img width="1385" alt="Screenshot 2020-04-06 at 14 45 41" src="https://user-images.githubusercontent.com/20965076/78559802-5097e680-7815-11ea-8ff1-9a60751f56c4.png">


### From the monitor details

There is a button next to the certificate information. (Only there is the certificate information is available)

<img width="1385" alt="Screenshot 2020-04-06 at 14 45 22" src="https://user-images.githubusercontent.com/20965076/78559801-4e358c80-7815-11ea-81ec-ab32922741b1.png">

**Comment by andrewvc** [comment]
Looks great! I think you're right about the search box, we could add one that searches CommonName, SAN, `monitor.url.full` and `monitor.name` as a start. I'd think that would make sense vs. the kuery bar style where we break it out by field.  It would intuitively yield what you want 99% of the time.

**Comment by katrin-freihofner** [comment]
Update from yesterdays meeting:
- We will be able to show expired certificates (red indicator in status column)
- We are going to use the EuiDatagrid instead of a table. By default, we are going to display the following columns: Status, common name, monitors, issuer, and expiration date.
- Columns can be changed and sorted. (We don't need the density or fullscreen functionality)
- By default, the list is sorted by the expiration date
- We are going to add a searchbox. It will be a text search.
- The headline should say "certificates"

**Comment by katrin-freihofner** [comment]
[Figma link](https://www.figma.com/file/lDlGXMzUTnzAlHPQu7lZAH/Uptime?node-id=130%3A1)
[Prototype link](https://www.figma.com/proto/lDlGXMzUTnzAlHPQu7lZAH/Uptime?node-id=130%3A2&viewport=390%2C342%2C0.16354478895664215&scaling=min-zoom)

**Comment by andrewvc** [comment]
@katrin-freihofner to update this with I believe where we finally wound up on the design changes:

1. We will not use a datagrid, but rather a table
2. We will use expanding table rows, as on the overview page, to show SHA1/SHA256/MD5 fingerprints as well as the full monitor list.

Did I miss anything @drewpost @katrin-freihofner ?
