### ISSUE TITLE
Update 7.0 documentation on Heartbeat dashboard

### ISSUE THREAD

**Issue by dov0211** [elastic/uptime#16]
Since we don't support Heartbeat dashboards today, I think we should remove our documentation regarding Dashboard until we decide otherwise
https://www.elastic.co/guide/en/beats/heartbeat/7.0/configuration-dashboards.html

**Comment by alvarolobato** [comment]
This issue is now obsolete with the dashboards being in uptime-contrib. We have a new docs page for it https://www.elastic.co/guide/en/beats/heartbeat/7.1/view-kibana-dashboards.html
