### ISSUE TITLE
[Uptime UI] details for certificates

### ISSUE THREAD

**Issue by katrin-freihofner** [elastic/uptime#166]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)

As a user, I want to get more details about my TLS certificate.
@andrewvc @drewpost would you mind adding the data that we want to display for each certificate?

**User stories**

Prerequisite for this issue: https://github.com/elastic/uptime/issues/159

**Comment by andrewvc** [comment]
I'm starting to wonder if iterating here is necessary at this point. Since we have other features we can move forward on, I wonder if holding off until this is in the hands of users and getting real-world feedback would be worth delaying design work here for?

@drewpost thoughts?

**Comment by drewpost** [comment]
@andrewvc I'd tend to agree. I don't have a compelling customer use case for this yet. Common Name, Related monitors, Issuer and expiry date are the must have columns with a hidden option to display and copy the SHA are MVP, in my mind.
