### ISSUE TITLE
Ping List expand multiple items at once

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#169]
CC @drewpost @katrin-freihofner any thoughts/objections to the introduction of this functionality?

**Is your feature request related to a problem? Please describe.**
Today, the Ping List only allows us to expand one item at a time. It may be helpful to allow the user to expand multiple pings at once.

**Describe the solution you'd like**
Modify the component to support multiple expansions.

**Describe alternatives you've considered**
N/A, we would leave it as it is

**Additional context**
![Apr-13-2020 11-07-09](https://user-images.githubusercontent.com/18429259/79131699-04015d80-7d77-11ea-86dc-58a2c5b7d1e4.gif)

**Comment by drewpost** [comment]
I'm fine with this feature. We may want to "plus it" and add an option at the top to expand all rows at once and then telemeterise it and see how often that's being used

**Comment by katrin-freihofner** [comment]
@justinkambic absolutely! 👍 I think we should use this behavior for all our tables. I'm not so sure about the expand all, although I see that this could be useful...let me think about it.
