### ISSUE TITLE
Reset filter states button on overview page

### ISSUE THREAD

**Issue by shahzad31** [elastic/uptime#172]
**Is your feature request related to a problem? Please describe.**

When viewing overview, playing with different filters, it can be hard to reset page state, you have to manually clear all the filters or you have to clear the url. A hidden filter can wreck your results.

**Describe the solution you'd like**

There should be a reset button for filters, that should clear all the filters and make overview page to it's default state. 

Perhaps a button icon below refresh button 
![image](https://user-images.githubusercontent.com/3505601/79544178-e2fa7e80-808e-11ea-9934-f4ab6eb8c456.png)

**Comment by andrewvc** [comment]
I'm worried about clutter here, but what about making the "Overview" header clickable to reset state?

**Comment by shahzad31** [comment]
Another use case is if you have selected bunch of filters and if you unselect filters in such a way, that remaining few filters have no data , UI looks frozen and there is no way to uncheck those filters 
Example below, selected tag and port have no data, but there is no way to uncheck them.
![image](https://user-images.githubusercontent.com/3505601/80397191-1078d080-88b6-11ea-81df-7e991e048431.png)

**Comment by shahzad31** [comment]
not valid anymore
