### ISSUE TITLE
Keep links to other solutions in same tab

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#177]
Previously when navigating between Uptime and other apps/solutions in Kibana, we were opening a separate browser tab so the user didn't lose access to their Uptime view while the new app loaded.

With NP migration coming in 7.8, we will be able to link between apps in a much quicker fashion, with little latency/loading. In light of this, it's probably safe to change cross-app linking to open in the current tab.

A somewhat-comprehensive list of files impacted by this change:
- `location_link.tsx`
- `license_info.tsx`
- `manage_ml_job.tsx`
- `status_bar.tsx`
- `doc_link_body.tsx`
- `location_name.tsx`
- `monitor_list.tsx`
- `monitor_list_drawer.tsx`

**Comment by andrewvc** [comment]
I'm +1 on this. Thoughts @katrin-freihofner @drewpost ?

**Comment by katrin-freihofner** [comment]
That is great!

**Comment by andrewvc** [comment]
Zube went nuts

**Comment by shahzad31** [comment]
This is already done ,so closing,
