### ISSUE TITLE
Mircoprofile /health

### ISSUE THREAD

**Issue by suikast42** [elastic/uptime#18]
I have a Microprofile healthcheck endpoint that exposes multible checks. 

For example:

`{
"outcome": "DOWN",
"checks": [
  {
"name": "Serivce1",
"state": "UP",
"data": {
"timestamp": 1554719930201
}
},
  {
"name": "Serivce2",
"state": "UP",
"data": {
"timestamp": 1554719930201
}
},
  {
"name": "Serivce3",
"state": "DOWN",
"data": {
"timestamp": 1554719930201
}
},
  {
"name": "Serivce4",
"state": "DOWN",
"data": {
"timestamp": 1554719930201
}
},
  {
"name": "Serivce5",
"state": "DOWN",
"data": {
"timestamp": 1554719930201
}
}
],
}`

Is that possilbe to create an uptime metric per service in the same check  with heartbeat ?

**Comment by justinkambic** [comment]
@suikast42 it seems from looking at [the topic](https://discuss.elastic.co/t/custom-heartbeat-shipper/176165) that lead to the creation of this issue that you were able to resolve your problem. Is that the case?

**Comment by suikast42** [comment]
> @suikast42 it seems from looking at [the topic](https://discuss.elastic.co/t/custom-heartbeat-shipper/176165) that lead to the creation of this issue that you were able to resolve your problem. Is that the case?

Yes I solve the problem but with a custom collector soltion . Actually it based on spring but planed to migrate to go
