### ISSUE TITLE
Client Side Experience Metrics

### ISSUE THREAD

**Issue by drewpost** [elastic/uptime#180]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)
We want to start surfacing client side metrics collected from our RUM agents in a front-end focussed dashboard view. There's three key segments of this dashboard that we'll iteratively built towards.  This issue is for the first part of that dashboard focussing specifically on displaying top level metrics.

**User stories**
As a front-end engineer with an Elastic RUM tagged website
I want to have a dashboard showing me key client side experience metrics for my site
So that I can view key client-side focussed metrics in one place without additional cognitive load from non domain-related noise

I made a "drew" mockup of where we are heading (attached) and I also have highlighted the section this design issue relates to.

Created implementation issues to divide feature into smaller implementable issues Client side Metrics: https://github.com/elastic/kibana/issues/68515
Page Load Distribution: https://github.com/elastic/kibana/issues/68517
Impression Trends: https://github.com/elastic/kibana/issues/68518

<img width="1273" alt="End User Experience Dashboard - Stage One Client SIde Metrics" src="https://user-images.githubusercontent.com/7509768/81050495-fc396280-8eb7-11ea-95f6-b45c9baaca1e.png">

**Comment by katrin-freihofner** [comment]
I think this is how it could work
![rum-dashboard-wireframes - large@2x (1)](https://user-images.githubusercontent.com/20965076/81186697-6be04800-8fb3-11ea-95da-36f84f6124b6.png)

<img width="821" alt="Screenshot 2020-05-06 at 14 53 01" src="https://user-images.githubusercontent.com/20965076/81178995-536b3000-8fa9-11ea-87bf-1f78e1565d77.png">

**Comment by drewpost** [comment]
++ I like these. Is your view to then add the bottom panel onto this same screen or to have a tabbed nav?

**Comment by katrin-freihofner** [comment]
Very good question! I assumed it should be on the same view - which could make the filtering easier.

**Comment by katrin-freihofner** [comment]
Quick update
<img width="1442" alt="Screenshot 2020-06-04 at 16 31 47" src="https://user-images.githubusercontent.com/20965076/83770083-f08cb780-a680-11ea-8bda-455727e001ed.png">

Todo
- tooltip for charts? (could be our standard tooltips)
- breakdown action

**Comment by roncohen** [comment]
1. Page load distribution graph is actually a histogram right? The current graph indicates that exactly 1.8% of page loads finished in exactly 1.2s. In reality, there's a bucket around 1.2s, maybe ranging from 1.0s to 1.4s, and the amount of page loads that finished in the range 1.0s to 1.4s amounts to 1.8% of the number pages loaded? If that's right, i think that graph should be a bar chart with each bar representing the bucket. It's similar to our distribution graph for backend.
![image](https://user-images.githubusercontent.com/744/84648367-3d844f80-af05-11ea-9911-24ada6d197a4.png)
the alternative is to show a graph that is accumulative and has a y-axis that starts at 0% and goes to 100% and a line that goes diagonally up and to the right as the page load time increases. 
1. From what i saw in the PR, that graphs enables zooming in by using the mouse to select an area of the graph. For every other graph that I know of in Kibana, zooming in will change the overall time window you have selected. That doesn't work for this graph and having this functionality will be a departure from the usual experience.
1. What does "Impression trend" mean? it's showing number of page views right? We use the "page views" terminology on the left side. If it's the same number, let's make sure we use the same terminology. 
1. How did we decide on the order of the metrics on the left side? Why is frontend and backend not together?
1. These numbers are aggregates. If they are averages, let's make sure it's clearly stated.

**Comment by drewpost** [comment]
Added Core Vitals in 7.10 https://github.com/elastic/uptime/issues/233
