### ISSUE TITLE
Add Visualizations in Certificate Page

### ISSUE THREAD

**Issue by shahzad31** [elastic/uptime#181]
**Is your feature request related to a problem? Please describe.**
Currently we have certificate list as a table in Cert page, getting an overview from table can be hard.

**Describe the solution you'd like**

I would like to have few visualizations on certificate page, it can be a bar chart, describing upcoming charts expiring in a month, so each bar essentially tells you how many certs are expiring in upcoming months.

Also a donut chart can be used to categorize, expired, expiring soon and valid certs.

Visualization always makes a page attractive and provides easy to read useful information.

**Comment by justinkambic** [comment]
I have an idea for a useful visualization for this page as well.

I wanted to create a visualization that answered the question, "how are all my certs doing in terms of expiration/age right now?". The motivation to look at this viz would be to glean the overall status of all certs in the index in a few seconds.

An implementation of this visualization would display the monitor/cert info on hover, and clicking could update the search bar to filter on that cert. In my original thinking, both the `not valid after` and `not valid before` fields would be accounted for in a single chart, but attempting to display them together was confusing.

I've tried my hand at drawing this viz; I'll share it internally, not looking to expose the mockup publicly after thinking it over.

**Comment by shahzad31** [comment]
i think this is a great idea, it will improve user understanding of the
severity, it's far simpler to understand, i think this visualization can be
used to give users an overview and table will compliment the whole picture
including search.
