### ISSUE TITLE
Visitor Breakdown

### ISSUE THREAD

**Issue by drewpost** [elastic/uptime#184]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)
As RUM data includes impressions for all visitors to a monitored website, there is great variation in the user cohorts as defined by their device type, OS, browser and location. These variables can have a big impact on overall user experience but can be optimised for given that the makeup of key cohorts is known. Very often the people accessing this data don't have access to other platforms that will show this type of information so it's an important piece of context to include on a RUM dashboard.

**User stories**
As a front-end engineer with an Elastic RUM tagged website
I want to have a dashboard showing me the breakdown of user cohorts by key meta data points on my site
So that I can understand, on an ongoing basis, what a typical user of my site looks like
AND so that I can use the information to make prioritisation/scope decisions

"Drew Mockup"

<img width="1273" alt="End User Experience Dashboard - Stage Two" src="https://user-images.githubusercontent.com/7509768/81150668-23576900-8f78-11ea-8825-bae0c09a002f.png">

**Comment by katrin-freihofner** [comment]
I think this is how it could work
![rum-dashboard-wireframes - large@2x (1)](https://user-images.githubusercontent.com/20965076/81186697-6be04800-8fb3-11ea-95da-36f84f6124b6.png)

<img width="821" alt="Screenshot 2020-05-06 at 14 53 01" src="https://user-images.githubusercontent.com/20965076/81178995-536b3000-8fa9-11ea-87bf-1f78e1565d77.png">

**Comment by andrewvc** [comment]
Fixed in https://github.com/elastic/kibana/pull/71428
