### ISSUE TITLE
Impactful Metrics

### ISSUE THREAD

**Issue by drewpost** [elastic/uptime#185]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)
RUM providers are all good at showing the metrics (measurements) but less good at showing some of the reasons WHY the metrics are the way they are. With this section, we are surfacing a list of data points that are highly impactful on site speed to help people using the dashboards understand the impact and point them in a direction to attempt optimisation. 

**User stories**
As a front-end engineer with an Elastic RUM tagged website
I want to have a view on some key site speed indicators that represent impact on user experience on my most popular pages
So that I can understand the impact technical implementations are having on my most heavily trafficked pages

**List known (technical) restrictions and requirements**
These metrics only come from a portion of browsers. Some browsers (specifically Mobile Safari) do not surface these metrics yet. Mobile Safari is a statistically significant volume of traffic so it's important we declare this to the user so they can take that into consideration when looking at the data

<img width="1273" alt="End User Experience Dashboard - Stage Three" src="https://user-images.githubusercontent.com/7509768/81155159-8fd46700-8f7c-11ea-97bb-e3d8a009529f.png">

**Comment by katrin-freihofner** [comment]
I think this is how it could work
![rum-dashboard-wireframes - large@2x](https://user-images.githubusercontent.com/20965076/81178803-0e46fe00-8fa9-11ea-85b0-7d2395e68e4b.png)
<img width="821" alt="Screenshot 2020-05-06 at 14 53 01" src="https://user-images.githubusercontent.com/20965076/81178995-536b3000-8fa9-11ea-87bf-1f78e1565d77.png">

**Comment by katrin-freihofner** [comment]
Initial design
<img width="1217" alt="Screenshot 2020-06-04 at 16 35 03" src="https://user-images.githubusercontent.com/20965076/83770473-642ec480-a681-11ea-963c-5d2d8167b9c7.png">

- I used a table for the errors. Is this all the data we need there?
- With the data grid for the high traffic pages, users would be able to switch out columns by themselves. If there is a way of proper grouping or reducing the number of columns, I'm happy to discuss other solutions.

**Comment by katrin-freihofner** [comment]
Implemented by https://github.com/elastic/kibana/issues/73037
