### ISSUE TITLE
Friendly Segmentation/Filtering Controls

### ISSUE THREAD

**Issue by drewpost** [elastic/uptime#186]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)
One of the biggest problems with RUM data is that the experiences within it are so variable based on what cohort they belong to, that you really need to break down the data to get actionable insight. Right now this requires the user to know exactly what data points they are looking for (ie the field name instead of the user friendly name) and for them to have an awareness of all the possible options. We want to curate the experience to focus on segments and filtering options that help a user dive down in a meaningful way without a steep learning curve as well as serving as a landmark for the values selected in the data below.

**User stories**
As a front-end engineer with an Elastic RUM tagged website
I want to be able to explore my client side data in the RUM dashboard by individual or groups of meta data points (cohorts)
So that I can explore how the data varies depending on a number of underlying factors
AND I don't need to know a query language
AND I can be guided towards meaningful ways to segment the data
AND so that I can see what filters are applied to the charts and data I'm looking at

**Comment by katrin-freihofner** [comment]
<img width="1151" alt="Screenshot 2020-05-06 at 16 14 44" src="https://user-images.githubusercontent.com/20965076/81187774-c332e800-8fb4-11ea-8d27-56bd1aa0533c.png">

@drewpost did I understand this correctly, that you expect our users to select multiple options? For example "Safari or Chrome". Do you think it could work if we state something like "Multiple browsers" in this case?
<img width="1236" alt="Screenshot 2020-05-06 at 16 20 51" src="https://user-images.githubusercontent.com/20965076/81188433-9501d800-8fb5-11ea-944e-b53aa02e0402.png">

**Comment by drewpost** [comment]
@katrin-freihofner Yes, that's what I'd expect to see for a multi-option selection. If I click on the value it opens up the filter selection box with the currently selected options visible at that point.

**Comment by katrin-freihofner** [comment]
Another question that came to my mind:

Is there a reason why we should not use the filter bar that is used in APM? 
<img width="224" alt="Screenshot 2020-05-14 at 09 05 56" src="https://user-images.githubusercontent.com/20965076/81903537-2f6ba800-95c2-11ea-9d83-e01543e22b92.png">

It seems more scaleable to me.

**Comment by formgeist** [comment]
We'll be making some improvements to that component soon-ish https://github.com/elastic/kibana/issues/49153

**Comment by katrin-freihofner** [comment]
> We'll be making some improvements to that component soon-ish [elastic/kibana#49153](https://github.com/elastic/kibana/issues/49153)

Great - thank you!

**Comment by katrin-freihofner** [comment]
The aggregation does not fit in the filter bar in my opinion. @drewpost the aggregation should be the same for the whole screen and all charts, right?

**Comment by drewpost** [comment]
Hi @katrin-freihofner - the filter bar drives which results should be included in all charts and tables on the page. Hierarchically, the filter bar is the main control for what data you see. Charts with further breakdown capabilities (ie the performance distribution) would always break down the data after the filters had been applied to it. ie If I filtered by iOS and then broke down the chart by Operating system, I'd only expect to see variants of iOS in there
