### ISSUE TITLE
Make IDs mandatory, and hosts singular in heartbeat 8.0

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#189]
There are rarely situations where users really benefit by having an auto-generated ID. In every situation we've seen in the wild it makes more sense to specify one, even if that ID is just the URL. Having IDs gives the UI continuity and makes programming sane.

Along with this, we should rename the `hosts`, `ports` and `urls` options in heartbeat to  `host`  `url`, and `port` and make those only accept singular values. When multiples are used we generate a hash based on the host and tack it on the end, again creating confusing IDs. While not as bad as the former, it generally creates a weird UX.

There is a potential performance downside here, as multiple ports will do independent DNS lookups, one per port.

We don't want to break 7.x, but I move we deprecate this in 7.x and require these values in 8.0+.

Furthermore, we can warn against this in the UI by detecting the use of generated IDs and alerting users to do specify them manually.

**Comment by paulb-elastic** [comment]
Closing, led by leading with fleet and make it minor
