### ISSUE TITLE
Service uptime percentage

### ISSUE THREAD

**Issue by OrangeDog** [elastic/uptime#19]
Somewhere in the uptime UI there should be the total uptime percentage (per-service and overall), probably with a configurable duration. One year is probably a good default.

A big use-case for uptime monitoring is for SLAs, which are typically concerned with this number.

**Comment by dov0211** [comment]
proposed wireframe
![image](https://user-images.githubusercontent.com/38371227/56275222-ee783a00-6108-11e9-99a0-bb13690d0900.png)

**Comment by BattinaVijayaBhaskarRao** [comment]
Hey, do we have a timeline by when this feature can be implemented?
This feature would help a great for SLA reporting.

**Comment by Svengalx** [comment]
This would be an excellent addition to an already great service. It is fairly important for SLA reporting for us too.

+1

**Comment by andrewvc** [comment]
This should be resolved in https://github.com/elastic/kibana/pull/67790 targeting 7.9.0 . If there are other features desired please open a new issue.
