### ISSUE TITLE
Show location of monitored site in Uptime UI

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#191]
Per [this discuss thread](https://discuss.elastic.co/t/help-with-heartbeat-setup-of-locations/227555/8) it might be nice to show the location of the monitored site in the Uptime UI.

Right now the syntax in heartbeat is tricky, and we only show the source of the info in Uptime.

One challenge here is that this would only work for monitoring sites that have one geo location, many monitored URLs are geographically distributed

**Comment by shahzad31** [comment]
@andrewvc isn't this duplicate of https://github.com/elastic/uptime/issues/178?

**Comment by andrewvc** [comment]
Ah, you're right @shahzad31 

Closing as a dupe of https://github.com/elastic/uptime/issues/178
