### ISSUE TITLE
Alerts created from Uptime app do not allow filter specification via selecting from suggestion

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/uptime#203]
7.7.0 ESS in Azure

**Describe the bug**
When creating a filter for an alert I cannot choose one of the suggestions that Kibana provides.
**To Reproduce**
1. Click on Alerts > Create
2. Start typing in the filter, for example `monitor`
3. Try clicking on `monitor.name`
4. Notice that focus shifts away from the flyout

**Expected behavior**
I expect that the suggestion that I choose will be used for the filter

Here is a GIF
![Alert](https://user-images.githubusercontent.com/25182304/82002926-1c41f200-962d-11ea-8bad-892b9b351fbe.gif)

**Comment by shahzad31** [comment]
Seems like a bug in on mouse click event, @DanRoscigno can you please verify if it works fine with keyboard ?

**Comment by DanRoscigno** [comment]
> Seems like a bug in on mouse click event, @DanRoscigno can you please verify if it works fine with keyboard ?

Interesting, I never tried to use keyboard.  What should the experience be? Something like type, tab, return?

**Comment by shahzad31** [comment]
so you will type, and will see suggestions, and using key up/down, once the field, you want to select, press enter.

**Comment by DanRoscigno** [comment]
keyboard navigation works partially.  If the suggestion list does not need to scroll then it works.  If it needs to scroll I have to use the mouse to scroll and then the arrow to highlight the proper entry, and then enter to select.  If the list does not need to scroll then I can just use keyboard.

**Comment by shahzad31** [comment]
Great, thanks for verifying, i have put a PR, will fix all mentioned issues.

**Comment by DanRoscigno** [comment]
Thanks!!!
