### ISSUE TITLE
Monitor List can say "no monitors found" while still loading

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#207]
**Describe the bug**
We should check if the Monitor List component is still `await`ing a server response before allowing the table's `noItemsMessage` to be `"No uptime monitors found"`. If the query takes a long time (this happens to me when I put 100 items on the page at once), it will say there weren't any found and a couple of seconds later display the items.

**To Reproduce**
1. Configure 2+ heartbeat instances to watch 100+ monitors
2. Set the Monitor List's size to 100
3. Use the Uptime app's date picker refresh button
4. Observe the message shown in the table

**Expected behavior**
We want this message to indicate that the list is `loading`. This will require the creation of a new message to display in the translations folder.

![May-18-2020 16-14-19](https://user-images.githubusercontent.com/18429259/82255460-abe3eb00-9922-11ea-86f1-b607c4e7af2f.gif)

There are cases where `loading === true` and we display a non-loading message:

![image](https://user-images.githubusercontent.com/18429259/82255591-e6e61e80-9922-11ea-8ba9-1b0f6151e7a6.png)

**Comment by shahzad31** [comment]
i suspect this will be resolved once we merge https://github.com/elastic/kibana/pull/66216

**Comment by justinkambic** [comment]
I'm about to review that, so if it's no longer an issue I'll add `resolves` keywords to that PR.

**Comment by shahzad31** [comment]
i believe this has been fixed in https://github.com/elastic/kibana/pull/66216
