### ISSUE TITLE
Wafflemap dashboard for uptime

### ISSUE THREAD

**Issue by syedsfayaz** [elastic/uptime#21]
It would be nice we can see the same GUI as an infrastructure Dashboard for uptime. where we can monitor multiple sites status as cubes.

Mostly people will want to monitor their site status on main dashboard to see if its up or down. 

In my case, we are only monitoring status of multiple internal sites. we are monitoring 500 server urls http status. My requirement is only to see what the last status of my http health check is.

It will be very convenient to categorize them with a custom field and monitor. The infrastructure dashboard GUI is very appealing. We can show site status as green/red color. If we need more details we can drill down to see whats going on.

![image](https://user-images.githubusercontent.com/26099918/56146884-f646ab80-5f5b-11e9-9534-c38874ef5a25.png)

**Comment by andrewvc** [comment]
Thanks for the idea! Where do you think it'd make sense in the UI? On the current overview page, or maybe an entirely separate one? I'm leaning toward the latter.

**Comment by syedsfayaz** [comment]
Any thing should be fine.

**Comment by andrewvc** [comment]
Coming back to this, is the idea here to have higher density by using more compact squares rather than the current list?

**Comment by syedsfayaz** [comment]
Yes, We can have more density of squares. The squares can just show status as red or Green. More details can be shown when hover over the square by showing what service or serverurl it is.

**Comment by shahzad31** [comment]
i think it's definitely an interesting use case, it's just like the way cctv control rooms works.
There can be 100's of cameras in a building, but usually softwares allows you to just monitor couple of them on a main page, for a focused view. So you are only looking at important ones like entry/exit.
So if we go by that, that would probably be an overview page, then we can have all monitors page and details page. But this besides designs certainly will require managed from back-end.

**Comment by andrewvc** [comment]
After discussing this as a team, our upcoming redesign https://github.com/elastic/uptime/issues/79 should handle the use cases here, albeit with a more traditional list. We've decided this isn't a feature we'll be tackling in the near to medium term. One of the deciding factors was that waffle maps don't scale as well as lists. They can be hard to read at high cardinalities. 

While we may take a different view in the future, we're going to close this issue to help tidy up our github issues. Thanks for the detailed writeup @syedsfayaz , it is much appreciated!
