### ISSUE TITLE
Monitor Availability Reporting

### ISSUE THREAD

**Issue by katrin-freihofner** [elastic/uptime#212]
Information about all locations and their availability.

Open questions:

Displaying monitor level availability on the overview page?
UI indicator for the absence of expected data (ie Heartbeat not running when expected)

**Comment by katrin-freihofner** [comment]
[Product brief](https://github.com/elastic/observability-dev/issues/791)

**Comment by katrin-freihofner** [comment]
# Design update

I tried the idea @shahzad31 had, to toggle the table and the world map. They present kind of the same information, but the table shows more details. As we were discussing [hiding the worldmap](https://github.com/elastic/uptime/issues/192) this could be a way to handle that.

Also, I took the chance to clean-up the existing UI elements a bit.


<img width="1370" alt="Screenshot 2020-05-28 at 19 44 51" src="https://user-images.githubusercontent.com/20965076/83175131-b9b42000-a11b-11ea-9463-22b5ccfe928d.png">


**Small screens**
<img width="579" alt="Screenshot 2020-05-28 at 19 43 16" src="https://user-images.githubusercontent.com/20965076/83175001-85406400-a11b-11ea-9370-611ccd9919c2.png">

**Wide screens**
<img width="932" alt="Screenshot 2020-05-28 at 19 45 57" src="https://user-images.githubusercontent.com/20965076/83175229-e10aed00-a11b-11ea-8bd7-8ec65313dce8.png">


## Demo
![uptime-availability](https://user-images.githubusercontent.com/20965076/83174422-ac4a6600-a11a-11ea-875e-37a51aaac4b2.gif)

@drewpost @andrewvc @shahzad31 @justinkambic let me know if you have any feedback.


[Prototype](https://www.figma.com/proto/lDlGXMzUTnzAlHPQu7lZAH/Uptime?node-id=525%3A0&viewport=636%2C1526%2C0.25&scaling=min-zoom)
[Figma file](https://www.figma.com/file/lDlGXMzUTnzAlHPQu7lZAH/Uptime?node-id=525%3A0)

**Comment by andrewvc** [comment]
I like the toggle. I think it'll also be simpler to implement, and handle changes to content a bit better as well (what if the number of pages decreases). ++ on moving forward here.

**Comment by shahzad31** [comment]
I am also in favour of toggle but only in case space is the constraint, otherwise we should keep both views intact. I think for bigger screens, it should be ok, since list columns are mostly going to be very small, they won't take enough space.

**Comment by justinkambic** [comment]
We persist some UI state, like page size. The toggle seems like something we might want to consider persisting as well. If we keep the toggle, as a user I'd probably find it really annoying if I prefer one view over the other and it resets any time the local state is deleted.

**Comment by katrin-freihofner** [comment]
Latest update:
- we moved the overall availability from the right to the left
- the table and worldmap have a new headline "Monitor locations" 
<img width="1376" alt="Screenshot 2020-06-03 at 10 51 55" src="https://user-images.githubusercontent.com/20965076/83617134-f2734f80-a588-11ea-9db2-e59cbb753399.png">

**Comment by shahzad31** [comment]
We are going to rename "Monitor locations" label to "Monitoring from"
