### ISSUE TITLE
Uptime integration with APM

### ISSUE THREAD

**Issue by dov0211** [elastic/uptime#22]
APM and Uptime are different approaches for end user monitoring (Active vs Passive, or Real vs Synthetic), a user can gain value on viewing Uptime metrics alongside APM metrics.
we would like to provide the ability to drill down from our Uptime app into APM in Kibana.
When drilling into APM we want the user to get relevant results in APM, therefore we would pass the `url.domain` field as a parameter to APM Kuery bar
![image](https://user-images.githubusercontent.com/38371227/56166140-7bbe7000-5fdd-11e9-8582-f91cfe7bc100.png)

**cc:** @justinkambic

**Comment by sqren** [comment]
@dov0211 Thi can be closed, right?
