### ISSUE TITLE
Support for APM service.name in Heartbeat/Uptime

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#220]
Today, linking between Uptime / APM is done only via URL. It would be trivial to add a common option to heartbeat monitor options `service_name`, that added the appropriate field for APM. This could then be used by the integrations links on the monitor overview/detail page to cross-link to APM.

**Comment by drewpost** [comment]
Trivial effort and high return - I am in favour of prioritising this. Can we elaborate a bit more with some user stories to really bring home the value of it @andrewvc and then discuss with the team when to bring it in?

**Comment by andrewvc** [comment]
As a user of both APM and Uptime, I'd like to more easily navigate between the two apps. Being able to jump from an uptime outage to an APM analysis of the same outage is something I expect. I'd like to be able to view a discrete error, then easily view that time segment in the relevant service in APM.

**Comment by tbragin** [comment]
+1 on this effort. Aligning and using most important ECS fields across our apps is so important. 

cc @elastic/observability-pm @roncohen @alvarolobato

**Comment by cyrille-leclerc** [comment]
+1 on this initiative. 

@andrewvc minor comment: I think that the ECS field name is `service.name` rather than `service_name` (see [Elastic Common Schema (ECS) / Service Fields](https://www.elastic.co/guide/en/ecs/master/ecs-service.html)). 

The next integration between APM and Uptime my wishlist is the usage of `transaction.id` and `trace.id` in uptime 👼

**Comment by andrewvc** [comment]
@cyrille-leclerc great ideas for `transaction` stuff in future versions! Heartbeat PR is here: https://github.com/elastic/beats/pull/19932

@katrin-freihofner any input on this? Adding the menu item to the integrations list should be very straightforward to the uptime UI.

**Comment by katrin-freihofner** [comment]
I think this a great initiative. Linking to the service from the integrations menu should work. I think this could even work better with the new [integrations menu](https://github.com/elastic/uptime/issues/128). A shared component for this is already available.
