### ISSUE TITLE
[Uptime] Ability to view sample document in discover

### ISSUE THREAD

**Issue by shahzad31** [elastic/uptime#222]
**Is your feature request related to a problem? Please describe.**
In heartbeat we have some data that's hidden from uptime app, even though we are adding new features, it's always hard to catch up, is user needs to debug some problem, they may needs to look at raw data. Which can now be done using creating hearbeat index pattern and then taking a look at discover manually.

**Describe the solution you'd like**
APM has a link called, view sample document for each transaction from which user can directly go to discover and view the sample data 

![image](https://user-images.githubusercontent.com/3505601/84735374-a7533680-afa3-11ea-96bb-a547417035fd.png)

We can do the same for uptime perhaps on uptime details page, from where user can view the latest document in discover for respective monitor.

**Describe alternatives you've considered**
A document can be viewed using dev tools or discover manually by creating an index pattern.

**Comment by tbragin** [comment]
Seems like a good idea, especially from consistency purposes.

**Comment by andrewvc** [comment]
This is a great idea. Maybe it can go in the ping history? @katrin-freihofner what are your thoughts?

**Comment by paulb-elastic** [comment]
@elastic/observability-design do you have a recommendation where the link/action should go?

**Comment by shahzad31** [comment]
My suggestion is to add Discover app icon in Ping list table actions.
