### ISSUE TITLE
Ping histogram should generate meaningful buckets

### ISSUE THREAD

**Issue by shahzad31** [elastic/uptime#228]
Right now ping histogram uses `auto_date_histogram` it hasn't been working well to create buckets, it creates buckets, either too big or too small. 

I think if user selects a range like for example last 24h, in that case histogram should generate 1h interval, same goes for last 7 days, should result in 1d interval.That way by looking at histogram one can have meaningful interoperation. We should have sort of lookup table to cover few common intervals like 1s, 5s, 1m, 15m, 30min, 1h, 1d, 1week, 1month etc. For other date ranges we can revert to default behavior of histogram.

![image](https://user-images.githubusercontent.com/3505601/86138057-40c73000-baee-11ea-89e1-b18273c002de.png)

**Comment by justinkambic** [comment]
We should at the very least calculate the interval to prevent massively wide buckets from forming, rather than relying on `auto_date_histogram`. Coupled with common-sense intervals like the issue describes it should provide a more meaningful viz.
