### ISSUE TITLE
Monitor list does not include monitors without TLS

### ISSUE THREAD

**Issue by hendry-lim** [elastic/uptime#231]
**Describe the bug**
The Uptime UI uses a query which requires `tls.server` field value.

**To Reproduce**
1. Configure a http/icmp monitor in heartbeat
2. Observe the monitor events are ingested into ES
3. Go to Kibana - Uptime
4. Monitor is not listed on the monitor list

**Expected behavior**
All monitors, including http, icmp, etc, should be listed on the monitor list, not only monitors which have `tls.server` field.

**Debug logs**
<details>
<summary>Query</summary>

```
GET heartbeat-*/_search
{
  "from": 0,
  "size": 10,
  "query": {
    "bool": {
      "filter": [
        {
          "exists": {
            "field": "tls.server",
            "boost": 1
          }
        },
        {
          "range": {
            "monitor.timespan": {
              "from": "now-15m",
              "to": "now",
              "include_lower": true,
              "include_upper": true,
              "boost": 1
            }
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  },
  "_source": {
    "includes": [
      "monitor.id",
      "monitor.name",
      "tls.server.x509.issuer.common_name",
      "tls.server.x509.subject.common_name",
      "tls.server.hash.sha1",
      "tls.server.hash.sha256",
      "tls.server.x509.not_after",
      "tls.server.x509.not_before"
    ],
    "excludes": []
  },
  "sort": [
    {
      "tls.server.x509.not_after": {
        "order": "asc"
      }
    }
  ],
  "aggregations": {
    "total": {
      "cardinality": {
        "field": "tls.server.hash.sha256"
      }
    }
  },
  "collapse": {
    "field": "tls.server.hash.sha256",
    "inner_hits": {
      "name": "monitors",
      "ignore_unmapped": false,
      "from": 0,
      "size": 3,
      "version": false,
      "seq_no_primary_term": false,
      "explain": false,
      "track_scores": false,
      "_source": {
        "includes": [
          "monitor.id",
          "monitor.name",
          "url.full"
        ],
        "excludes": []
      },
      "sort": [
        {
          "monitor.id": {
            "order": "asc"
          }
        }
      ],
      "collapse": {
        "field": "monitor.id"
      }
    }
  }
}
```
</details>

This is observed in both `7.8.0` and `7.9.0-SNAPSHOT`.

**Comment by shahzad31** [comment]
Hi @hendry-lim thanks for opening the issue.

Actually the query you have posted is to get list of certificates from certs page. Uptime monitor list does shows list of all monitors. Monitor list query doesn't have exist filter for `tls.server` 

Would you able to show the heartbeat config(masked), i will try to reproduce the issue you are facing.

**Comment by hendry-lim** [comment]
Hi @shahzad31 thank you for your fast reply.

I can't seem to replicate this either. I think we can close this for now.

I sincerely apologise for the false alarm.
