### ISSUE TITLE
Core Vitals RUM Panel

### ISSUE THREAD

**Issue by drewpost** [elastic/uptime#233]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)
Core Vitals has a massive impact on google ranking/placement and is a solid representation of user experience. We want to feature it on our RUM dashboard

**User stories**
As a front-end engineer with an Elastic RUM tagged website
I want to see my Core Web Vitals scores for my my origins
So that I can understand what impact my technical metrics are having on user experience and Google ranking

ACs

We'll need to add the following metrics to the RUM page (all averages):

1. CLS: Cumulative Layout Shift
2. FID: First Input Delay
3. TBT: Total Blocking Time
4. LCP: Largest Contentful Paint
5. FCP: First Contentful Paint

- We can put them in one UI block, though we may later group CLS,LCP and FID under Core vitals. 
- These values all have their own ranges of good to warning to bad, and should probably change color from green -> yellow -> red. Each metric has its own thresholds for those categories (we will use the mobile guidelines from google for these thresholds which are more permissive about timings).
- We need a note somewhere in the UI that these are only available in chromium based browsers.

**List known (technical) restrictions and requirements**
The data that powers this is not available from all browsers. We need to call this out in the UI
We can't segment desktop / mobile effectively yet

**Comment by katrin-freihofner** [comment]
@drewpost 
I think we could use a panel with Eui stats like the one we already have for this

<img width="1428" alt="Screenshot 2020-07-21 at 12 09 11" src="https://user-images.githubusercontent.com/20965076/88041679-0a0f9300-cb4b-11ea-9095-874de870ca6c.png">

+ a button group to toggle mobile vs desktop
+ a subheadline stating that is data is not from all browsers

Can we add information about how these stats changes compared to the previous deployment or month?

**Comment by drewpost** [comment]
@katrin-freihofner - I think that's OK however I'm not sure how that would communicate the percentage of people within the bands for each score? ie if <2s is good 2-4s is ok and >4s is bad - we need to show the percentage of impressions/results that fall into those bands for the given period. That may be a bit much to communicate textually. 

I also LOVE the ability to compare periods of time. Really think that would be an incredible addition to this feature.

**Comment by andrewvc** [comment]
This requires the RUM agent need to make changes to add these metrics to transaction docs and out of spans. See https://github.com/elastic/apm-server/issues/3972

**Comment by katrin-freihofner** [comment]
## Overview 
### All core vitals
<img width="1164" alt="Screenshot 2020-07-30 at 12 46 49" src="https://user-images.githubusercontent.com/20965076/88914336-c3b0e700-d262-11ea-8005-804b1ce6e2d6.png">

## Details
### Tooltips
Tooltips could provide further details what these bar charts and the percentages mean.
<img width="840" alt="Screenshot 2020-07-30 at 12 44 23" src="https://user-images.githubusercontent.com/20965076/88914360-cd3a4f00-d262-11ea-9ae6-586de63ff0e0.png">

### Inline help
If we need to show how these are calculated and what they mean, we add an icon next to the headline (triggers and overlay or tooltip)
<img width="953" alt="Screenshot 2020-07-30 at 12 40 56" src="https://user-images.githubusercontent.com/20965076/88914541-0ffc2700-d263-11ea-94b4-30bcb1647066.png">

### Compare
We could add a "compared to previous deployment" information.
<img width="739" alt="Screenshot 2020-07-30 at 12 41 19" src="https://user-images.githubusercontent.com/20965076/88914405-de835b80-d262-11ea-83f7-1c949325afc2.png">


@drewpost @andrewvc let me know if you have any feedback for me. Also, I definitely need some help with the wording.

**Comment by katrin-freihofner** [comment]
Do we always have all metrics available? Are there any corner cases (no data/not enough data...) I should be aware of?

**Comment by hmdhk** [comment]
Thanks @katrin-freihofner , the design looks great.

One suggestion: Instead of the message for data availability, we can show the percentage of transactions that had this data compared to the ones that didn't. e.g. "These metrics are representative of 83% of transactions due to browser support" or similar.

**Comment by katrin-freihofner** [comment]
@jahtalab thank you, that is great input. I will update the message.

**Comment by katrin-freihofner** [comment]
[Figma file](https://www.figma.com/file/2v4vCAIJtT7faWsZo7VE2F/Dashboard?node-id=65%3A2289)
