### ISSUE TITLE
[RUM UI] Add notification for agent upgrades to UI

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#234]
**Is your feature request related to a problem? Please describe.**

For some features, like the upcoming web vitals, users will need to ensure that users are running the latest version of the RUM agent to see any data. This issue will certainly come up again, and we should strive to keep users on the latest copy of the agent.

**Describe the solution you'd like**

On the RUM dashboard we could add a small notification somewhere letting users know that their agent is out of date. We can calculate this by finding the maximum agent version, and comparing that to the released agent version. We need to investigate if there's a public API that indicates the latest agent version, as we'd need to hit that to determine this. This obviously would not work offline.

**Describe alternatives you've considered**

An alternative would be indicating on each feature the minimum agent version needed, however this would get very complex on a feature by feature basis.

CC @drewpost @katrin-freihofner @shahzad31 @jahtalab  @vigneshshanmugam

**Comment by katrin-freihofner** [comment]
Like this?
<img width="1128" alt="Screenshot 2020-07-20 at 17 50 06" src="https://user-images.githubusercontent.com/20965076/87958158-7938a900-cab1-11ea-81a6-b2de3f81eab8.png">

I suggest adding an action for the user to upgrade.

@drewpost @andrewvc

**Comment by katrin-freihofner** [comment]
I talked to @drewpost about this and we are going to change the message a bit. It should say


RUM agent vX.X [Upgrade](https://www.elastic.co/guide/en/apm/agent/rum-js/master/upgrade-to-v5.html#v5-update-rum-agent)

With a tooltip explaining:

`RUM agent is up to date`
`vX.Y available`

Upgrade URL: https://www.elastic.co/guide/en/apm/agent/rum-js/master/upgrade-to-v5.html#v5-update-rum-agent.

We also talked about linking to the release notes, but I'm not sure if we need that (example: https://www.elastic.co/guide/en/apm/agent/rum-js/master/release-notes-5.x.html)

**Comment by drewpost** [comment]
The copy change was an attempt to make it consistent with the messaging that users see in their Elastic Cloud deployments.
