### ISSUE TITLE
[Design] Ingest Management MVP

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#236]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)

This is the design issue corresponding to https://github.com/elastic/uptime/issues/235

The main issue here is that users would like to be able to configure (CRUD) monitors via the Kibana GUI instead of YAML.

**Rough Design Outline**

Our initial discussion here has been around:

1. UI to be built primarily in Uptime with simple or no UI in IM. Will cross-link from IM to Uptime's richer UI.
1. Only supporting HTTP monitors for parity with the IM UI (which can only show one type for now, due to technical constraints. HTTP is the most popular).
1. Making the 'add data' button link to a simple form for creating a new monitor with `Name`, `Schedule`, and `URL`, `Tags (combo box) `as basic options with some expandable advanced area. Tags don't have to be in MVP.
1. Adding an `edit` button for individual monitors that will also trigger the same form.
1. As a stretch goal we can add additional advanced options, probably hidden by default
1. Will be a flyout

**User stories**

As an Uptime user I'd like to be able to create, edit, update, and delete monitors if I have 'all' access to the app (Read access users would not be able to). 

**List known (technical) restrictions and requirements**

This has to work with the ingest manager. Each monitor config would be analogous to the Ingest manager's 'policy' objects, which are created in the Security UI. There's a back and forth between ingest management and Uptime in this case due to how Ingest management works.

Ideally we'd support all of the [Heartbeat monitor options](https://www.elastic.co/guide/en/beats/heartbeat/current/configuration-heartbeat-options.html) at some point. There's quite a few (especially for HTTP monitors). We'll probably have to segment options between basic and advanced.

The only mandatory fields are:

* `Name`: human readable name for the monitor
* `Schedule`: how often the monitor runs, e.g. every minute, day etc. (Note: Heartbeat supports a cron style syntax as well, but for our MVP I think it's much easier to just support common intervals of seconds, minutes and hours).
* `Host/URL`: Host for TCP and ICMP, URL for HTTP, e.g. `http://www.elastic.co`

There are heaps other options in the docs too of course.

**Comment by hbharding** [comment]
I think this relates to https://github.com/elastic/kibana/issues/72546 (cc @mostlyjason)

**Comment by katrin-freihofner** [comment]
[Video that shows the current state](https://www.loom.com/share/354a63b72b1f4967bcfbce5c5245f81d)

Open questions:
1.  Do we need an entry point from the monitor overview page?
1. Who is going to provide the content for the integration page? 
1. Do we need anything additional on the configuration side? 
1. Should the add data button in Uptime go to IM -> add monitor view?
And if not, where does a user land once they have added a new monitor?

**Comment by andrewvc** [comment]
@katrin-freihofner looks great!

1. Yes, I think an entry point from the monitor overview page would be great. I think we discussed using the current 'add data' button, which should go away.
2. @drewpost would you be able to provide the text content for the integrations page?
3. I'd like us to add as many advanced options as possible this release after we get the basics. I think we can experiment there and work iteratively
4. I think I expressed this as a requirement before, but after further conversations with @ruflin and team it's no longer required. From Uptime we shouldn't have to crosslink to IM for any reason. IMHO the flyout as the only experience here works for the time being, but I'm open to new ideas.
5. I agree that adding edit monitor to the expanding drawer in overview makes sense.

**Comment by mostlyjason** [comment]
@katrin-freihofner thanks again for working on this overall the design looks great!

1. How do you add a new monitor? It seems like an add monitor button would be good to add? It might be good to think about consistency between apps here as well. Does it make sense for all apps to have an add data button in the same place so its easy to find?
2. Thanks Drew!
3. @andrewvc Can you remind me what you decided about multi-region support? It might be better to start with a single region for 7.10 and add more in 7.11+. I didn't see it in the design so I just wanted to confirm.
4. @andrewvc I think I might have missed that conversation? My concern is consistency between apps. If Uptime made a special flyout just for uptime, and every other product did the same we'd end up with a half dozen special flyouts. It'd be nice from a UX perspective if we could create a common component that worked across all products. I suggested to Katrin that in 7.10 we link to IM and use this cycle to align on design, then implement the flyout in 7.11. The design issue is here https://github.com/elastic/kibana/issues/72546 We have to implement the IM part anyway so I think the flyout would be an enhancement. What do you think?
5. I like the idea of having the ability to edit monitors in an expanding section. @katrin-freihofner why did you call it integrations instead of "edit monitor"?
6. I'd suggest renaming HTTP monitor to something else. The naming sounds too close to metricbeat's HTTP monitoring https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-http.html and filebeat as well https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-http_endpoint.html

**Comment by katrin-freihofner** [comment]
> 1. How do you add a new monitor? It seems like an add monitor button would be good to add? It might be good to think about consistency between apps here as well. Does it make sense for all apps to have an add data button in the same place so its easy to find?

Sorry, I did not communicate that clearly. There is a button that on the overview page to add monitors. The question here was more about, do we want to have an edit/delete button in the list of monitors on the overview page. 

> 4. @andrewvc I think I might have missed that conversation? My concern is consistency between apps. If Uptime made a special flyout just for uptime, and every other product did the same we'd end up with a half dozen special flyouts. It'd be nice from a UX perspective if we could create a common component that worked across all products. I suggested to Katrin that in 7.10 we link to IM and use this cycle to align on design, then implement the flyout in 7.11. The design issue is here [elastic/kibana#72546](https://github.com/elastic/kibana/issues/72546) We have to implement the IM part anyway so I think the flyout would be an enhancement. What do you think?

I started working on that for Logs and Uptime and will update you soon.

> 5. I like the idea of having the ability to edit monitors in an expanding section. @katrin-freihofner why did you call it integrations instead of "edit monitor"?

The context menu there is still the old version of our actions menu. I think both, edit and delete could fit in there. 

This is the issue related to the menu update: https://github.com/elastic/uptime/issues/128

Thank you all for your feedback and help with this!

**Comment by andrewvc** [comment]
@katrin-freihofner @mostlyjason @ruflin @drewpost one thing we missed here, that I discussed with @mostlyjason is a 'policy' selector (policies are what are called 'configurations' in IM today, but that will change soon) and a link to the add policy button. This is already part of the IM UI, SS below

![image](https://user-images.githubusercontent.com/131427/90279498-ecbea380-de2e-11ea-809b-acebba76a3a9.png)

This is something that's a bit irritating, since we expect most users to just use the same policy for all monitors, and on cloud we'll be able to automatically detect the right policy most of the time. Most users have 1-3 heartbeats that will all be on one policy. We can help them out by automatically picking the policy with the most heartbeats on it by default.

One other thing we need to think about is a state for insufficient privileges. Only super-users can edit IM stuff, so all these features need to handle that. I'm thinking we can either gray or hide any buttons that require a super-user, and use a tooltip to communicate that.

**Comment by andrewvc** [comment]
@mostlyjason and I resolved most of the questions he mentioned in a zoom, we're fine on the flyout, multi-region support is coming post 7.10

**Comment by andrewvc** [comment]
Added ` UI to be built primarily in Uptime with simple or no UI in IM. Will cross-link from IM to Uptime's richer UI.` to ACs after discussion with @alvarolobato . 

Let's figure out if we want no UI or little UI. I know @katrin-freihofner prefers a minimal IM UI. I'm worried about two UIs where one is clearly better. IMHO link to Uptime would be better. Thoughts?

**Comment by ruflin** [comment]
@andrewvc I assume this means the same experience as we have today with Endpoint in 7.9?

**Comment by andrewvc** [comment]
Yes. I think we need more feedback here from @drewpost and @katrin-freihofner

**Comment by katrin-freihofner** [comment]
Quick video walk-through of what we are thinking of as the user flow:
https://www.loom.com/share/de2b2d39514d472c986b10b7eae5c74e

**Comment by andrewvc** [comment]
@katrin-freihofner love the new walk-through, two questions:

1. Is there a reason there's a new place to get the list of centrally managed monitors in Uptime? Why not use the overview page list?
2. Is there a delete button in there I missed?

**Comment by katrin-freihofner** [comment]
For now, we don't need any bulk actions and that is why we will not need the list of monitors in the settings.
We are going to have edit and delete actions on the overview page. Each line in the monitor list will have an edit/delete monitor action in the expanded view. The edit navigates to the settings page of the monitor, the delete triggers the confirmation popover.
