### ISSUE TITLE
Move RUM tab to sidebar

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#240]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)

We want to move the RUM tab to its own app in the sidebar. This should just entail adding the sidebar link to the RUM page and not much else.

The breadcrumbs will change to "End User Experience" or whatever the sidebar tab is named (@katrin-freihofner do you remember what this was to be called?)

**Comment by katrin-freihofner** [comment]
I think @drewpost can help us here.
