### ISSUE TITLE
Default time range filter should respect the default time filter defined in Kibana Advanced Settings

### ISSUE THREAD

**Issue by hendry-lim** [elastic/uptime#241]
**Describe the bug**
As the title above. APM had the same issue, but it was fixed in [#71464](https://github.com/elastic/kibana/pull/71464).

**To Reproduce**
1. Configure default time filter in Kibana Advanced Settings to 1h
2. Navigate to Uptime
3. The time range filter shows 15 minutes.

**Expected behavior**
The default time range filter in Uptime should has the same value as the default time filter defined in Kibana Advanced Settings.

<details>
<summary>Expand</summary>

![image](https://user-images.githubusercontent.com/48344515/88190700-2a377300-cc6d-11ea-8458-bc1e580352ea.png)

![image](https://user-images.githubusercontent.com/48344515/88190705-2d326380-cc6d-11ea-9016-478baadaafe2.png)

</details>

**Comment by shahzad31** [comment]
Closing since this is done via https://github.com/elastic/kibana/pull/79418
