### ISSUE TITLE
Incident support in uptime

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#245]
**Is your feature request related to a problem? Please describe.**

Today when a site becomes unreachable or otherwise fails a check in Uptime a user gets multiple failed pings. This creates an information overload since a user must read each one to see if they're related, or simply assume that they are.

**Describe the solution you'd like**

We should create discrete incidents with unique IDs tying related failures together. A good first start would be combining identical errors from a given monitor in a single location into one row. @katrin-freihofner created this mockup a while back (see bottom of issue) that would be a great start. We could place it above the ping histogram. One modification we'd need to make is to make a location selector. Combining errors across locations is possible, but complex and could be in a follow-up.

TODOs:

- [ ] Have heartbeat generate a unique `monitor.state_block_id` UUID value every time the monitor's state or error type changes. This will let us track when errors change.
- [ ] Build Kibana UI following below SS (but broken out by geographic location). 

![image](https://user-images.githubusercontent.com/131427/89244574-75864580-d5cc-11ea-9ba4-41b6ffeb85d5.png)

**Comment by tbragin** [comment]
I love the idea of exploring heuristics for grouping uptime alerts into incidents. While I see it as a larger goal in observability to group alerts into incidents across data types, I like the idea of starting small in a well-scoped domain of uptime monitoring to investigate this. I'm curious whether the framework for doing so as well as the UX for exposing incidents can eventually be applied to other parts of observability.

**Comment by andrewvc** [comment]
@tbragin I agree uptime's an ideal initial use case. I assume the lessons we learn UI wise will be quite portable.

There's probably a larger story here for a unified incident concept across observability, but I don't think we should try to go there yet. This initial take will be very reliant on existing heartbeat datastructures, so no generic API or data-model across apps.

That said, we could get there in the future.
