### ISSUE TITLE
Replace search bar with Kuery bar

### ISSUE THREAD

**Issue by dov0211** [elastic/uptime#25]
We would like to replace the search bar we have today in Uptime, with a Kuery bar

**Comment by katrin-freihofner** [comment]
@justinkambic @andrewvc thanks for sharing. I thought we are going to remove the ID filter dropdown? But anyhow I would set a max-width (~144px/button) for the Up/Down toggle buttons to make sure they look clickable.

**Comment by andrewvc** [comment]
PR here: https://github.com/elastic/kibana/pull/43621
