### ISSUE TITLE
Change Client Side Monitoring Branding to User Experience

### ISSUE THREAD

**Issue by drewpost** [elastic/uptime#253]
Update all references to Client Side Monitoring to User Experience in 7.10 dashboard 

H1 title
Kibana Nav
URL

Anywhere else?

**Comment by formgeist** [comment]
We need to update the promo callout in APM app for RUM services

**Comment by formgeist** [comment]
I've opened https://github.com/elastic/kibana/issues/78207 to handle the updated copy of the callout in APM app.
