### ISSUE TITLE
Add `type` to monitors details page for new `browser` type

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#254]
On the monitor details page we don't show the monitor type (see current SS below). This hasn't been a problem so far because the URL scheme effectively is the type. With real browsers though it's ambiguous since the URL will be HTTP. CC @drewpost @katrin-freihofner . I propose we add a new type field just below URL containing `icmp|tcp|http|browser`. 

![image](https://user-images.githubusercontent.com/131427/94561921-4980ec80-022a-11eb-86bf-0744ef626ad0.png)

**Comment by shahzad31** [comment]
instead of adding a new row, i propose we use an EuiBadge to display HTTP/BROWSER or ICMP in front of url value or maybe in the title.  It can also be before "Up in 3 Location" text
