### ISSUE TITLE
Callout the new experimental Synthetics feature in Uptime UI

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#255]
**Is your feature request related to a problem? Please describe.**
We will be making Synthetics available as an experimental feature at the same time we release 7.10.

To increase awareness and early adoption, we would like to call this out in the Uptime UI, where users can go to find out more information.

**Describe the solution you'd like**
Add a callout to the Uptime UI that advertises Synthetics is available as an experimental feature.

It is expected that this will use existing Kibana capabilities for adding a banner (or some other UI) notice. It must be possible for the user to find out more details about what Synthetics is (such as a click through).

**Additional context**
* The copy of what to display is to be confirmed (cc @drewpost)
* The URL to link through to, is to be confirmed (this is being looked at separately), for context:
  * This will be a publicly available URL
  * The docs will include information about what the limitations of being experimental

**Comment by justinkambic** [comment]
Does this need an accompanying docs page? AFAIK we don't have an existing public URL detailing how to use synthetics.

I will create a PR that adds the callout with some placeholder copy, but we'll want to isolate what this URL will be as soon as we can.
