### ISSUE TITLE
Uptime and User Experience to be available in Navigational Search

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#256]
**Is your feature request related to a problem? Please describe.**
Navigational Search is going to be deployed in the Kibana UI, so we want to ensure that the *Uptime* and *User Experience* apps are identified when searching for associated text.

**Describe the solution you'd like**
The *Uptime* and *User Experience* apps should be identified when searching for specific keywords. The keywords are to be determined as part of this, but for example, searching for `synthetic` may provide a search result for the `Uptime` app.

**Additional context**
There is a [Kibana issue](https://github.com/elastic/kibana/issues/78174) that describes the wider issue where Observability apps are not being identified in searches.

This issue is to address this specifically for the *Uptime* and *User Experience* apps:

Main app links
- [ ] Identify which keywords should match which apps
- [ ] Apply to Uptime
- [ ] Apply to User Experience

Deep links (as referenced in https://github.com/elastic/kibana/issues/86165)
- [ ] Identify which keywords should match to which deep links
- [ ] Apply to Uptime

**Comment by paulb-elastic** [comment]
@drewpost can you help define the search terms for each of the apps please?

**Comment by drewpost** [comment]
**Uptime**: Synthetic(s), ping(s), check(s), availability, response duration, response time, outside in, reachability, reachable, digital, performance, web performance, web perf
**User Experience**: RUM, Real User Monitoring, DEM, Digital Experience Monitoring, EUM, End User Monitoring, UX, Javascript, APM, Mobile, digital, performance, web performance, web perf

cc @PaulB-Elastic @andrewvc

**Comment by alexfrancoeur** [comment]
Linking out to the broader initiative of registering search aliases for registered applications and features https://github.com/elastic/kibana/issues/76778

**Comment by paulb-elastic** [comment]
Added reference to https://github.com/elastic/kibana/issues/86165, to also add deep links to the navigational search

**Comment by alexfrancoeur** [comment]
Spreading the news that aliases are now supported with https://github.com/elastic/kibana/issues/76778

**Comment by paulb-elastic** [comment]
@drewpost, https://github.com/elastic/kibana/issues/86165 mentions about adding deep links as well, to go directly to **Overview** and **Settings**.

By definition, all of the search terms you’ve listed above (for Uptime) will go to the **Overview** page anyway (as this is the landing page for Uptime).

However, do you have a view on what terms should result in **Settings**?

For example, should searching for `uptime` show a search result for `Uptime` (which would go to **Overview**), but also show a result for `Uptime Settings` which takes the user to the **Settings** page?

Are there any other terms to add that show a deep link result to the **Settings** page?

**Comment by drewpost** [comment]
@paulb-elastic That's a decent point. TBH, that's about the only example I can think of that would go somewhere else. Unless we get really clever ie identifying monitor names and dynamically adding them to the searchable index so I could search for "Checkout Flow" and it shows Uptime there and. deep links into the monitor

**Comment by shahzad31** [comment]
Another cool nav point would be if user searches for "Down monitors" we can land them to overview page by filtering to down monitors, same can be true for "Down websites" for browser checks.

**Comment by shahzad31** [comment]
I believe we can also add for other filters if needs be 

"TCP Pings", "ICMP Pings" "HTTP Pings" etc

**Comment by shahzad31** [comment]
@drewpost to have a more dynamic search provider, where you can even search using, monitor names, url et, one can register search provider in the app 

https://github.com/elastic/kibana/tree/master/x-pack/plugins/global_search#registering-custom-result-providers

that you can power using your own custom search api.
