### ISSUE TITLE
Disable APM integration button if no data is available for the displayed monitor

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#26]
It's likely that in some, or even the majority, of cases our users won't have an APM service configured for a given monitor. In this case it would be best to reflect this in the **Uptime > APM** integration, as noted in [this comment](https://github.com/elastic/kibana/pull/34892#issuecomment-484974486).

At the time of this writing, the integrations are in the early stages of development and this functionality is probably too complex to introduce. As we move forward and invest more in the cross-solution integrations, it would be useful to our users via our UIs.

Additional input on how we should address this is welcome.

**Comment by dov0211** [comment]
In case we are greying out the link integrations we need to provide the user with the explanation on why it is greyed out (probably using a tooltip)

**Comment by justinkambic** [comment]
> In case we are greying out the link integrations we need to provide the user with the explanation on why it is greyed out (probably using a tooltip)

++ we would give them some explanation. "There is no APM data for this monitor yet" or something along those lines. It may be a fairly complicated feature because as we've discussed elsewhere, it's possible that they _are_ monitoring a service in APM that Uptime can't identify using the methods it has available today.

**Comment by andrewvc** [comment]
This was shipped
