### ISSUE TITLE
Monitor simple alert spinner doesn't go away after error

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#267]
**Describe the bug**
When I attempt to configure an alert without SSL enabled, I encounter an error. This is the correct behavior, but after the toast goes away, there's still a loading spinner in the UI.

**To Reproduce**
1. Run the Elastic stack with heartbeat data
2. Configure an action connector via the _Settings_ page
3. Click the switch to enable an alert
5. After the toast goes away, a loading spinner remains

**Expected behavior**
We'd hide this spinner after the error finishes displaying, or create some new UI state indicating the error.

**Screenshot**

![image](https://user-images.githubusercontent.com/18429259/96462713-e1537400-11f3-11eb-8883-e5959e318f4f.png)

**Comment by paulb-elastic** [comment]
This has been fixed in https://github.com/elastic/kibana/pull/91453
