### ISSUE TITLE
[Design] Show browser logs for failed journeys/steps

### ISSUE THREAD

**Issue by hmdhk** [elastic/uptime#268]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)
[Showing browser logs](https://github.com/elastic/synthetics/issues/82) helps users investigate failed journeys.

**User stories**
As a user who is investigating a journey failure, it's helpful to know what browser logs exist before the failure. 
The browser logs are captured in the agent with [this PR](https://github.com/elastic/synthetics/pull/94) and they include `text` and `type` fields.

**List known (technical) restrictions and requirements**
The number of browser logs should be limited to a reasonable number of most recent logs with the ability to expand further to see older ones. 

Note: The browser logs are only captured for failed journeys.

cc @katrin-freihofner  @drewpost @paulb-elastic @andrewvc

**Comment by drewpost** [comment]
I think this is a serious usability improvement. I'd be a big fan of prioritising this.

**Comment by katrin-freihofner** [comment]
I think this is solved by https://github.com/elastic/kibana/issues/80156

**Comment by hmdhk** [comment]
@katrin-freihofner, just to clarify, this issue is for browser logs (which potentially should be displayed for failed steps), are you implying that we will use the same design for agent logs for browser logs as well?

**Comment by katrin-freihofner** [comment]
@jahtalab would you mind adding an example for both just to make sure I understand the issue at hand?

**Comment by paulb-elastic** [comment]
Don't we have them both in the current design, or is there another set of logs?
![image](https://user-images.githubusercontent.com/70908889/98007070-dd764300-1dea-11eb-97b8-3b451def9aa9.png)
