### ISSUE TITLE
Show tag values for monitors

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#269]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)

It is possible today to tag monitors in Uptime, and to search by these tags. We have a tags drop down in the filter bar already. However, we do not provide any way to see:

1. Which tags a monitor currently has
2. To navigate to similar monitors easily based on tags

I would categorize these as fairly obvious features and low hanging fruit to boot. Additionally it's strange to be able to search by something but then not see it reinforced in the results. This issue proposes adding a simple tag list widget to both the overview page (in the expandable row) and to the monitor details page (below the monitor type on the top left of the page). This could be a simple inline list of [EUI Badge](https://elastic.github.io/eui/#/display/badge) elements, with each linking to the overview page search for that particular tag.

**User stories**

Tony Tagger has a few dozen monitors categorized in a variety of ways, by role (production, staging) department (finance, sales, IT), and data center (us-west, us-east). While diagnosing an issue with increased latency on a server he wondered if it was affecting all the servers in the same data center. By clicking on the `dc:us-east` tag he was taken to the overview page where he was able to see that all the servers with that tag had increased latency. By removing that filter and clicking on the `dc:us-west` tag he was able to see that the west coast servers were fine.

The next day, Tony was troubleshooting a different issue with a different service having poor performance. He wanted to inform the head of the relevant department that he was going to be looking into it proactively. By examining the associated tags he determined that this service was used by the finance department, and was able to contact the appropriate person.

**List known (technical) restrictions and requirements**
It would be rare to see more than 5-10 tags for a given monitor, with 0-3 being most common.

**Comment by katrin-freihofner** [comment]
> This could be a simple inline list of [EUI Badge](https://elastic.github.io/eui/#/display/badge) elements, with each linking to the overview page search for that particular tag.

Do you mean clicking on the badge filters down the overview page?

> It would be rare to see more than 5-10 tags for a given monitor, with 0-3 being most common.

I guess we could show the first 3 (or dependent on the no. of characters even less) and have a `4 tags badge`. We have something like that in APM:
<img width="394" alt="Screenshot 2020-10-21 at 10 44 43" src="https://user-images.githubusercontent.com/20965076/96695889-74bead80-138a-11eb-99de-93f0d810daf6.png">

...but in a persistent popover so the badges can be clicked.

**Comment by tbragin** [comment]
@katrin-freihofner it's worth mentioning that Kibana is rolling out saved object tagging. Not sure if there are any concepts or elements we can reuse there. https://github.com/elastic/kibana/pull/79096

**Comment by andrewvc** [comment]
@katrin-freihofner I'm thinking these tags are more like tags here on github issues. Ideally they wouldn't require a popover to view, I think you'd want to have them at your fingertips.

@tbragin these are tags defined in the heartbeat.yml, and later in fleet UI, so the saved objects don't apply (yet), but they may in the future, so thanks for the heads up!

**Comment by katrin-freihofner** [comment]
@andrewvc 
1. This is user-defined content. Which means we need to find a solution that can handle 10+ tags in the UI. I think my proposal is more scalable than listing all the tags from the heartbeat.yml in the UI.

2. Does this mean, with saved objects we have two tagging solutions side-by-side?

**Comment by tbragin** [comment]
My point about saved objects tagging in Kibana was one of more visual consistency, and perhaps re-user of EUI components to help us, if applicable. I understand that our tags come from user-defined values in the Heartbeat shipper.

**Comment by katrin-freihofner** [comment]
> My point about saved objects tagging in Kibana was one of more visual consistency, and perhaps re-user of EUI components to help us, if applicable. I understand that our tags come from user-defined values in the Heartbeat shipper.

Yes, definitely. Thanks for pointing me in that direction. I think it could be very confusing to have two types of tags in the UI.

**Comment by shahzad31** [comment]
@katrin-freihofner that saved objects UI i think it displayed tags in expanded list, i think we can strike a balance here, instead of show an abstraction like environments above, may be we can show 2-5 tags in expanded state and if there are more show those in popover like above,
