### ISSUE TITLE
Proposal to align Uptime UI and UX UI filters

### ISSUE THREAD

**Issue by shahzad31** [elastic/uptime#270]
**Is your feature request related to a problem? Please describe.**

In UX app we have filters like browser, os, location and in uptime UI filters are like tags, scheme, ports,

both works the same, they filters the data and apply to all the content below, both displays top 10 terms and only search offline on those 10 values.

but they look totally different, in UX app, they are displayed in left, in uptime we are displaying them on top 

i propose that we align to use the same design for those, either adapt uptime style filters in UX app, or adapt UX type filters in uptime app.

UX View
![image](https://user-images.githubusercontent.com/3505601/97851924-53e54900-1cf6-11eb-972a-2178c9bc4425.png)

Uptime View

![image](https://user-images.githubusercontent.com/3505601/97851959-61023800-1cf6-11eb-99ba-63844d79fb5d.png)

cc @katrin-freihofner @formgeist @paulb-elastic @drewpost

**Comment by formgeist** [comment]
@shahzad31 Just FYI, we're making this a design team priority to research and further propose a consistent and updated filtering experience across our Observability apps - you can follow along in https://github.com/elastic/observability-dev/issues/1244

**Comment by shahzad31** [comment]
this is more or less done in https://github.com/elastic/kibana/pull/101459
