### ISSUE TITLE
Add Include & Exclude Option to User Experience Filters

### ISSUE THREAD

**Issue by drewpost** [elastic/uptime#273]
As a user of UX
I want to be able to be able to use the filters to both include and exclude items (currently can only use include)
So that I can analyse my data manually without needing to spend a lot of time checking/unchecking a ton of options
And so that I can remove unwanted cohorts from the analysis

Typical scenario: I want to exclude all headlesscrhome traffic from User Experience as it's often synthetics users and can bias the data away from real users' experiences

**Comment by formgeist** [comment]
We probably need some UX design on how the exclude / include interactions will work within the select popovers. I'm putting this on the project board for 7.12 design. cc @paulb-elastic

**Comment by paulb-elastic** [comment]
This now won’t be done as an individual change in User Experience, in favour of a wider Observability filtering initiative.

**Comment by shahzad31** [comment]
This is already done in 7.14 in this PR https://github.com/elastic/kibana/pull/101459
