### ISSUE TITLE
[Uptime] Simplify kuery bar to use simple keyword search instead of field specific kql

### ISSUE THREAD

**Issue by shahzad31** [elastic/uptime#274]
**Is your feature request related to a problem? Please describe.**
Uptime kuery bar use kql to search for monitors, although this is very powerful, it allows configurable syntax, but it has overhead for normal users, it's useful for advance users, but you need to have know-how of how elastic search, kql and heartbeat index works.

![image](https://user-images.githubusercontent.com/3505601/99530461-99b23a80-29a1-11eb-8c8b-a7cdd5e27886.png)

**Describe the solution you'd like**

I would like to have two configurable options in kuery bar, where user can configure it either to use KQL or simple wildcard search against few useful fields like monitorId, monitorName, url etc just like how the search works in certificate page.

user will just type in and it automatically filters results against those fields. there is precedent for configurable synatx in kibana discover app etc , where user can configure between lucene and kql syntax, but in uptime context, we will allow user to configure between normal search and kql syntax search

![image](https://user-images.githubusercontent.com/3505601/99530682-ebf35b80-29a1-11eb-9e9a-6de9d422fea5.png)

**Describe alternatives you've considered**
Using kql to search against specific fields.

**Comment by shahzad31** [comment]
Users have left feedback to simplify apm kuery bar as well, so i feel like if we can implement this, we will provide lot's of value to our users.

**Comment by katrin-freihofner** [comment]
I think that sounds good. If we decide on this, we should make sure this is an Observability-wide effort.

**Comment by paulb-elastic** [comment]
Agreed, I would think it makes sense for this to be consistent across Observability

**Comment by tbragin** [comment]
+1 on consistency across observability.

**Comment by shahzad31** [comment]
i have opened an issue in observability repo to get more feedback on this https://github.com/elastic/observability-dev/issues/1220

**Comment by justinkambic** [comment]
Both search features seem to be working:

Simple search:
![image](https://user-images.githubusercontent.com/18429259/116898826-d945a980-ac04-11eb-975b-2889a63c90e0.png)


`KB`:
![image](https://user-images.githubusercontent.com/18429259/116898746-c29f5280-ac04-11eb-8286-fd11e4ab6a63.png)
