### ISSUE TITLE
Elastic Agent and Synthetic (Real Browser) Integration

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#276]
This builds upon the initial [Phase 1 implementation](https://github.com/elastic/uptime/issues/235).

As an Elastic user
I want to be able to add an real browser Synthetic monitor to an Elastic Agent via an integration
So that I can centrally deploy the monitor without having to install and configure a separate Synthetic or Heartbeat Agent binary and YML file

ACs:
* User can add a Synthetic (real browser) Integration (in the same way they can other integrations)
* User can add a monitor, with the configuration of:
  * Name, frequency and other base fields
  * Monitor Script - which can be defined in **one** of two ways:
    * Inline (the actual script, as is currently put into the `heartbeat.yml` file)
    * Suite ZIP location (as implemented in https://github.com/elastic/uptime/issues/271)
      * Which requires manadatory location, optional folder, optional username/password
* User can define which Elastic Agent, the integration will run on (via the integration policy -> agent policy -> agent assignment)
* The real browser Synthetic monitor will run at the given frequency, and results will appear in Uptime
* The Synthetic monitor will operate via the Docker implementation (note that [this](https://github.com/elastic/synthetics/pull/159) adds an environment variable to ensure Heartbeat will only run Synthetics from Docker)

Consider the AC referenced [below](https://github.com/elastic/uptime/issues/276#issuecomment-867208364)

**Comment by andrewvc** [comment]
@drewpost @paulb-elastic @dominiqueclarke I'd like to expand the last AC around the experience setting up the docker image. We should do the following IMHO:

1. Attempt to detect if the agent policy is backed by `offline` agents (e.g. ones capable of running synthetics)
2. Show an error if that is the case *before* the policy is saved clearly explaining the situation
3. Create a tutorial in correctly setting up synthetics with fleet and link to it in the UI. (It should be part of https://www.elastic.co/guide/en/observability/master/synthetics-quickstart.html)

**Comment by paulb-elastic** [comment]
I do like the idea of this - giving a more useful pointer of a misconfiguration before it’s set up (at which point the user is left debugging why they have no data).

I guess the only thing would be if there is a use case where a user might want to set up a load of monitors before assigning the policy to an agent, in which case this would prevent that.  I’m not convinced that is a valid use case, just asking the question (/cc @drewpost)

**Comment by paulb-elastic** [comment]
Linking to https://github.com/elastic/beats/issues/26398 which is the requirement for an Elastic Agent + Synthetics dependencies image

**Comment by dominiqueclarke** [comment]
This has been resolved.
