### ISSUE TITLE
Simplify status by location Display 

### ISSUE THREAD

**Issue by shahzad31** [elastic/uptime#277]
**Is your feature request related to a problem? Please describe.**
Right now in uptime, we display status by location saying, Up in 1/1 location or Down in 2/3 Locations

![image](https://user-images.githubusercontent.com/3505601/101378993-0ab78480-38b4-11eb-80ca-ff4765fd00b0.png)

This information is displayed in Monitor list as well as in details page.

**Describe the solution you'd like**
This works well for multiple locations, but when we have only one location, we should instead just display name of location, saying `Up in Ny-Heartbeat`, or `Down in Us-East` .

**Comment by shahzad31** [comment]
@drewpost @katrin-freihofner any inputs?

**Comment by katrin-freihofner** [comment]
Sounds like an improvement to me, let's do it.
