### ISSUE TITLE
[Bug] Waterfall chart not working with large number of requests

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#284]
When viewing the waterfall chart for a page has a large number of network requests (it varies, but above 500), not all of the data is not shown.

On a page that should include 1000 network requests where I have increased the timeout to ensure all resources load (I’m not getting a page load timeout error), it typically only shows up to about 500 requests.

I don’t know if it’s relevant, but there is a strange grey box ‘artefact’ on the chart as well, near where the data stops being shown.

![image](https://user-images.githubusercontent.com/70908889/104438874-67c7e980-5588-11eb-9928-9e2469077718.png)

In addition to not showing the bars, there also seems to be a har limit of 1000.  This page should include 3000 requests, but the list of URLs stops at 1000:

![image](https://user-images.githubusercontent.com/70908889/104439069-9d6cd280-5588-11eb-991e-541155476a62.png)

**Comment by drewpost** [comment]
In Chrome 87.0.4280.141 on macOS it stops at 261 

<img width="2234" alt="image" src="https://user-images.githubusercontent.com/7509768/104441345-71068580-558b-11eb-9a0a-3ded5d22c4c4.png">

In Safari 14.0.3 on macOS it will render all lines but it does spike system resources and sometimes will have strange periods where you scroll down and nothing renders for a while

https://user-images.githubusercontent.com/7509768/104441705-ef632780-558b-11eb-8d40-b2b7037f0a98.mov
