### ISSUE TITLE
[Bug] Test Results page caching screenshots

### ISSUE THREAD

**Issue by drewpost** [elastic/uptime#285]
**Describe the bug**
The test results page for each monitor appears to be caching the screenshots for the last viewed monitor

**To Reproduce**
1 - open a real browser monitor and let the screenshots load
2 - go back to Uptime overview 
3 - select a different monitor

You'll see the previous monitors' images remain there for some time, then go to a no image available state and then load the correct images

**Expected behavior**
The screenshots would either load directly with the correct ones for the monitor or show a loading icon

https://user-images.githubusercontent.com/7509768/104440981-f6d60100-558a-11eb-9b5d-6eb91526df1f.mov

**Comment by paulb-elastic** [comment]
Just to add to this, it doesn’t only appear to be the screenshot, but the whole table that’s cached (i.e. the other columns in the history table as well).

This also seems to be the case in 7.10, however it may just appear more obvious now that the screenshot thumbnails will be shown in 7.11.

**Comment by dominiqueclarke** [comment]
@drewpost @paulb-elastic Here is the video of the fix. Please note on loading, I changed the content to say "Loading ping history" (it's somewhat cut off by my awesome screenshot extension but you can see some of the content in the video). After loading, it'll say "No pings found". Do you have any feedback on the content? https://drive.google.com/file/d/1Zm__8vbPjo1TZ30IRMLXIxzFdWsgqFPQ/view

**Comment by drewpost** [comment]
1 - I love that this the screenshot app is actually called "awesome screenshot extension" and that wasn't you being sarcastic.

2 - This looks good. I am partial to saying "Loading Test Runs" to be more inclusive of real browser based monitors vs pings

WDYT @paulb-elastic ?

**Comment by paulb-elastic** [comment]
Agreed - I'd prefer to avoid the term ping.

Being picky, do we refer to "Test Runs" as a thing?  If not, then we should probably lowercase it "Loading test runs", or if that suggests something about what we call those entities, then maybe just "Loading history..." as it's on the history table, and the ellipsis make it clear it's not in the final state (and I think we use elsewhere)?

**Comment by dominiqueclarke** [comment]
I am partial to the generic `Loading history...` and `No history found`
