### ISSUE TITLE
Loading messages sometimes do not display sensible copy

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#286]
**Describe the bug**
There are a few cases in the Uptime app where we display loading messages with copy that doesn't reflect the correct situation. Typically the message says something like "No data available," and once data loads the message disappears and the data are rendered on the screen.

The two places we have identified this so far are on the _Certificates_ page and the _Pings list_.

**To Reproduce**
1. Navigate to the Certificates page
2. Look at the loading message
3. See the data load

![Jan-13-2021 14-27-37](https://user-images.githubusercontent.com/18429259/104597105-e84b2080-5642-11eb-9fd5-f9d47307bff6.gif)

**Expected behavior**
We should notify the user that we are checking for data, and only display the message when none is available. Otherwise we should replace the message with the data.

**Comment by shahzad31** [comment]
fixed in https://github.com/elastic/kibana/pull/111526
