### ISSUE TITLE
Uptime monitor status toggle alert should implement recovery action

### ISSUE THREAD

**Issue by shahzad31** [elastic/uptime#289]
**Describe the bug**

We added actions for connectors like Slack PG,Service Now, JIra etc in PR , those connector will create message or ticket in respective platforms, alerting team has implemented recovery action.

While in a normal monitor status alert flyout user can configure recovery action, we should automatically do that as part of toggle simple alert which user can configure easily from monitor list column. 

**To Reproduce**
Configure a simple toggle alert

1. Make sure you have a test monitor up
2. Create an action connector like slack
3. Configure a toggle alert against that monitor
4. Make monitor down, you will receive a down message
5. Make monitor up again
6. There is no recovery message

![image](https://user-images.githubusercontent.com/3505601/105837155-90ab9e00-5fce-11eb-833f-6e9cde825d01.png)

**Comment by justinkambic** [comment]
Tested locally, works well 
![image](https://user-images.githubusercontent.com/18429259/117007650-e4a5dd00-acb7-11eb-9dca-b8f95af566fc.png)
