### ISSUE TITLE
Synthetics Data Stream Naming

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#292]
I'd like to propose the following streams:

    synthetics-tcp-*: TCP monitors
    synthetics-http-*: Lightweight HTTP Monitors
    synthetics-icmp-*: ICMP Monitors
    synthetics-browser-*: Browser based checks
    synthetics-browser.screenshots-*: Screenshots from browser based checks
    synthetics-browser.network-*: Network data from browser based checks
    synthetics-api-*: API journey checks

The rationale here is:

    Given that we're now separating the different protocols into separate packages, I think separating the datasets feels more natural. Plus, the more I think about it, given the light lift, the improved performance from the constant keyword type when filtering by type.
    Partitioning screenshots into a separate index is a common ask from customers who want to set a different ILM policy for screenshot data given its large size, same goes for network data, which may not be as relevant to older runs. Additionally, this could use a more minimal mapping for efficiency.
    We should account for API Journeys, work has not yet started here, but should in the mid-term. We may want to break this into multiples later, but given that we haven't gone in-depth there yet, that can wait.

CC @urso @ruflin @justinkambic @drewpost @mostlyjason @dominiqueclarke

**Comment by justinkambic** [comment]
@andrewvc we ran into some technical limitations when trying to set up the names for the data streams. The stream name follows the pattern `type-packageName-dataSetName-namespace`.

1. **type:** the type of the package specified in the manifest. This is `logs | metrics | synthetics | etc`, in our case, synthetics
1. **name:** the name of the package. In our case, synthetics
1. **dataset name:** the name of the dataset, in our case `http | tcp | icmp | browser | etc`
1. **namespace:** this is chosen by the user at runtime. When creating an integration, it defaults to.. `default`. But the user can configure multiple integrations with the same namespace, i.e. `my-integration-customNamespace1, my-integration-customNamespace2`.

My understanding is the unfortunate side effect of these technical limitations as they exist today is you end up with a datastream named like:

```
synthetics-synthetics.http
synthetics-synthetics.tcp
```

cc @ycombinator @ruflin can speak more in-depth to the underlying cause of this.

**Comment by ycombinator** [comment]
@justinkambic Everything you've said above is correct based on my explorations and our conversations as of yesterday. 

This morning I took a look at the `apm` package (sorry, I should've done this yesterday) and — long story short — have figured out how to get the data stream names to be what @andrewvc suggested in this issue's description. I've pushed up a commit to your branch that will achieve this goal for `synthetics-http-*`: https://github.com/justinkambic/integrations/commit/3ec62949123d8fce8be728cf99a8f1a84296e772. 

Sorry about the noise, folks!

**Comment by ycombinator** [comment]
> `synthetics-browser-*`: Browser based checks
> `synthetics-browser.screenshots-*`: Screenshots from browser based checks
> `synthetics-browser.network-*`: Network data from browser based checks

Implementation note: when defining sub-folders for each of the above data streams under the `data_stream/` folder in the `synthetics` package, I believe the folders will need to be named `browser`, `screenshots`, and `network` respectively. For reference, see https://github.com/elastic/package-storage/tree/production/packages/endpoint/0.17.0/data_stream/process and https://github.com/elastic/package-storage/blob/ca0a990ccf9d6066df8214516b8673ecc62e7dd5/packages/endpoint/0.17.0/data_stream/process/manifest.yml#L3.

**Comment by justinkambic** [comment]
Oh great, thank you for this awesome update, and the additional information about how the package should be structured.

**Comment by andrewvc** [comment]
To confirm, it sounds like we're OK with the original spec then?  If not, let's update the top of this issue to reflect any necessary changes.

**Comment by justinkambic** [comment]
The comments above were news to me vs what we discussed yesterday, so it sounds like we do not need to update the spec.

**Comment by paulb-elastic** [comment]
Closing as we have DS for Synthetics now
