### ISSUE TITLE
SPIKE: Investigate options for a script recorder

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#295]
Before embarking on a script recorder, this spike it to look at options of how we might be able to build this.

The initial requirement is to be able to record a browser flow (e.g. loading a URL, interacting with elements on the page, including keyboard and mouse input to navigate between pages, forms etc.), which generates Synthetic/Playwright code in the format of the `journey` and `step` objects of our implementation.

This should consider a very easy implementation for the user (for example, we know some users cannot run command line npx and the current Playwright codegen facility), so a standalone Chrome extension for example could suffice, where the code is available to be copied out of the recorder and pasted into a monitor script.

Being able to modify the recorded script in the ‘tool’ and replayed would be very useful, and should be considered in the investigation.

A future enhancement might be to be able to build this directly into Fleet, but this wouldn’t be needed in the first instance.

**Comment by andrewvc** [comment]
To summarize our recent meeting on this, next steps would be:

1. Create a browser extension that allows for the creation of a single journey and CRUD operations on the steps
2. Ability to the recorded test
2. Savable IR format that can be reloaded in the extension UI
3. Output JS code based on this

**Comment by andrewvc** [comment]
Closing in favor of https://github.com/elastic/uptime/issues/304 , @vigneshshanmugam has already made great progress on the scope of the original spike.
