### ISSUE TITLE
States Index Meta Issue

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#30]
This issue tracks development of the new heartbeat states index. The proposed implementation would require:

1. Adding an option to the beats elasticsearch option (only for heartbeat or other beats opting in), to write to a secondary index. The two options, one for enable/disable, the other to change the index name, could be named:
    * `output.elasticsearch.enable_alternate_outputs: true`
    * `output.elasticsearch.alternate_outputs.heartbeat_states_index: "heartbeat-states-{version}"`
1. Developing a painless update API script to merge together new heartbeat check data.
1. Modifying existing Kibana APIs where appropriate to use this new API preferentially (not a requirement, but would simplify kibana code).
1. Implement beats tooling to update mapping for this new index such that `make update` would do the right thing in terms of generating a mapping and docs.

There was some concern about how the new ES options would not work with Kafka, Logstash, Redis etc., but for the uptime product there are few legitimate uses for those technologies and only a handful of known implementations in the wild. That may make this less applicable for other beats.

If we can get tentative agreement on this by @roncohen @ruflin @dov0211 and @justinkambic I can turn this into an implementation ticket and move forward from there.

**Comment by justinkambic** [comment]
From an implementation level I don't know how much I have to offer. My technical concerns are all downstream of how the indices are created.
I would say I prefer not to maintain a Kibana API responsible for this sort of work because it would mean Heartbeat would depend on Kibana to provide this feature. Today that's not an issue since its only use is for Kibana, but it adds additional coupling that may be a hinderance in the future.

**Comment by andrewvc** [comment]
+1 to not providing an API here just yet. The index is a pretty dang good API for now.

**Comment by ruflin** [comment]
In general I'm on board with the above suggestion. I think we should discuss where the configs goes and names directly in a PR in more detail.

**Comment by dov0211** [comment]
I would like to raise the concern about users that send their data to ES using Kafka, Redis or LS, in that case, Uptime UI will break

**Comment by tbragin** [comment]
@dov0211 I'm concerned about that as well. 

@andrewvc You also mentioned that the state index would not work with cross-cluster search in another context. Could you elaborate on that here? That concerns me as well, especially because CCS may be one of the deployment paths we'll need to seriously consider in Elastic Cloud in order to get to a multi-region scale.

**Comment by andrewvc** [comment]
@tbragin @dov0211 the more I think about these issues the more I think the original design here is wrong. Luckily, there's a solution.

In an ideal world this would be easy to implement with something like triggers in a traditional DB. We'd intercept writes to the `heartbeat-7.0.0` ILM alias, and send a copy of them to the update script for the state index, and we'd use CCR to mesh together multiple regions. However, ES cannot do that.

We still *really* want to create the state index docs. We should go the kibana background process route. That involves creating a scheduled kibana job that runs *very* frequently (at least once every 5s), that would search the ILM indices for new events, and re-index them into the states index. That solves all the concerns listed here, and even lets us use CCS instead of CCR. It's probably equivalent in terms of work, and ugly in its own way, but will have fewer deployment problems.

**Comment by justinkambic** [comment]
> It's probably equivalent in terms of work, and ugly in its own way, but will have fewer deployment problems.

It's worth explicitly noting that we also sacrifice at least 5s of latency between event creation and rendering in our UI going that route. Also means Kibana needs to send many more requests to ES.

If these constraints aren't viewed as problematic then I don't have further reasons not to go that route. I think the states index is worth creating, especially given the feedback we've gotten from many different places; it seems like something that may be adopted in other domains as well.

**Comment by andrewvc** [comment]
Closing in favor of #49
