### ISSUE TITLE
Support trace based linking with APM

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#302]
Today linking between Uptime and APM is done via either URL or APM `service.name`. The connection would be stronger if we used APM trace headers. Sending those headers would be a simple add to heartbeat and allow for much richer cross-linking between apps. Users would be able to just from a specific failure on heartbeat's side to the trace for that exact transaction

Tasks:
- [ ] Add trace fields to heartbeat HTTP headers and documents. (see https://gist.github.com/graphaelli/ae416585c67f9b50f9f326a50ed26c91) 
- [ ] Ensure the recording bit is set to remove any sampling
- [ ] Enhance outbound links to APM in Uptime to use that same data
- [ ] Feature to pass in header to Synthetics (implemented using `setExtraHTTPHeaders`)
- [ ] Add synthetics functionality https://github.com/elastic/synthetics/issues/245

CC @graphaelli

**Comment by paulb-elastic** [comment]
Captured in https://github.com/elastic/apm-dev/issues/1024, closing
