### ISSUE TITLE
Display the data in the UI based on geo locations.

### ISSUE THREAD

**Issue by dov0211** [elastic/uptime#31]
We should provide the ability to display the data in the Uptime UI based on geo locations.
This will help in case the user has multiple Heartbeat instance sharing the same configuration (HA as an example), in the UI we will present duplicate entries with different UUID. The user still can identify which monitor belongs to the instance using the ID, however, it is not user-friendly. 
By adding location name to the table the user can easily distinguish between the different monitors based on Heartbeat instances 

![image](https://user-images.githubusercontent.com/38371227/57067299-48672b00-6cd7-11e9-96bb-5d9edae124f1.png)

@andrewvc @justinkambic

**Comment by justinkambic** [comment]
What text do you think we should display if there is no location given? We can't give a default location value today, so we should either leave it blank or provide some default text and perhaps link to the documentation for configuring the location field.

Thoughts?

**Comment by dov0211** [comment]
We should add something like "Location not configured" with a link to our doc on how to configure location

**Comment by justinkambic** [comment]
@andrewvc what're your thoughts on this? It seems like an easy win, if we're all agreed.

**Comment by andrewvc** [comment]
+1 on this, and yes, it's an easy win now that the observer data is merged in

**Comment by justinkambic** [comment]
PR: https://github.com/elastic/kibana/pull/36317

**Comment by Cho1409** [comment]
+1 Up
