### ISSUE TITLE
Update Uptime tests to use the new ES Client

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#314]
As per https://github.com/elastic/kibana/issues/83910#issuecomment-805783494, although Uptime has been [updated](https://github.com/elastic/kibana/issues/83910#issuecomment-731153653) to use the new ES Client, there are some outstanding tests to migrate over.

These need to be done by 7.15 FF.

**Comment by paulb-elastic** [comment]
This is being done in https://github.com/elastic/kibana/pull/99801

**Comment by justinkambic** [comment]
Apologies, I didn't realize there was a separate issue. I was reviewing the meta issue from the Kibana team and saw our tests weren't checked off.
