### ISSUE TITLE
Beta link does not open in new tab

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#316]
The new beta link (implemented in https://github.com/elastic/kibana/issues/91421) would be better to open in a new tab, so the user does not lose the context of the Uptime page they are currently in

![image](https://user-images.githubusercontent.com/70908889/115539682-29338080-a295-11eb-8d87-66feb660ad43.png)

**Comment by justinkambic** [comment]
Tested this, works great
![May-03-2021 11-40-53](https://user-images.githubusercontent.com/18429259/116898505-7227f500-ac04-11eb-9f58-2ccd49f9e7d4.gif)
