### ISSUE TITLE
[Exploratory View] Screen re-layout when hovering between Synthetic Monitoring and UX

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#319]
There seems to be an odd re-layout of the screen when moving the mouse between the **Synthetic Monitoring** and **User Experience (RUM)** buttons.  The text (in the centre) and table (at the bottom) shift, and it seems scroll bars appear and disappear.

It’s quite subtle, but is not a nice experience when looking at the screen.

![Video_2021-05-10_112505](https://user-images.githubusercontent.com/70908889/117645640-b5ddaa00-b182-11eb-9369-e099b43a2882.gif)

I see this in Firefox (not Chrome).

**Comment by justinkambic** [comment]
Are you still able to reproduce this? Which version of FF? I'm not seeing it in Chrome, Firefox, or Firefox Dev edition.

**Comment by paulb-elastic** [comment]
Ok, I can see now there is a specifc way of seeing the problem.

Go to **User Experience** and click **Analyze Data**

This will auto select the **User Experience (RUM)** option, which is where the problem shows up (hover, without clicking on any of the selections).

**Comment by justinkambic** [comment]
@paulb-elastic, @dominiqueclarke and I paired on this issue and identified that it is indeed caused by v7 theme in Firefox. At this point we should discuss how much effort is worth investing in fixing this specific issue given that it only impacts Firefox users, and that v7 theme will go away eventually anyway.

**Comment by paulb-elastic** [comment]
@justinkambic / @dominiqueclarke it will affect anyone using Firefox with 7.13 as this is the default theme, unless v8 has been enabled. (Sometimes it happens with **Synthetic Monitoring** selected too, so we should consider it's likely for anyone using Exploratory View with Firefox).

I do personally find it quite jarring - in fact, it almost hurts my eyes as the whole layout shifts - odd to explain, and maybe just me, but that's certainly how it affects me.

**Comment by dominiqueclarke** [comment]
Eui has provided a suggested fix for the v7 buttons and this fix is currently in review.
