### ISSUE TITLE
[Discuss] What icon should we use for our integrations popover

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#32]
Today we're using the `boxesHorizontal` icon. In several places people have [expressed concerns](https://github.com/elastic/kibana/pull/34892#discussion_r279926203) that this is probably not the best icon for us to use. The icon was chosen initially because it's the same one that `EuiBasicTable` employs. The difference is we aren't displaying a set of primary options along with this boxes icon.

We're open to suggestions on the appropriate icon to use. Given that these integrations are being employed across multiple solutions it may be a viable solution to ask for a dedicated integrations icon. That may also be premature.

If we can come to a consensus on which available icon we should use, this issue will be resolved.

**Comment by makwarth** [comment]
++, it'd be great to streamline this now that we have multiple integrations. How about using either of these in the apps:

1) Copy link: `[exportAction icon] Actions [arrowDown icon]`
2) Icon link: `[exportAction icon] [arrowDown icon]`

We originally went with "Actions" over "Integrations" as this menu will evolve to contain other items, like create ML job, set alert, etc.

**Comment by andrewvc** [comment]
This was shipped
