### ISSUE TITLE
[Exploratory View] Add metrics selector to Synthetic data selection path

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#320]
As a user of Heartbeat monitoring the health of my infrastructure
I want to plot specific performance metrics of specific monitors on a graph
So that I can determine if performance is improving or not

ACs:
* When selecting **Synthetic Monitoring** from the **Exploratory View** (Analyze Data), I can define the metric to show (the same as I can when selecting **User Experience (RUM)** data
* The metrics are those available from https://github.com/elastic/synthetics/issues/120 (at some future point, https://github.com/elastic/synthetics/issues/283 will add more)
* This will be available for **Monitor duration** and/or **Ping histogram**

![image](https://user-images.githubusercontent.com/70908889/117661753-ae280080-b196-11eb-9e46-20013713d09f.png)

**Comment by paulb-elastic** [comment]
@drewpost / @liciavale please confirm the menu option for this (e.g. changing Monitor duration to KPI over time)

**Comment by drewpost** [comment]
I am 100% ok with switching to KPI over time as it's more generic and fits the vision of the product. In fact, I'd argue that |pings histogram" goes away and we add in Performance Distribution as an option. Pings become a metric in the KPI over time definition section cc @shadab-elastic @paulb-elastic @liciavale

**Comment by justinkambic** [comment]
This is looking good:

![image](https://user-images.githubusercontent.com/18429259/125958676-d372dedd-7921-48c4-a7ab-939660a31be0.png)

![image](https://user-images.githubusercontent.com/18429259/125958852-9b6bef21-8508-4c56-8995-9e1bdecaa5fb.png)
