### ISSUE TITLE
[Exploratory View] Add Multi Series

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#321]
As someone interesting in using raw data to investigate performance
I want to be able to create multiple series on the same chart with unique data/filter combos
So that I can identify items of interest in the data that wouldn't otherwise be visible

ACs:

- Users can add multiple series to a single chart (at least 5)
- The first series defines the chart type and what can be shown in subsequent series (ie if a distribution is chosen, then all additional series will be distributions)
- The breakdown option is not available in any series other than the primary series
- Each series has a default name that can be changed by a user and is displayed in tooltips and in the legend of the chart
- I can choose from any data type in subsequent series, irrespective of data type chosen in primary series
- I can compare different periods of time
-- In non time-series type charts, the subsequent series can have different durations of time selected
-- In time-series charts, the duration selected in the first series must be matched by all subsequent series
-- The users will have an option to pick from a list of meaningful relative time periods if the first option is a relative time period as well as a custom option that lets a user choose the start date and time OR end date and time and the duration of the series will then match the first series
- Users should be able to build a series and then choose to apply changes to filter/breakdown options. the chart should not automatically render without a user specifically saying they are ready

**Comment by paulb-elastic** [comment]
Linking https://github.com/elastic/kibana/pull/103855
Linking https://github.com/elastic/kibana/issues/106394

**Comment by paulb-elastic** [comment]
Discussed in refinement, closing in favour of https://github.com/elastic/uptime/issues/361

**Comment by justinkambic** [comment]
Not performing testing on this as it's a dupe.
