### ISSUE TITLE
[Exploratory View] Replace existing charts

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#323]
**Uptime**
Donut up/down chart - replace with lens only. No clickthrough
Pings over Time Overview - replace with lens only. No clickthrough
Downtime History - replace with lens only. No clickthrough
Pings over Time (in monitor details) - Stays the same format, replace with exploratory view embeddable and add "explore" button
Monitor Duration (ping) - Stays the same format, replace with exploratory embeddable and add "explore" button
Monitor Duration (real browser) - NEW LOGIC. Sow different chart. TBD on what is shown.

**User Experience**
Core Web Vitals - don't replace with embeddable but DO add click through button to Exploratory View (need to ensure good experience)
Page Load Distribution - Remove "breakdown" dropdown. Stays the same format except the percentile labels pending Lens PR support merging, replace with exploratory embeddable and add "explore" button
Total Page Views over Time - Remove "breakdown" dropdown. Stays the same format, replace with exploratory embeddable and add "explore" button
Browser breakdown -  replace with lens only. No clickthrough
OS breakdown -  replace with lens only. No clickthrough

**Overview Page**
Pings over Time - Replace with pings over time from Uptime lens embeddable to match colouring. Don't add explore button 
Core Web Vitals - don't replace with embeddable but DO add click through button to Exploratory View (need to ensure good experience)

**Comment by paulb-elastic** [comment]
Moving out of 8.0, into 8.1 for the time being.  Need to plan how this fits in with the bigger design work for Uptime.

/cc @drewpost

**Comment by paulb-elastic** [comment]
@drewpost can this be closed now, in favour of the upcoming Synthetics App UI?

**Comment by paulb-elastic** [comment]
Agreed with @drewpost that this can be closed in favour of the upcoming Synthetics App UI.

**Comment by shahzad31** [comment]
@paulb-elastic will that also cover user experience app?

**Comment by paulb-elastic** [comment]
> @paulb-elastic will that also cover user experience app?

Eventually, yes (although that will come after the initial focus on Synthetic (Lightweight + Real browser) monitors)
