### ISSUE TITLE
[Exploratory View] Add mobile APM

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#324]
~Placeholder issue to be defined~

This description added by @justinkambic:
Add a new Data Type to support APM mobile data. It will allow users to explore latency, memory usage, cpu consumption of mobile devices that are logged to APM indices.

**Comment by paulb-elastic** [comment]
This has been done in https://github.com/elastic/kibana/pull/99565

**Comment by justinkambic** [comment]
This is looking good:

![image](https://user-images.githubusercontent.com/18429259/125959596-ba9fc6c3-149f-4917-99d3-526f3cb7615c.png)
