### ISSUE TITLE
[Exploratory View] Move from experimental to GA

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#325]
MVP
- Update and polish the end-to-end user experience in the exploratory view based on the new design like filters etc. (work in progress https://github.com/elastic/observability-dev/issues/1229) 
- Define entry points - When users access the feature from the graphs in other views we need to show the same graphs and keep them consistent 
- Content, CTAs, contextual info need to be checked with UX writing

Stretch 

      1) Multiseries
      2) Date comparison
- A landing page and onboarding - give info about the feature and allow users to access it from a landing page
- Open in lens should be in the same tab

**Comment by drewpost** [comment]
Closing as redundant - this is the issue to look at for GA definition https://github.com/elastic/uptime/issues/361
