### ISSUE TITLE
Exploratory View Polish

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#327]
Carried over from https://github.com/elastic/uptime-dev/issues/51

  - [x] Use EUI viz colors for charts
  - [x] Use sentence case and abbreviations for legends and tooltips (for example: currently it says "Secondes" where it could be "s") (fixed in https://github.com/elastic/kibana/pull/101520)
  - [x] Currently the reports produce charts with different heights, it should be the same height for all charts
  - [x] the unit should be dependent on the number, for example instead of "26000 Milliseconds", it should say "26 s" (fixed in https://github.com/elastic/kibana/pull/101520)

Carried over from https://github.com/elastic/kibana/issues/98602

**The context menu/popover for the filtering doesn't look like the EuiContextMenu on the navigation titles**
The context menu / popover styling deviates from the original component with not using the title option to display the selected group and back options. I consider this an enhancement if needed.

<details>
<summary>View screens</summary>

<img width="448" alt="Screenshot 2021-04-28 at 14 22 41" src="https://user-images.githubusercontent.com/4104278/116405010-7a141d80-a82f-11eb-9e87-82d9a756385c.png">
<img width="461" alt="Screenshot 2021-04-28 at 14 23 31" src="https://user-images.githubusercontent.com/4104278/116405015-7b454a80-a82f-11eb-9496-552ebdd91440.png">

</details>

**Responsive layout: Perhaps not necessary for experimental, but if possible it'd be nice if the definition options would just vertically align instead of the horizontal layout for smaller screens (below 1024px)**

<details>
<summary>View screens</summary>

<img width="1108" alt="Screenshot 2021-04-28 at 14 27 46" src="https://user-images.githubusercontent.com/4104278/116405275-c0697c80-a82f-11eb-9c5f-a11cc24fac17.png">

</details>

**Small enhancement: Use the same chart options display as in Lens**
The Lens app displays the chart options simply as a group button option instead of the selector.

<details>
<summary>View example</summary>

<img width="268" alt="Screenshot 2021-04-28 at 14 29 19" src="https://user-images.githubusercontent.com/4104278/116405392-e2fb9580-a82f-11eb-91d4-44000ed4dfba.png">

</details>

**Comment by shahzad31** [comment]
Relevant issues are fixed and remaining will not be relevant after redesign

**Comment by justinkambic** [comment]
I checked the various polish items locally and they seem to be looking good.
