### ISSUE TITLE
[Discuss] What should Uptime -> Observability integrations copy be?

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#33]
Today we are adding integration links from Uptime to the other Observability solutions.

We have some working copy in `master` and our subsequent PRs. These links are displayed in an action-style popover in our monitors list (imaged below).

![image (1)](https://user-images.githubusercontent.com/18429259/57082632-1c42ae80-6cc5-11e9-8b9f-e3ba5a2545aa.png)

The copy is essentially placeholder and should receive some dedicated treatment.

Right now we have:

| Solution name | Integration text |
| -------------- | --------------- |
| APM                 |  Check APM for domain |
| Infra UI             | Check Infra for pod UID |
| Infra UI             | Check Infra for container ID |
| Logs UI             | Check Logs for pod UID |
| Logs UI             |  Check Logs for container ID |

As already mentioned, these are not thought of as final copy. The purpose of this issue is to reach a consensus on what these links should say.

**Comment by dov0211** [comment]
I think we should use the terms: Logs metrics and APM as those are the 3 pillars of observability we keep mentioning, I also think we should be consistent across our solutions 
My suggestion:
| Solution name | Integration text |
| -------------- | --------------- |
| Infra UI             | Show pod metrics |
| Infra UI             | Show container metrics |
| Infra UI             | Show host metrics |
| Logs UI             | Show pod logs |
| Logs UI             |  Show container logs |
| Logs UI             |  Show host logs |
| APM                 |  Show APM service |

**Comment by justinkambic** [comment]
There has been chatter about this on other issues as well.

cc @makwarth @andrewvc @tbragin 

Can we use this issue to finalize the copy discussion? We have open PRs for Infra and Logs that I'd like to merge in the next couple of days. We could follow that up with a finalization PR for all of the integrations where we ensure the copy/iconography looks good, and that they're checking feature availability before displaying links. At that point we can consider this issue and https://github.com/elastic/uptime/issues/32 resolved.

**Comment by andrewvc** [comment]
These labels are fine for now.

My personal hope is that this is a temporary UI. Once we actually start showing container/other info we should move these links to those items. In other words we should display `ContainerId: foo (Logs | Metrics`.

**Comment by tbragin** [comment]
I'm not crazy about abbreviation "infra". What's wrong with Dov's suggestions for labels? They seem reasonable to me.

**Comment by andrewvc** [comment]
This was shipped
