### ISSUE TITLE
The last successful screenshot should be from the same location

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#330]
When a step fails and we show the screenshot of the last successful check as a comparison to the failure, it does so using the screenshot of the most recent successful test prior to the failure.

However, when tests for the same monitor are running from multiple locations, the screenshot we show will be the most recent (prior to the failure) regardless of location.

It’s not uncommon for websites to deliver different content based on the location of the client.  As such, the most recent good image (for comparison) should only be shown from test results from the same location.

In fact, if there are no previous good tests from this location, then no comparison image should be shown (even if there is a good test from a different location), as it’s a misleading comparison.

**Comment by awahab07** [comment]
**Post FF Testing**

LGTM
- Does respect the location for monitor-with-locations when listing **last successful check**.
- Doesn't list **last successful check** for a failed step with no prior successful steps.
- Correctly shows the last successful screenshot and links to last successful step.

**Monitors with locations** (Used oblt-edge for testing)
1. A successful ping on 1:34:24 PM with first step timestamped at 1:34:13 PM with location **spa** shows only one (successful) screenshot.
![spa-heartbeat successful](https://user-images.githubusercontent.com/2748376/140744144-c7a0dd96-ca6d-4846-8b32-8b083156039e.png)
2. The same monitor fails for the same location (**spa**) on the next ping (1:35:24 PM). Notice that there are other successful pings for the same monitor for different locations, in between the last successful **spa-** and failed **spa-** ping.
![spa fail list](https://user-images.githubusercontent.com/2748376/140745557-5271d945-a3e0-4676-ae92-c083351a1cf0.png)
3. The failed step shows two screenshots, the failed one and the last successful one from step 1 above with a link to the "last successful check". The last successful check is from the same location although there were more recent successful steps from other locations.
![link to success](https://user-images.githubusercontent.com/2748376/140745668-02644cf3-c84a-4b6c-b2b6-d0f088b3d59a.png)
4. "the last successful" link correctly takes to the last successful step for the same location.
![link back to successful](https://user-images.githubusercontent.com/2748376/140745713-54707113-bfca-4ed5-8743-f54f5274453c.png)

**Monitors without locations**
1. Successful step shown on one (successful) screenshot.
![Screenshot 2021-11-08 at 17 20 21](https://user-images.githubusercontent.com/2748376/140780674-dfd6433e-4e7b-4e85-a728-4772f80066ef.png)
2. A failed step doesn't show a "last successful check" screenshot if there's no prior successful check.
![no prior success step](https://user-images.githubusercontent.com/2748376/140781059-947460fb-49cc-44e2-83c1-235d9b1bb6fe.png)
3. Notice the failed step at 5:18:49 PM, it should mention the step at 5:16:49 PM as "last successful check".
![Screenshot 2021-11-08 at 17 19 50](https://user-images.githubusercontent.com/2748376/140781313-b577da9d-b98d-43f7-9a0d-5239c5a97b49.png)
4. It correctly includes and links the last successful check screenshot.
![Screenshot 2021-11-08 at 17 20 07](https://user-images.githubusercontent.com/2748376/140781549-6e60bee4-4e2b-421a-8b42-0a03da997b34.png)
