### ISSUE TITLE
Improving typings in the uptime code

### ISSUE THREAD

**Issue by shahzad31** [elastic/uptime#331]
In uptime plugin code, we have lot's of usage of `any` type in the typscript code, example being

https://github.com/elastic/kibana/blob/master/x-pack/plugins/uptime/server/rest_api/index_state/get_index_pattern.ts#L16

We should get rid of all the usage of `any`

we can start with low hanging fruits, where we don't need many changes and then tackle complex usage of any.

**Comment by paulb-elastic** [comment]
Might be useful to break this down into multiple PRs
