### ISSUE TITLE
[Exploratory View] Add Label as an option in the filter and breakdown selector

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#334]
As a Web Performance Engineer at an ecommerce company
I want to filter and/or breakdown the Exploratory View data (especially Core Web Vitals) by label
So that I can see the performance data broken down by my online brands (for which I use labels to distinguish them)

ACs:
* There is a `Label` option in the **Filter** drop down in Exploratory View in the **User Experience (RUM)** workflow
* There is a `Label` option in the **Breakdowns** drop down in Exploratory View in the **User Experience (RUM)** workflow
* When selected, the data being shown is broken down and grouped into series that correspond to the individual Labels within the result data

**Comment by shahzad31** [comment]
We want to save these custom filters in saved object or user will have to selected label field every time from the custom popover?

**Comment by shahzad31** [comment]
@paulb-elastic  I think this needs futher refinement, we need design and need to determine which EUI component can be used for this

**Comment by dominiqueclarke** [comment]
I am confused. What field does `label` map to?

**Comment by paulb-elastic** [comment]
> 
> 
> I am confused. What field does `label` map to?

Labels can be added in the RUM tag, for anything (e.g. using `apm.addLabels({ foo: "bar" });`).

Some users use this for a type of categorisation for their pages (e.g. different brands, or maybe product pages vs information pages).  Having a breakdown by label, allows those users to separate them in Exploratory View.

**Comment by justinkambic** [comment]
Post FF testing LGTM

Tested this against dev cluster and the search/application of the breakdown looked good to me. Couldn't seem to get data to show, but I'm thinking that's more a product of the underlying data than an issue with the software.

![Nov-01-2021 14-13-57](https://user-images.githubusercontent.com/18429259/139720251-897894e7-dc56-4cc3-b689-45658ae39c9b.gif)
