### ISSUE TITLE
[Synthetics] Improve performance of de-dupe support

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#337]
We recently introduced support for the chunking strategy the Synthetics agent uses to reduce index size. We can further optimize this by caching blocks locally; for some cases this can completely remove the need for querying image data. In average cases, it can reduce the required fetched data considerably.

We should also investigate if it's possible for us to implement some kind of request batching so we can fetch multiple screenshots' blocks in a single request.

**Comment by dominiqueclarke** [comment]
Verified that API calls are working as expected, and validated regression for the following
- Screenshots on monitor details page
- Screenshot slideshow on monitor details page
- Screenshot popover on monitor details page
- Screenshots on step details page
- Screenshot slideshow on step details page
- Screenshot popover on monitors details page
- Screenshot loading when navigating using check navigation
