### ISSUE TITLE
[Synthetics] Extract reference to o11y nav Page Template from page components

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#338]
Today, we have twofold rendering logic in our [main router switch](https://github.com/elastic/kibana/blob/master/x-pack/plugins/uptime/public/routes.tsx#L136), where we can either render the Observability nav sidebar template directly, or allow the component to do it itself. This adds some complexity and inconsistency with the way page components are designed. It's trivial to share any needed data amongst the various header/body components using a dedicated hook. As an added side benefit, extracting the template code will result in simpler component functions, without the need to import as many external dependencies.

This issue is related to https://github.com/elastic/kibana/issues/103670; I would have normally folded the work needed to resolve this into that issue, but we are post-FF and as this isn't a bug per se, we are choosing to only target this part of the change for the 7.15 release.

**Comment by dominiqueclarke** [comment]
This was mainly a code change that was validated in #104939.

For regression, Uptime page templates continue to be valid, with only one h1 per page with only valid html markup nested inside.
