### ISSUE TITLE
Users are encountering oversized bucket aggs

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#34]
**Describe the bug**
Some of our elastic queries use aggs that we felt were defined in a way that they wouldn't overflow the default bucket size, but [we have had users report problems](https://discuss.elastic.co/t/uptime-error-graphql-error-too-many-buckets-exception-trying-to-create-too-many-buckets-must-be-less-than-or-equal-to-10000-but-was-10001/179432) related to this.

We should revisit our queries and update them to allow our users to query an arbitrary window of timeseries data for a reasonably large number of monitors without encountering these limits.

**To Reproduce**
1. Configure Heartbeat to monitor ~15-20 monitors at a rate of 1-5 seconds each.
2. Allow Heartbeat to run for an hour (check to ensure data is accumulating as you'd expect).
3. Load the Uptime UI and set the date range for the past hour.
4. You should see an error message for the monitors list.

**Expected behavior**
The monitors list should display the top 50 monitors.

**Debug logs**
N/A

**Comment by andrewvc** [comment]
@justinkambic how much of this would be fixed by using the states index once it's done?

**Comment by justinkambic** [comment]
Hm.. I don't know how much it will be improved, it depends on the architecture we build around the new index. We could conceivably build a secondary query to enrich the results of our states index queries from the results of the first one, so we may still be grabbing quite a few buckets.

I'll put an update on this issue summarizing what we discussed earlier:
- we are changing our implementation of `auto_date_histogram` to use `date_histogram`
- this helps us to avoid the seeming lack of predictability with our old query (which requires further investigation)
