### ISSUE TITLE
Detect when mapping is missing in Heartbeat indices and report in Uptime app

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#359]
**Describe the bug**
Today, we get lots of bug reports that people cannot query their Uptime data. Almost always, it's because their mapping is somehow not correct. The remediation is to stop Heartbeat, delete their improperly-mapped indices, and restart Heartbeat. We could probably detect this error state and direct them to documentation that will show them how to fix the problem.

This could potentially save many hours of support staff's time dealing with this problem, and reduce the number of forum posts we receive detailing this issue.

**To Reproduce**
1. Start Elasticsearch and Heartbeat
2. Delete your Heartbeat indices
3. Load the Uptime app, observer that nothing works

**Expected behavior**
Instead of showing error states all over the place, we could detect that the expected mapping for some key fields are not correct, and direct the user to documentation that can help them remediate this problem.

**Debug logs**
Attach your debug logs.
See the [documentation](https://www.elastic.co/guide/en/apm/agent/java/current/trouble-shooting.html#trouble-shooting-logging)
about how to enable debug logging.

<details>
<summary>Click to expand</summary>

```
server    log   [14:36:55.045] [error][http] ResponseError: search_phase_execution_exception: [illegal_argument_exception] Reason: Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [monitor.id] in order to load field data by uninverting the inverted index. Note that this can use significant memory.
    at onBody (/Users/jk/git/justinkambic/kibana/node_modules/@elastic/elasticsearch/lib/Transport.js:355:23)
    at IncomingMessage.onEnd (/Users/jk/git/justinkambic/kibana/node_modules/@elastic/elasticsearch/lib/Transport.js:279:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  meta: {
    body: { error: [Object], status: 400 },
    statusCode: 400,
    headers: {
      'x-opaque-id': 'd671e3d0-8de4-4605-90c1-a3e4db3a9b24',
      'x-elastic-product': 'Elasticsearch',
      'content-type': 'application/json;charset=utf-8',
      'content-length': '1858'
    },
    meta: {
      context: null,
      request: [Object],
      name: 'elasticsearch-js',
      connection: [Object],
      attempts: 0,
      aborted: false
    }
  }
}
```
</details>

### Screenshot

This is how the UI looks when this happens, super un-helpful:

![image](https://user-images.githubusercontent.com/18429259/131557972-9be5e2d7-1472-4f97-83a0-289342f798f7.png)

**Comment by justinkambic** [comment]
CC @liciavale - you may want to provide some insight on how this should look. At the moment I was thinking of an alternate empty state to what we display today:

![image](https://user-images.githubusercontent.com/18429259/131558298-78f79d44-13c6-4aa0-bccb-b58b0af2bf69.png)

If you have thoughts to share I'd welcome them 🙂

**Comment by liciavale** [comment]
Hey @justinkambic  LGTM

**Comment by lucasfcosta** [comment]
Just to confirm, is this what one is supposed to see after they've deleted their Heartbeat indexes?

It looks different form the screenshot from earlier, so I just wanted to confirm.

![Screenshot 2021-11-01 at 11 07 42](https://user-images.githubusercontent.com/6868147/139662568-0b4f1951-1ed1-4cc9-a08b-2cc91fef772c.png)

**Comment by shahzad31** [comment]
@lucasfcosta yes you are right, this is a new view which represent mapping error state.
