### ISSUE TITLE
[Uptime] Certs loading state UX on page reload

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#360]
**Describe the bug**
When the page is reloaded on the Uptime app's Certs page, the UI tells the user there are no items. After the initial fetch, the loading experience is much nicer and accurately reflects the state of the data.

**To Reproduce**
1. Configure some monitors that will use TLS
2. Navigate to the certs page
3. Refresh the page
4. Notice the warning that no items were found; shortly after you see this, all the items that were found appear.

**Expected behavior**
There should be a loading state any time we are waiting for a fetch to resolve.

![Sep-07-2021 12-19-17](https://user-images.githubusercontent.com/18429259/132391677-773d23bd-c2b2-46e6-8223-6d7ae16cee27.gif)

**Comment by shahzad31** [comment]
POST FF Testing looks good !!
