### ISSUE TITLE
Exploratory View GA Definition

### ISSUE THREAD

**Issue by drewpost** [elastic/uptime#361]
### Capabilities

- [x] Look and feel and user experience match the new designs as contained here. 
- [x] Single series
- [x] Multi-Series
- [x] Same cohort, different time
- [x] Different cohort, same time
- [x] Mobile APM, User Experience and Synthetics series options
- [x] Chart type controls
- [x] Series names as the series data type
- [x] Breakdowns enabled only on first series (alternative, breakdown on only 1 series)
- [ ] When broken down, legend shows series name pre-pended to broken down value name (**depends on Elastic Charts and Lens**) - delayed to 8.1.0
- [x] "Apply" button to enable doing a number of actions and then requesting the results
- [x] Entry points from Uptime, User Experience and Mobile APM service views
- [x] Time period comparisons on charts with time series X axis must automatically match the length of the main series. User can pick start OR end date/time and we auto fill
- [x] Filters are multi-level capable (ie Browser, Browser Family, Browser Family Version) 
- [x] Filters are all include OR exclude for each category
- [x] URL filter enables exact matches OR wildcard matching
- [x] Chart must show date/time created AND date/time range shown
- [x] Change the badge to remove beta

### Metrics, Filter and Breakdown Options by Data Type

**User Experience**

Metrics: 
Page views, Page Load Duration, "Backend" Time, "Frontend Time", First Contentful Paint, Largest Contentful Paint, First Input Delay, Total Blocking Time, Cumulative Layout Shift, Page weight (over the wire), Page weight (uncompressed), Number of page objects

Filters:
- Operating System: OS Family>Major Version>Minor Version
- Browser: Browser Family>Major Version>Minor Version
- Device Make & Model: Device Make>Model
- Location: Country>Region>City
- Web Application: Web Application
- Environment: Environment
- URL: List of top URLs with ability to search, select specific URL, wildcatted pattern match and multi-select
- Labels: Labels

Breakdown: 
All of the filters
Calculation (for time series charts)

**Synthetics**

Metrics: Page views, Page Load Duration, "Backend" Time, "Frontend Time", First Contentful Paint, Largest Contentful Paint, First Input Delay, Total Blocking Time, Cumulative Layout Shift, Page weight (over the wire), Page weight (uncompressed), Number of page objects, Failed Tests,
- Testing Location: Location Name
- Monitor Type: Monitor Type
- Tags: Tags
- Labels: Labels

Breakdown: 
All of the filters
Calculation (for time series charts)

**Mobile User Experience**

OS Platform: OS Family>Major Version>Minor Version
Host OS: OS Family>Major Version>Minor Version
Service Version: Major Version>Minor Version
Carrier Location: Country>Region>City
Carrier Name: Name
Connection Type: Connection Type
Device Model: Device Make>Model

Breakdown: 
All of the filters
Calculation (for time series charts)

**Telemetry**

- [ ] Count of filters
- [ ] Count of data types selected
- [ ] Measure of time between hitting apply and displaying a chart on screen

**Prototype to see it in action:**
https://www.figma.com/proto/UDXscgU9o3p6auDOy6Zov7/Exploratory-view?node-id=1957%3A311044&scaling=min-zoom&page-id=1957%3A308594&starting-point-node-id=1957%3A311044

**Mockups:**
https://www.figma.com/file/UDXscgU9o3p6auDOy6Zov7/Exploratory-view?node-id=1387%3A367986

Outstanding Bugs
- elastic/kibana#113327
- elastic/kibana#113326
- elastic/kibana#113279
- elastic/kibana#113129
- https://github.com/elastic/kibana/issues/115739
- https://github.com/elastic/kibana/issues/113711
- https://github.com/elastic/kibana/issues/115740
- https://github.com/elastic/uptime/issues/370
- https://github.com/elastic/kibana/issues/115741
- https://github.com/elastic/kibana/issues/114868

Outstanding Features
- elastic/kibana#112860
- elastic/kibana#113421
- https://github.com/elastic/kibana/issues/113433
- https://github.com/elastic/kibana/issues/116229
- Better solution for y axis labels
- https://github.com/elastic/kibana/issues/113712
- https://github.com/elastic/kibana/issues/114867
- https://github.com/elastic/uptime/issues/369
- https://github.com/elastic/uptime/issues/373

**Comment by shahzad31** [comment]
`When broken down, legend shows series name pre-pended to broken down value name
`
this is not an easy thing to do, can we push this out of MVP scope?

**Comment by drewpost** [comment]
Let's bring this up at refinement. It was super hard to understand the legend when there was a broken down series without this capability. cc @dominiqueclarke I think I remember you saying you looked at this?

**Comment by dominiqueclarke** [comment]
" Time period comparisons on charts with time series X axis must automatically match the length of the main series. User can pick start OR end date/time and we auto fill". This behavior wasn't immediately obvious to Justin and I. We may need to design a small callout to explain this behavior. Also, how does this meld with the ability to timeshift with "same cohort, different time". We may need design to help callout when time can be shifted and when it can't. 

I believe breakdown by calculation is currently not implemented, so that caught my eye. @shahzad31 wondering if this is as simple as the other breakdowns. 

@drewpost can you clarify what you mean by calculation in this line:
```
Breakdown:
All of the filters
Calculation
```

**Comment by andrewvc** [comment]
@dominiqueclarke I suspect that @drewpost meant that the length of time being compared must remain constant. You could only compare 12:00AM-3:00AM with another 3 hour period, but not a 2 hour period for instance.

**Comment by paulb-elastic** [comment]
Updated the requirement for sensible defaults to `Series names as the series data type`

**Comment by paulb-elastic** [comment]
Discussed in refinement - let's keep this ticket open to track as we approach FF (at which point we might split this up)

**Comment by paulb-elastic** [comment]
https://github.com/elastic/kibana/issues/116172 added to the list, ready for splitting out and prioritising.

**Comment by shahzad31** [comment]
removing elastic/kibana#116172  after discussion with the the team.
