### ISSUE TITLE
Move monitor list histogram API to Async search

### ISSUE THREAD

**Issue by shahzad31** [elastic/uptime#364]
As part of meta https://github.com/elastic/uptime/issues/293 we need to move monitor list histogram API to Async search

**Comment by justinkambic** [comment]
Post-FF testing LGTM:

![image](https://user-images.githubusercontent.com/18429259/139713791-4e773906-c773-49f3-b68b-97b33fb3f6f0.png)

All I did was make sure that the histogram showed up in the monitor list. Assuming the original PR contained the necessary embeddable replacement code.
