### ISSUE TITLE
[Exploratory View] Add embeddable component

### ISSUE THREAD

**Issue by shahzad31** [elastic/uptime#365]
In order to replace existing charts in observability apps, we need an embeddable version of exploratory view.

AC's

- We should be able to embed exploratory view into amy app
- Ability to pass time date picker range and series attributest to render
- Option to edit chart in exploratory view

This requirement blocks https://github.com/elastic/uptime/issues/323

and was determined as part of https://github.com/elastic/uptime-dev/issues/67

**Comment by dominiqueclarke** [comment]
No data available is showing in the example, despite having monitors in the `heartbeat-*` index within the past 5 days. I am running elasticsearch and heartbeat locally, running the master heartbeat binary and es via `yarn es snapshot` on the 7.16 Kibana branch. Tested on commit `0c347055e667851383a7415dfeaaa985bc01fe07`

<img width="820" alt="Screen Shot 2021-11-01 at 2 57 46 PM" src="https://user-images.githubusercontent.com/11356435/139726104-20b7b3fb-7677-4e4c-b5e3-b8ebec9eefce.png">
