### ISSUE TITLE
[Observability] [Exploratory View] Collapse series config accordions when applying changes

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/uptime#369]
As an analyst, I want to be able to clearly focus on my chart configured with exploratory view, without distractions. 

When clicking 'Apply changes' in exploratory view, we should collapse the series accordions to allow the user to better focus on the chart.

**Comment by justinkambic** [comment]
Post FF Testing LGTM

![Oct-26-2021 16-29-00](https://user-images.githubusercontent.com/18429259/138956041-6d54e463-7cc1-4a24-a254-d1ccc9d4a6e5.gif)
