### ISSUE TITLE
[Observability] [Exploratory View] Change title to match figma

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/uptime#370]
The title of exploratory view is incorrect. It should be updated to match the figma, which says `Explore data`.

Figma: https://www.figma.com/file/UDXscgU9o3p6auDOy6Zov7/Exploratory-view?node-id=1163%3A230098

**Comment by justinkambic** [comment]
Post-FF Testing LGTM

![image](https://user-images.githubusercontent.com/18429259/139734081-2ab1f1a2-2cee-4313-bfa1-2503ea6111bb.png)
