### ISSUE TITLE
[Synthetics integration] Add option to add script from the Elastic Synthetics Recorder

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/uptime#371]
As a QA engineer, I want to be able to create synthetics monitors within the Synthetics Integration, using the Elastic Synthetics Recorder.

AC
- [ ] A third "tab" is added to the synthetics integration for the script recorder method with a tech preview label for this mechanism
- [ ] The tab content will include a link to the Elastic Synthetics Recorder download page.
- [ ] The tab content will include a file upload link
- [ ] The file upload link will support select and drag and drop
- [ ] The file upload link will only allow javascript files
- [ ] The tab content will allow visualization of the script uploaded
- [ ] The script will be "editable" by removing and replacing the script, both in the create integration and edit integration flow
- [ ] The ZIP URL should still be the default

**Comment by paulb-elastic** [comment]
@dominiqueclarke discussed with @drewpost, let's mark this as tech preview rather than beta at this stage

**Comment by paulb-elastic** [comment]
@dominiqueclarke we've also clarified in the ACs that the ZIP URL should still be the default

**Comment by dominiqueclarke** [comment]
> @dominiqueclarke discussed with @drewpost, let's mark this as tech preview rather than beta at this stage

Sorry, does tech preview mean "experimental"?

**Comment by paulb-elastic** [comment]
Yes, they have been used interchangeably in the past

@drewpost, can you confirm which to use?

**Comment by shahzad31** [comment]
POST FF Testing Done, Looks good

- [x] A third "tab" is added to the synthetics integration for the script recorder method with a tech preview label for this mechanism
- [x] The tab content will include a link to the Elastic Synthetics Recorder download page.
- [x] The tab content will include a file upload link
- [x] The file upload link will support select and drag and drop
- [x] The file upload link will only allow javascript files
- [x] The tab content will allow visualization of the script uploaded
- [x] The script will be "editable" by removing and replacing the script, both in the create integration and edit integration flow
- [x] The ZIP URL should still be the default
