### ISSUE TITLE
Exploratory View - Synthetics Step Level Capabilities

### ISSUE THREAD

**Issue by drewpost** [elastic/uptime#372]
As a user of the Exploratory View
I want to be able to analyse data based on the individual step level of a multi-step synthetic journey
So that I can view information that's specific to a certain part of my application or journey without the cognitive load that comes from having the entire journey shown

Essential: Monitor becomes multi- level. You have monitor name which will included aggregated results from all steps of a journey OR you can choose a given step within a journey to display results for
Breakdown: Users can breakdown by steps on a given chart (takes the monitor chosen at the start of the series builder and automatically breaks down by those steps) 
Action: Click through on a point in time on any charts to the page load waterfall for that step in Uptime

**Comment by justinkambic** [comment]
Post-FF Testing LGTM

![untitled](https://user-images.githubusercontent.com/18429259/139727954-e49f7a5b-2f04-4499-bbcd-ab8d5982a177.gif)
