### ISSUE TITLE
[Exploratory View] Refactor URL filter to allow wildcards

### ISSUE THREAD

**Issue by shahzad31** [elastic/uptime#373]
We need to overhaul URL filtering in exploratory view to accomodate wildcards matching.

Ideally we should use the same component from user experience.

**Comment by justinkambic** [comment]
Post-FF testing LGTM
![Nov-01-2021 14-39-45](https://user-images.githubusercontent.com/18429259/139723645-65cdc651-156b-4ca8-84b5-22855511bc7b.gif)
