### ISSUE TITLE
Add Link to Quick Start to Integration Main Description

### ISSUE THREAD

**Issue by drewpost** [elastic/uptime#376]
Add the following copy to the main synthetics integration description:

"Elastic Synthetic monitoring is included with all license levels via the Uptime app in Observability. In this release, you will need to set up your own synthetic testing nodes to execute your tests. For step by step instructions on how to set up a synthetic testing node for Elastic Synthetics with Elastic Agent, click here for the Quick Start Guide. Hosted testing locations will be coming in a future release."

**Comment by justinkambic** [comment]
Post FF Testing LGTM

![image](https://user-images.githubusercontent.com/18429259/138931123-5a1f8f1d-d614-45d2-bd65-1ceeee622ac5.png)
