### ISSUE TITLE
Script Recorder Initial Docs

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#377]
For the 7.16 release, we will create limited documentation for the Script Recorder, in the GitHub [repo](https://github.com/elastic/synthetics-recorder), as opposed to *proper* documentation pages, which we will look to implement in 8.0 (as per https://github.com/elastic/observability-docs/issues/988).

ACs:
* Create a location in the GitHub [repo](https://github.com/elastic/synthetics-recorder) that documents how the script recorder is downloaded, installed and used (to some level) (this can continue to be modified as we release future alpha releases, outside of the stack release)
* Update the Integration UI to link to this URL (the one that currently refers to the download location)

**Comment by justinkambic** [comment]
> documents how the script recorder is downloaded, installed and used

Regarding this issue, how specific do we want the installation instructions to be? Should we assume the user doesn't know how to install a binary on their given platform, or is it ok to link them to the releases and say "download, unpack, and install the binary for your platform"?

**Comment by vigneshshanmugam** [comment]
Pasting from the slack conversation. 

> I was thinking in the line of having a dedicated docs folder and have installation, recording files as markdown which we can host as GH pages for the time being. (edited)

**Comment by paulb-elastic** [comment]
> 
> 
> > documents how the script recorder is downloaded, installed and used
> 
> Regarding this issue, how specific do we want the installation instructions to be? Should we assume the user doesn't know how to install a binary on their given platform, or is it ok to link them to the releases and say "download, unpack, and install the binary for your platform"?

@drewpost do you have a specific level you want this aimed at?  This is meant as an initial set of docs before they are *properly* set up in the docs area - how detailed do you want this?

**Comment by drewpost** [comment]
Aren't we offering pre-packaged versions of the app to download in exe or .app (inside a dmg)? This would be my preferred approach vs asking them to do anything in a command line. Again, thinking lowest common denominator for the primary user this tool is aimed at. Command line = scary! 

Aside from that I think we should also document the high level process of getting started (ie just hit record, don't need to install anything else), what to do when you're done recording (ie how to copy and paste out or download JS file) and also use it as another touch point to solicit feedback on the recorder by pointing out the feedback link again.

**Comment by justinkambic** [comment]
The associated PR does not address all of these concerns. It does outline the basic usage of the recorder and the main features. We don't have any screenshots included as of yet, for instance. Are we ok with text-only docs in the repo itself, until we have a proper docs page set up where we can maintain screenshots etc.?

**Comment by justinkambic** [comment]
I've updated that PR so as not to resolve this, but it will provide a baseline set of docs that we can iterate over.

**Comment by justinkambic** [comment]
I've put this in Done for now, and will assume it's closed by https://github.com/elastic/synthetics-recorder/pull/60; should we want a more formal set of docs we should create an issue for the Docs team to work with us on.

**Comment by paulb-elastic** [comment]
For info, added a small follow up PR (https://github.com/elastic/synthetics-recorder/pull/84) to clarify the Script Recorder is not supported.
