### ISSUE TITLE
[Uptime] Allow logical AND in Monitor Status rule

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#391]
**Is your feature request related to a problem? Please describe.**
We [received a request](https://discuss.elastic.co/t/uptime-alert-on-ha-heartbeat-deployments/287138) from a user to be able to receive alerts only when their service is down in _all_ locations. Today, if we configure an alert with multiple locations and any of them go down, the rule will become active.

**Describe the solution you'd like**
We should add an option that allows users to make it so a rule only activates when _all_ of the specified locations are simultaneously unavailable.

**Describe alternatives you've considered**
N/A

**Additional context**
There may be some workaround possible with custom query logic, but if we want users to be able to do this it will be worthwhile to add the functionality as part of the standard UI flow.

**Comment by sanjaruzic** [comment]
Adding a specific customer use case: 

The customer has several heartbeat instances monitoring the same URLs from different locations.
Currently it is not possible to group the alerts coming from different heartbeat instances for the same URL.

The customer wants to get an alert if 1 instance is not reporting.
The SQL equivalent would be
select count(distinct(observer.geo.name)) from 'heartbeat-7* < X

**Comment by justinkambic** [comment]
We're going to evaluate putting this request onto our roadmap. Earliest possible target would be 8.1, but at this point we haven't committed to working on it at all.

If it does get added you'll be able to track the board it's on (projects link on the sidebar) and the issue's target version label.

**Comment by paulb-elastic** [comment]
@justinkambic the main description (alert when all are down), seems different to https://github.com/elastic/uptime/issues/391#issuecomment-974077226 suggesting an alert if one location is down.  Can you clarify?

**Comment by justinkambic** [comment]
> the main description (alert when all are down), seems different to #391 (comment) suggesting an alert if one location is down. Can you clarify?

Per the original forum request:

```
Having Heartbeat deployed to multiple hosts, I would like to be alerted only when a monitor (e.g. ICMP probe on "example.org") fails on all of them.
```

Today we will trigger an alert for a rule when _any_ location is down. This is the canonical case, and today we're not accounting for the more esoteric choice of wanting to know only when _all_ are down.

**Comment by paulb-elastic** [comment]
Pinging @andrewvc re @justinkambic's [comment](https://github.com/elastic/uptime/issues/391#issuecomment-992602617)

**Comment by paulb-elastic** [comment]
@drewpost to find out some more about the *why* for this, for example, to handle the unreliability of ICMP for example with retry capabilities.

**Comment by huemac** [comment]
Hi @paulb-elastic 
This is useful when we have heartbeat deployed to multiple availability zones (e.g. in Azure) and we only want to be alerted if an endpoint is reported down on ALL the az's.
It may be acceptable for the application that is under monitoring to be inaccessible from some az's. But if all heartbeat deployments are all reporting the endpoint as "Down", then there is a real issue that needs to be acted on.

**Comment by kevinnoel-be** [comment]
We have the same use case here. We've heartbeat instances deployed in multiple AZs and we'd need to know when the monitor is down from all observers point of view.
Also, the current Uptime monitor status check only allows for conditions like `Matching monitors are down > X times within last Y minutes` which is not very useful in this setup as we may have a variable number of heartbeat instances (i.e. at least one, expected two).

**Comment by paulb-elastic** [comment]
Captured in https://github.com/elastic/kibana/issues/153571
