### ISSUE TITLE
[Step Lists Page] Adds step duration for each step in steps list

### ISSUE THREAD

**Issue by shahzad31** [elastic/uptime#392]
we have a step list page for each synthetics monitor journey run, it display step name, image and a link to waterfall chart

it also has few more info like browser console etc in expanded form

we should also add a step duration for each step , it can be a new column in the table, just like we have in the ping list on monitor details page

![image](https://user-images.githubusercontent.com/3505601/138834998-d0fca055-eb98-44ed-99f1-500f2ae82a33.png)

### Nice to have:
We can also show preview of the step duration as a trend chart using exploratory view embeddable, and deep link it to the exploratory view for further investigation.

**Comment by emilioalvap** [comment]
nit: Found that when the user interacts with step duration popover, the event is being propagated to the corresponding row. I've created the following issue to address that: elastic/kibana#122032.

The rest is LGTM.

Tested by:
- Starting Kibana 8.0.0-SNAPSHOT locally.
- Navigating to Observability -> Uptime.
- Selected a browser type monitor -> last execution.
- Checked that step duration is displayed if available and exploratory view popover is displayed when hovered upon.
