### ISSUE TITLE
Improve default connector creation flow for simple monitor alerts

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#395]
**Is your feature request related to a problem? Please describe.**
Today, when I create a connector to use as the default for my Uptime settings, it still requires me to assign it to the default connector setting if there's no connector selected. Oftentimes, when I create a connector, my intention is for it to be the default, and when the current flow completes, I forget to manually make it the default.

**Describe the solution you'd like**
When there is no default connector selected, if I create one using the custom connector creation UI, it should set the default connector to the one I just created.

**Describe alternatives you've considered**
N/A

**Additional context**
![20211119092706](https://user-images.githubusercontent.com/18429259/142638758-0c1f9216-b171-4749-a881-9f36fc3cc1a4.gif)

**Comment by paulb-elastic** [comment]
The flow is simplified for the Synthetics use case
