### ISSUE TITLE
[Uptime] Monitor summaries - Changes in the Overview page

### ISSUE THREAD

**Issue by dov0211** [elastic/uptime#40]
We would like the Overview page in Uptime to be:
- [ ] Compact view that presents an up to date information for each monitored endpoint.
- [ ] Grouping together relevant information on a single endpoint.
- [ ] Expose information such as Locations, IPs, status code, underline infrastructure (Host, Containers, Pods), without overwhelming the UI.
- [ ] Time picker should end with now (last hour/day/week, etc...)

Link to a design [doc](https://docs.google.com/document/d/1Dgv5ypeQ5W8QkHZ-e79p66UhDWVKQ_eNWUn5l1yl-r8/edit#)
Design issue https://github.com/elastic/uptime/issues/42

**Comment by andrewvc** [comment]
In implementation phase.
