### ISSUE TITLE
[Uptime] [UI Monitor Management] Hide all corresponding pages and new features behind a feature flag

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/uptime#408]
UI Monitor Management should only be available behind an explicit feature flag.

The feature flag will be `xpack.uptime.ui.unsafe.monitorManagement.enabled`.

Corresponding UI Monitor management routes should be unavailable when `xpack.uptime.ui.unsafe.monitorManagement.enabled` is `false` and available when `xpack.uptime.ui.unsafe.monitorManagement.enabled` is `true`.

_To enable/disable server part of monitor management, see https://github.com/elastic/uptime/issues/421_

**Comment by lucasfcosta** [comment]
> ⚠️ Please notice that this feature flag **did _not_ show me the links to the UI monitor management screens on version `8.0`, I had to test it on `8.1`, and thus I believe it needs fixing.**
> I tested this on the current tip of the `8.0` branch, whose hash is `11772615c663fafca30540801c0aba3ae4d462e6`.

I've just had to test this **on 8.1** by following the steps below:

1. Enabling the UI Monitor Management flag in `kibana.yml`:
    ```yaml
    # kibana.dev.yml
    xpack.uptime.ui.unsafe.monitorManagement.enabled: true
    ```
2. After enabling that, I do see the "monitor management" link on the top right corner of the Uptime app, as shown in the screenshot below.
    ![Screenshot 2021-12-15 at 17 24 30](https://user-images.githubusercontent.com/6868147/146235291-eda10987-c1e0-4074-b352-eb51055d2449.png)
3. In that page, I can also access the `add-monitor` page by clicking the "Add monitor" button on the top right corner of the page, as shown in the screenshot below. Furthermore, editing and deleting the monitor is not a problem.
    ![Screenshot 2021-12-15 at 18 44 04](https://user-images.githubusercontent.com/6868147/146246345-9258f4b0-7bd2-4ef0-bf8b-941d54d20baa.png)
    ![Screenshot 2021-12-15 at 18 45 34](https://user-images.githubusercontent.com/6868147/146246530-61f973fb-93e7-44ee-ae64-869f2039f6c6.png)
    ![Screenshot 2021-12-15 at 18 45 29](https://user-images.githubusercontent.com/6868147/146246533-b6eb7088-51ca-45a4-806b-eb1da030096d.png)
4. Finally, when I disable the UI Monitor Management flag in `kibana.yml`, I can't see those pages anymore.
    ```yaml
    # kibana.dev.yml
    xpack.uptime.ui.unsafe.monitorManagement.enabled: false
    ```
    When I try to access these pages directly through the routes, I also get a `404`.
    
    ![Screenshot 2021-12-15 at 18 47 30](https://user-images.githubusercontent.com/6868147/146246802-bd41792e-e09b-4692-9832-1469603254c8.png)
    
    ![Screenshot 2021-12-15 at 18 47 40](https://user-images.githubusercontent.com/6868147/146246799-e95e46b6-3d8f-4e9a-8840-272815df68e2.png)
    
    On another note, should we open a separate issue for the design of these `404` pages?


Worth highlighting again: it works on 8.1, but not on 8.0.

I also tested only the CRUD functionality, not running these with the service itself, which I plan on doing separately.

**Comment by dominiqueclarke** [comment]
To clarify, the service is not expected to work in 8.0. We were working on individual features before the 8.0 FF, but post FF we added more MVP features. As such, the work to test that the FF works positively can be done in `8.1.0`.

**Comment by lucasfcosta** [comment]
As per the comment above by @dominiqueclarke and what we discussed on Slack, I'll move on to moving this issue to "Done done" as the testing has been done in 8.1.0 successfully.
