### ISSUE TITLE
[Uptime] [Design] Monitors page redesign

### ISSUE THREAD

**Issue by dov0211** [elastic/uptime#41]
Here are the recommended changes for this page:
**Header:**

![image](https://user-images.githubusercontent.com/38371227/58581591-916bba00-8258-11e9-85cf-4ad17e055502.png)

- Add: Monitor name
- Add: TLS expiration date
- Add: Last update
- Remove: locations
- Remove: RTT

**Charts:**
![image](https://user-images.githubusercontent.com/38371227/58581619-ab0d0180-8258-11e9-810b-175a35aef87a.png)

- Replace “Check status” with “location availability”
- Replace “Monitor duration” to “Location overtime”
- Each line in the chart represent location duration over time

**History:**
![image](https://user-images.githubusercontent.com/38371227/58581684-d2fc6500-8258-11e9-8702-ce3e5720c3d3.png)

- Remove error type
- Add text on error column
- Add locations column

![image](https://user-images.githubusercontent.com/38371227/58581723-e4de0800-8258-11e9-975a-f35ebad457cb.png)

- Expand/collapse rows to get Filebeat / Metricbeat status
- Possibility to add drill down to Infra or Logs

Monitors page suggested wireframe
![image](https://user-images.githubusercontent.com/38371227/58581325-f7a40d00-8257-11e9-873a-8837a4015175.png)

Note: we should try to find a way to combine the 2 filters by location on the table and chart.

Link to design [doc](https://docs.google.com/document/d/1jlyOam08gC3oq0W8dim0BF-5QYEOXFqSg48nMwbirmg/edit#)

**Comment by justinkambic** [comment]
It should be noted that most of the features outlined in this design issue were implemented in https://github.com/elastic/kibana/pull/39751. We are missing the swim lane visualization due to technical constraints.

**Comment by andrewvc** [comment]
Shipping in 7.3
