### ISSUE TITLE
SPIKE: Any other places we ignore heartbeat/summary?

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#411]
We have had some bugs identified recently where Uptime was not considering the heartbeat/summary doc, meaning there were times where we were looking at partial results (from incomplete runs) in some of our queries.  If there is no heartbeat/summary doc, it means that the test is still in progress (or has crashed, and therefore won't complete), either way, the result is not complete and should not be considered within the existing reports.

Examples where this has come up:
* Alerting issue https://github.com/elastic/kibana/issues/118998
* Last good screenshot issue https://github.com/elastic/uptime/issues/330
* Alert triggered without matching the rule https://github.com/elastic/kibana/issues/115928

This spike is to investigate if we have other places in Uptime that need to take this into consideration.  It’s expected that this is only for where we are reporting on `browser` based test/results, as lightweight checks don’t have this same issue (which is where the problem stems from - having added multi step types of test, into Uptime).

ACs:
* Identify if there are any queries in Uptime that are reporting on `browser` type monitors/results that are not taking the heartbeat/summary doc into consideration
  * This could be via an audit, or running E2E tests, or some other method, to identify them
* If there are cases, raise separate issue(s) or just PR(s) to fix them

**Comment by andrewvc** [comment]
I think we've fixed these issues, and even if not this issue has outlived its usefulness. Closing.
