### ISSUE TITLE
[Uptime] Add Monitor Metrics to UI Monitor Management

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/uptime#414]
As an Uptime user, I want to be able to see metrics for UI Monitor management that provide a summary of the status of my current monitors.

These metrics include:

- Active monitors
- Disabled monitors
- Enabled monitors
- Archived monitors

Figma: https://www.figma.com/proto/wY1t5ElePiSmogTQJ04i5A/Monitor-creation?node-id=1515%3A242974&scaling=min-zoom&page-id=434%3A120

Questions for refinement
- What is the difference between active and enabled monitors
- What are archived monitors. What will the flow be for archiving a monitor?

**Comment by paulb-elastic** [comment]
This won't get implemented in Uptime, but considered in the Synthetics App, and options considered there.

/cc @liciavale
