### ISSUE TITLE
Add "AND" logic option for the search function in "Tag" filter

### ISSUE THREAD

**Issue by JaoKlintone** [elastic/uptime#417]
**Is your feature request related to a problem? Please describe.**
When we do the search for tags in Uptime's "Tag" filter and select 2 or more tags, result shows monitors that have any of the selected tags and not both of them. It uses the "OR" logic.

**Describe the solution you'd like**
We would like to see only monitors that contain both tags, so to narrow down the search.
Therefore, we would like to have an option in some Kibana setting to switch to the search using "AND" logic if wanted.

**Additional context**
![image(1)](https://user-images.githubusercontent.com/77189755/145005435-d52084d0-77bb-48b3-b710-a7bd6c6e9dab.png)

**Comment by paulb-elastic** [comment]
Thank you for the suggestion and identifying the use case you’re trying to achieve.

There are some considerations around having a consistent behaviour between filters (e.g. `AND` makes sense for `tag`, but does not for `port`, however this would introduce a difference in behaviour).

Right now, this would have to be achieved using the KQL query bar with the search term `tags : "service" and tags : "prd"`

![image](https://user-images.githubusercontent.com/70908889/148792690-ff6959ba-70f5-4943-a5eb-94488f0d2c32.png)

We are going to look at these additional capabilities (AND/OR) as part of the upcoming Synthetics App UI, which will simplify the management and reporting for synthetic monitors.

CC @liciavale / @drewpost for tracking in the Synthetics App.
