### ISSUE TITLE
Feedback for suites that cannot run

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#425]
This has come about from various discussions about there being little to no feedback when Heartbeat is unable to run a suite of Synthetics tests that have a ZIP URL for the source (e.g. an invalid configuration, or a syntax error in the ZIP).  Part of this was also raised/discussed in https://github.com/elastic/beats/issues/27924.

As a user of Synthetics suites with a ZIP URL source
I want to be informed in Uptime when there is a problem preventing the suite from running (such as a syntax error)
So that I can easily understand why monitors from the suite are not being shown on the Uptime Overview page

ACs:
* If Heartbeat is unable to execute the suite of tests as defined in a ZIP URL source, it stores this failure condition with some details about the failure, in ES
* This stored data does not interfere with any of the existing result data or alerting within Uptime
* There is a notification in the Uptime UI (such as a toast, or some other method), informing the user about the failure
  * The notification includes the details captured about the failure condition
  * There is no click through to more details, or see historic failures
* The user can dismiss the notification (there is no way to get back to it)
* Only show notifications for where the issue has occurred within the last x minutes (e.g. 30 minutes)

**Comment by andrewvc** [comment]
Somewhat related to https://github.com/elastic/beats/issues/29692

**Comment by andrewvc** [comment]
This is now superceded by:

https://github.com/elastic/uptime/issues/431
and 
https://github.com/elastic/uptime/issues/432
