### ISSUE TITLE
Simplified "Single Monitor" browser type

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#426]
For users who want to just load a single page and test that it works in a browser, they must write a small synthetics script. We should create a new simplified workflow for this, whereby:

1. We have a new `source` type in heartbeat of `url`, that takes a single URL and checks that it loads
2. The synthetics has a new mode whereby it can simply load a single URL
3. The same settings are exposed in the Kibana UI

Open Questions:

1. What level of validation should we perform?
2. How do we determine the page is 'done'?

**Comment by paulb-elastic** [comment]
I agree this is a good idea to make it easy to set up monitors with a single URL.  I also agree that there needs to be some assertion to check the page is loaded as expected.  A couple of points that come to mind:

* I strongly suggest this is still of the same `browser` type and not separated out from our existing types (it just becomes a different way of creating it, like **Inline**, **Suite/ZIP URL**, **Script Recorder** and now also **_Single Page_**)
* There should at a minimum be a text phrase to check for (without selector)
  * e.g. `hello world` exists on the page loaded
  * I think this is ok in this first instance to also check that the page is _done_
  * If user’s need something more specific, like a particular HTTP request has been fulfilled, or a specific selector has a certain value, then we should point them towards a normal scripting solution (inline or suite)
* I’m inclined to think the default 30 second timeout is ok here, but wouldn’t be against an option to expose this (e.g. specifying a timeout up to 120 seconds)

**Comment by paulb-elastic** [comment]
Discussed in refinement, input will have a URL and text input (to be on the loaded page) only

**Comment by paulb-elastic** [comment]
Here is an example of the new flow

![image](https://user-images.githubusercontent.com/70908889/154268597-5081432a-0e20-4aac-b7b7-e25d06264ac1.png)

> Open Questions:
    1. What level of validation should we perform?
    2. How do we determine the page is 'done'?

Validation:
* Validate the URL input (mandatory), just like we do for the HTTP monitor type
* In terms of validating the monitor, just a text assertion that the string is found on the page

Page done:
* Rely on the existing `step()` behaviour where we wait for the loaded state
* Anything more _complex_ should use a script

**Comment by paulb-elastic** [comment]
Requirements are going to be moved from here to https://github.com/elastic/kibana/issues/128473
(cc @drewpost @hbharding)

**Comment by paulb-elastic** [comment]
This is covered in https://github.com/elastic/kibana/issues/128473 (with the addition of the assertion requirement as mentioned in https://github.com/elastic/kibana/issues/128473#issuecomment-1147524569)
