### ISSUE TITLE
I would like to be able to include a link to the monitor that triggers an alert in the action associated with the alert.

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/uptime#429]
**Is your feature request related to a problem? Please describe.**
When creating an alert I cannot include the URL for the monitor that triggered the alert.  If I send an alert I want to be able to give the recipient the information to take the first step in finding the problem, which might be a link to the monitor or a link to a dashboard for the service. 

**Describe the solution you'd like**
I would like to be able to build up the URL to link back to, something like:
```
View in Kibana
{{kibanaBaseUrl}}/app/uptime/monitor/{{state.monitorUrl}}
```

**Describe alternatives you've considered**
I looked through the available bits and pieces in `{{state}}`, but cannot find the specific monitor.  The URL uses the base64 encoded  state.monitorId

**Comment by shahzad31** [comment]
`View in app {{context.viewInAppUrl}}` var has been added which can be used to deep link monitor in synthetics app from alert.

Example being 

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/3505601/215125297-2baa6d75-b1ed-42b3-9c6e-e927873d5ce6.png">

**Comment by paulb-elastic** [comment]
Post FF Testing looks good, e.g. adding
  ![image](https://user-images.githubusercontent.com/70908889/228615450-cb456dd1-7f8f-4eef-9c03-910c6dffd456.png)
Gives:
  ![image](https://user-images.githubusercontent.com/70908889/228615017-e55d916c-6c1e-4aa2-9637-d62b5d9b3f63.png)
