### ISSUE TITLE
[Uptime] Uptime support for dynamic settings / index names

### ISSUE THREAD

**Issue by dov0211** [elastic/uptime#43]
Uptime needs to support CCS in order for Uptime slider to support multi-region deployment

**Comment by andrewvc** [comment]
Comes with the states index

**Comment by andrewvc** [comment]
As an update to this as an MVP we just need to support custom index patterns in kibana.yml, letting users search across clusters. We also need to test this.

**Comment by andrewvc** [comment]
I'm shifting the goalpost here. Technically its actually easier to just do this dynamically in saved objects vs. the kibana.yml, and its a better feature. 

@katrin-freihofner when you get a chance it'd be great to get a UI mockup of how an uptime settings page (or dialog) might look. It would just be for the one index-pattern value. I'm thinking it could just be a popup dialog next to the date picker.

In the meantime I'm working on the REST API back-end of this here https://github.com/elastic/kibana/pull/53550

**Comment by katrin-freihofner** [comment]
@andrewvc I suspect, that there will be more settings in the near future!? If so, I propose to create a similar experience as in APM and Logs. The settings page is reachable via one of the tabs on the very top. 

<img width="969" alt="Screenshot 2019-12-23 at 09 15 38" src="https://user-images.githubusercontent.com/20965076/71345149-d2188100-2564-11ea-8e16-4089aada72db.png">
