### ISSUE TITLE
The filter list in the Create Rule panel only a subset of the fields

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/uptime#430]
**Describe the bug**
When creating an alert rule in the Uptime app I am presented with a filter area:
<img width="469" alt="Screen Shot 2022-01-05 at 12 39 09 PM" src="https://user-images.githubusercontent.com/25182304/148263584-b892e0cb-ef3e-4800-8aee-d5f4a150b8ab.png">

This leads me to think that this is the list of possible fields that I can use.  I look at the list and wonder what index this list represents.  It is very confusing.  I scroll through the list and it ends with `client.user.name.text`.  What I really want is something related to the URL of the website that I am monitoring, but the list ends.  Eventually I think "maybe I can type in `url` and find the right field".  That works, and I can filter like I want:

<img width="397" alt="2022-01-05_12-46-10" src="https://user-images.githubusercontent.com/25182304/148264488-f6fe9e0b-a5ad-485c-adab-ed807324cd7f.png">

I think that having a super long list (maybe of all of the possible fields, or all of ECS?) and only showing a small part of it is confusing.  I would prefer having a blank pick list at the start and a hint in the search line that currently says "Filter using sql syntax" to tell me "start typing part of a field name", so that I don't see a partial list at the start that I interpret as a list of all of the choices.

**Comment by drewpost** [comment]
Hey @DanRoscigno - Thanks of this. Can you help me out with what you're trying to do here that requires you to use the filters. We're looking at the alerting experience with our new Synthetics app and creating a more user friendly experience is a big part of that. I'm not sure what you were trying to that prompted this feedback!

**Comment by DanRoscigno** [comment]
Hi @drewpost I don't remember what my goal was, but this issue is to say "the UI should not show the laundry list of fields unless the user can scroll through all of the fields and not just the first 100"

To find out real use cases I would suggest working with the Cloud SREs and Infra to find out what they alert on with watcher and then try to recreate those with Alerting.
