### ISSUE TITLE
Add mappings for test now/run once mode

### ISSUE THREAD

**Issue by shahzad31** [elastic/uptime#443]
We are adding few fields from UI for test now mode and run once mode. 

We are using heartbeat fields api for ingesting those fields 

But we should add explicit mapping for those. 

So far i have identified following fields

`config_id`. This is a configId, essentially a kibana saved object id. This is being using in test now mode while adding/editing moniotrs.

`test_run_id` This is being used in Test now mode from monitor overview list.

`run_once` boolean field, which is being used in the uptime to filter out test runs from the results.

We will need to add these mappings in the heartbeat as well as in the synthetics integration package.

**Comment by dominiqueclarke** [comment]
This needs to be added to the Synthetics Integration and released to production before `run_once` will work in our tech preview clusters.

**Comment by dominiqueclarke** [comment]
@andrewvc @shahzad31 Do we need to add these mappings to beats as well? Seems to me that this is only applicable for the service.

**Comment by paulb-elastic** [comment]
This is done
