### ISSUE TITLE
[Monitor Management] Monitor Type drop down not selectable by mouse in Firefox

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#444]
Using the `main` branch (so, what will be `8.1.0`).

When using Firefox and attempting to select the type of monitor (TCP, ICMP etc.) from the Monitor Management, Add Monitor page, I cannot select anything with the mouse, as it remains on the default HTTP selection.  The only way I can select it, is to use the keyboard to scroll down and then press enter.

https://user-images.githubusercontent.com/70908889/151352177-4bb619fb-36b7-4cbb-a7f0-78a2973fedd7.mp4

Notes:
* This only happens in Firefox (I’m using version 95), it **is** working correctly in Chrome
* That this problem does NOT happen on the Integration UI, only on Monitor Management UI

Steps to reproduce:
* Using Firefox
  * Go to Uptime
  * Select **Monitor management**
  * Select **Add monitor**
  * Type a **Monitor name**
  * Select a **Monitor location**
  * Use the mouse to try and pick something other than `HTTP` from the **Monitor Type** drop down, and you cannot

**Comment by awahab07** [comment]
Should be fixed with #445

**Comment by paulb-elastic** [comment]
@awahab07 just cross referencing a comment to the drop down here, with the referenced PR: https://github.com/elastic/kibana/pull/125017#issuecomment-1033694893
