### ISSUE TITLE
[Monitor Management] Test Now progress and results often not visible in viewport

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#445]
When using the **Run test** option (added in https://github.com/elastic/uptime/issues/437) whilst adding a monitor (before saving it, to check it works), it’s often not possible to see the progress or results, in the viewport, so as a user, I don’t know anything is happening (in fact, I thought the button wasn’t working initially, until I randomly scrolled up).

The following video shows the UX running on my browser which is full screen on a 1920*1080 resolution screen, and there is only a small amount of the bottom/grey bar showing at the top of the screen, which I only notice now, I hadn't noticed it until I scrolled up:

https://user-images.githubusercontent.com/70908889/151362820-799550dd-4ad7-40c8-bdd4-46ef374123e2.mp4

Maybe it would be better to anchor the results to a more visible part of the screen, or have some other flyout or UI.

**Comment by shahzad31** [comment]
With current design, it should definitely auto scroll up once button is pressed.

**Comment by paulb-elastic** [comment]
To add some detail, it's behaving as shown in both Firefox and Chrome.
