### ISSUE TITLE
Migrate away from deprecated indexPattern Service

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#449]
Uptime requirements for handling https://github.com/elastic/kibana/issues/124063

More details to follow...

**Comment by paulb-elastic** [comment]
@shahzad31 to add more details here, including the User Experience app

**Comment by shahzad31** [comment]
closed by https://github.com/elastic/kibana/pull/130952 and https://github.com/elastic/kibana/pull/130949

**Comment by shahzad31** [comment]
Skipping post FF Testing
