### ISSUE TITLE
Enable single metric charts on exploratory view 

### ISSUE THREAD

**Issue by shahzad31** [elastic/uptime#455]
Lens allows metric visualisation where you can add a single metric to the chart, like average page load time value

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/3505601/153373698-8d767c41-fd1e-4b65-beb9-fddcd5360954.png">

we have many of those visualisations in user experience app, to get rid of UX app code from APM UI, we need to enable single metrics in exploratory view so that we can replace those in the user experience app

ticket is essentially https://github.com/elastic/uptime/issues/454 , if we don't enable single metric visualization in exploratory view.

**Comment by drewpost** [comment]
@shahzad31 does this mean we can't remove the code from APM until this is done? Is this a hard dependency?

cc @paulb-elastic

**Comment by shahzad31** [comment]
Yes, i think that's the path we want to take. Though we can also use asyncsearch directly to remove remaining code out of APM.
