### ISSUE TITLE
[Monitor Management] Add Monitor form becomes invalid before user interaction

### ISSUE THREAD

**Issue by awahab07** [elastic/uptime#456]
In Uptime -> Monitor Management, when user lands on Add Monitor page, the form starts with an invalid state. All required fields show validation error messages on start.
<img width="1134" alt="Screenshot 2022-02-15 at 12 09 45" src="https://user-images.githubusercontent.com/2748376/154051418-c593467e-431c-41b8-9fa5-c67764d0b506.png">

### AC
The form should only becomes invalid after user has interacted with it:
- A required field should only display validation error message when it has been interacted with.
- All required fields should display validation error messages if they are invalid and user tries to submit the form.

**Comment by shahzad31** [comment]
Tested on Edge-olbt, working as expected !!
