### ISSUE TITLE
Issues with Test Now in Monitor Management UI

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#457]
There seem to be some issues in the current **Test Now** feature in Monitor Management.

# Timeout / delay loading screenshots

On a multi step monitor, it seems that the screenshots are not initially loading (often they will load for later steps, but not the first ones).  The screenshots are there, as they can be seen if collapsing/expanding the result, or opening the result in a new tab.

![Video_2022-02-16_122620](https://user-images.githubusercontent.com/70908889/154264817-62388b69-752e-4349-b50d-cae6be5105ff.gif)

# Doesn’t handled failed journeys

When the script does not succeed, as in the following animation (where I’ve purposely included a failing step) the result window doesn’t seem to handle this properly.
* The overall test result is `COMPLETED` even though step 3 `Failed`
* I don’t mind that steps 4 to 6 show as skipped, but the UI seems to be continually attempting to load, as step 6 remains like this forever

![Video_2022-02-16_123206](https://user-images.githubusercontent.com/70908889/154265189-5d2cc1b8-92ff-4801-9eb4-14984ceefc0d.gif)

**Comment by shahzad31** [comment]
I am going to resolve few of these issues with new inline errors capabilities. Will update the issue accordingly

**Comment by shahzad31** [comment]
i haven't been able to reproduce the first issue.
