### ISSUE TITLE
Add error callout to bottom of FilterBar component

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#46]
**Is your feature request related to a problem? Please describe.**
It's really obscure when our implementation of `EuiSearchBar` fails to parse a user's KQL input.

**Describe the solution you'd like**
We should add an [`EuiCallout`](https://elastic.github.io/eui/#/display/callout) to the bottom of the FilterBar, as this would be a relatively simple addition and provide value to people trying to search.

**Describe alternatives you've considered**
We are planning to introduce the KueryBar to Uptime in the next release, so it seems like this may be unnecessary. If the KueryBar introduction is delayed we should implement this.

**Additional context**
The idea to implement this originated while addressing https://github.com/elastic/kibana/issues/36855.

**Comment by andrewvc** [comment]
++ to deferring this in lieu of the query bar.

**Comment by justinkambic** [comment]
@andrewvc and I just had a discussion and we feel that it's actually a bug. The reason is that there can be errors returned by the KQL parsing function provided by EUI (which we use today), and if the error isn't being displayed to the user then it's a bug.

In light of this, we should re-evaluate and see if we can add it as a bug fix for `7.2.0`, or at least in `7.2.1`.
