### ISSUE TITLE
[Public Beta] Add callout if fair usage policy is breached

### ISSUE THREAD

**Issue by shahzad31** [elastic/uptime#466]
In 8.2 we have enabled public beta for monitor management. 

In which user can request access to public beta, once user is in public beta, they will have to abide by the fair usage policy.

Since there will be no cost to run monitors in the service in this phase, we will enforce to make sure, there is limit.

AC's

Once an API is added in the service which will return if user has breached the fair usage policy.
In kibana we should show a callout to user indicating that they have already reached their limit.
And more runs aren't being scheduled.

Limit will reset after 24 hours.

**Comment by paulb-elastic** [comment]
Do we have a view on how this will be presented, in a toast, or some other way?

cc @drewpost @hbharding @liciavale

**Comment by shahzad31** [comment]
this was doen in https://github.com/elastic/kibana/pull/128770
