### ISSUE TITLE
[Elasticsearch] Add necessary `manage` privileges for synthetics indices to the `kibana_system` user to support ILM

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/uptime#467]
Related to https://github.com/elastic/uptime/issues/462

Fleet uses the internal `kibana_system` user to install integration package assets into Elasticsearch in order to support automatic upgrades of packages without end user intervention. To support , we'll need to add extra permissions for this user.

In particular, we must add the `manage` index privilege on all the indices being managed by the ILM policies for Elastic Synthetics, including:

- synthetics-http-*
- synthetics-icmp-*
- synthetics-tcp-*
- synthetics-browser-*
- synthetics-browser.network-*
- synthetics-browser.screenshot-*

Background: https://github.com/elastic/package-spec/issues/293
Example: https://github.com/elastic/elasticsearch/pull/81811

**Comment by shahzad31** [comment]
Since during testing lifecycle, it deleted data, we can this works so marking this as POST FF Testing succesfull.
