### ISSUE TITLE
Update the Enable Monitor Management links

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#468]
The _Enable Monitor Management_ page contains two URL links that need to be updated to the correct location for the Public Beta

![image](https://user-images.githubusercontent.com/70908889/161528390-a47d419a-c95b-4e77-8c05-b2d8e2042257.png)

ACs:
* @drewpost to confirm the details of the URL locations*
* Update the _Request access_ button to link to the correct location
  * Details in https://github.com/elastic/kibana/issues/128594
* Update the _Read the docs_ link to refer to the correct location
  * https://docs.google.com/document/d/1hkzFibu9LggPWXQqfbAd0mMlV75wCME7_BebXlEH-oI/

(* when we last spoke, @drewpost has details of how to use the service in an email, which should at the least be moved to a public Google doc).

**Comment by paulb-elastic** [comment]
Updated the AC with the _read the docs_ link (https://docs.google.com/document/d/1hkzFibu9LggPWXQqfbAd0mMlV75wCME7_BebXlEH-oI/)

**Comment by dominiqueclarke** [comment]
The request access link LGTM in production. Takes you to https://docs.google.com/forms/d/e/1FAIpQLSfWPWhpGmKzE8KteuRywVRqqKEhahG-494q8tIldZMp3xo2SQ/viewform

<img width="1008" alt="Screen Shot 2022-04-19 at 1 07 32 PM" src="https://user-images.githubusercontent.com/11356435/164058380-0f29f9a0-acef-4c7d-ae64-225d7ea7e3c9.png">
