### ISSUE TITLE
[Monitor Management] Update beta badge hover copy

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#470]
When hovering over the `Beta` badge on Monitor Management, the copy should be changed to reflect the limitations of the beta programme, more like what we have with the Synthetics Integration, like this:

![image](https://user-images.githubusercontent.com/70908889/162925566-1d42960f-1393-411e-a6cb-2732a9c4c95f.png)

If there is a standard for beta copy, use that.  Alternatively, use this:

> This is not recommended for use in production environments.

**Comment by bmorelli25** [comment]
The standard beta copy that we have is:

> This functionality is in beta and is subject to change. The design and code is less mature than official generally available features and is being provided as-is with no warranties. Beta features are not subject to the support service level agreement of official generally available features.
