### ISSUE TITLE
Deprecate Synthetics Integration and ZIP URLs

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#473]
With the introduction of the self-managed node integration (https://github.com/elastic/uptime/issues/441) and project based monitors (https://github.com/elastic/synthetics/issues/494), we need to clean up the previous beta implementations that will be superseded.

ACs:
* None of these should be done until both https://github.com/elastic/uptime/issues/441 and https://github.com/elastic/synthetics/issues/494 have been released
* Provide a migration mechanism for those using the existing `Synthetics Integration` (i.e. how to use the https://github.com/elastic/uptime/issues/441 instead)
* Deprecate the existing `Synthetics Integration`
* Deprecate Heartbeat’s ability to run `source, local` (i.e. ZIP URLs)
  * Note this will remove the need for https://github.com/elastic/beats/issues/28749
  * (when getting to this, consider if this should be split out to do at a later point, potentially keeping this capability for a bit longer, not as part of Synthetics going GA (i.e. still not supported), with a clear message that it will be removed in the near future)
* Update documentation
  * Existing documentation - refer to these being deprecated, and the new way of setting things up
  * Ensure there is documentation on how to set these up using the service, or the self-managed node integration
  * The _recommended way_ of setting up monitors must be clear in the Synthetics GA documentation (i.e. it must be clear how users should use the new features in place of the old ones)
  * Update repo examples such as those in https://github.com/elastic/synthetics/blob/main/examples/docker/heartbeat.docker.yml

**Comment by kazagz** [comment]
@paulb-elastic will this make `inline` the only option for running scripts? It won't be possible to run docker.elastic.co/beats/heartbeat with `source: local:` in `heartbeat.yml` file?

**Comment by paulb-elastic** [comment]
Hi @kazagz, [project based monitors](https://github.com/elastic/synthetics/issues/494) are going to be an improved solution that replaces ZIP URLs.

This will allow you to have externally configured user journeys (similar to how you have these currently as a ZIP URL) and `push` them to Kibana (either from the command line, or from a CI pipeline).

As part of this `push` you also configure where to run the test from and the frequency etc. (i.e. it makes the user journey a fully configured monitor).

If you want to run these monitors from your own self-managed locations, then https://github.com/elastic/uptime/issues/441 will provide this capability, using the [elastic-agent-complete](https://www.elastic.co/guide/en/fleet/current/elastic-agent-container.html) Docker image, having configured this new integration to run on your self-managed node(s).

**Comment by paulb-elastic** [comment]
Closed as covered in https://github.com/elastic/synthetics-dev/issues/124 and items in https://github.com/elastic/kibana/issues/137508
