### ISSUE TITLE
URL vs. ID link confusion

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#5]
Today, we have two links displayed on the monitors list table. One is the monitor's ID, the other is the URL that the monitor is checking. Clicking the ID will take you to the dedicated monitors view; the URL link will open a new tab with that URL present.

![image](https://user-images.githubusercontent.com/18429259/51989653-7a1ceb80-2475-11e9-9dd6-72a97ad6524d.png)

This presents an obvious usability concern. It's very easy to get confused and click the wrong thing. One proposal is to separate the two columns, de-prioritizing the URL to the right, and increasing the prominence of the ID like below:
![image](https://user-images.githubusercontent.com/18429259/51989794-c6682b80-2475-11e9-9d69-25084259a71f.png)

Additionally, it was suggested that we remove the link and just display the URL text, with some icon button to leave Kibana, like so:
![image](https://user-images.githubusercontent.com/18429259/51990336-ce749b00-2476-11e9-8688-e6d660a738ce.png)

**Comment by andrewvc** [comment]
Will be fixed by #72224

**Comment by justinkambic** [comment]
@andrewvc do you think we are ok to close this issue?

**Comment by andrewvc** [comment]
Yes
