### ISSUE TITLE
Handling Empty State for 7.3

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#51]
**Describe the bug**
The Uptime UI is currently not notifying the user of a missing index in some cases.

Today, the UI is relying on an ES call like `HEAD heartbeat-8*`, expecting that it will `404` if there are no indices matching the given pattern. However, this request gives a `200` always, even if no indices match that pattern. It requires a specific index name like `HEAD heartbeat-8.0.0` to return a `404`.

There are three cases we want to handle when evaluating whether or not we should show an empty prompt.

- No matching index: in this case the targeted index does not exist at all, and we should display an `EmptyPrompt` telling the user this. This is the state that caused the discovery of the bug.
- Matching index exists, but has no documents: in this case, the targeted index exists, but there are no data present. We should either:
  - display an `EmptyPrompt` with a different message, saying there are no documents (this is how the app has behaved in the past)
  - display a page with default empty states for all components. This should work fine as the components all handle this condition
- Matching index exists and it has documents: render the overview page's child components.

**To Reproduce**
1. Run a non-8.x version of Heartbeat (i.e. build from `7.x` branch) against a Kibana/ES `8.x`.
2. Load the Uptime UI
3. See the page like below:
![image](https://user-images.githubusercontent.com/18429259/60520217-00eb2400-9cb3-11e9-85bb-38c76eace983.png)
4. You can see that there is no `heartbeat-8*` index, yet the app does not inform the user of this.
![image](https://user-images.githubusercontent.com/18429259/60520197-f892e900-9cb2-11e9-9bff-3fa77f801b5d.png)

**Expected behavior**
The topic of discussion is how we want the app to handle this.
- When there is an index but no data, what do we want to show?
- When there is an index with data, but the user's filters return an empty set, what do we want to show?

**Debug logs**
N/A

**Comment by andrewvc** [comment]
I think this sounds good. I assume this will be solved with a `_count` request against `heartbeat-VERSION*`

**Comment by justinkambic** [comment]
Ok. Is it acceptable to infer the index's existence from the `_shards.total` and the doc count from the `count` field in the result set? Or is there a case where the index exists but can also have no shards?

**Comment by andrewvc** [comment]
Good question about shards. Yes, `> 0` shards indicates the existence of the index.

**Comment by justinkambic** [comment]
++ ok I will create an implementation issue and get to work on fixing this.

**Comment by andrewvc** [comment]
Fixed in #40194
