### ISSUE TITLE
Add most recent error message to monitor summaries on a per-check basis

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#53]
**Is your feature request related to a problem? Please describe.**
We introduced the concept of `MonitorSummaries` in 7.3.0. It's been noted that it is likely useful to have the most recent error message displayed in the list when an error has occurred.
![image](https://user-images.githubusercontent.com/18429259/60598845-6c98c400-9d7b-11e9-9727-b54edc541053.png)

**Describe the solution you'd like**
Show error messages for location-level checks.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by andrewvc** [comment]
This is complicated by the fact that scripted metric aggs cannot aggregate full text fields, which is what our errors are. We can solve this with top hits, but that will take more effort.

**Comment by andrewvc** [comment]
I do agree we should do this FYI

**Comment by justinkambic** [comment]
A thought, we have the monitor IDs and locations of each down check. We could always subsequently query for the monitor IDs and locations for any `down` check, the query should be pretty fast. I know we're already doing a lot of querying for this data as it is though, so it may not be a good enough solution.

**Comment by andrewvc** [comment]
Will be fixed in https://github.com/elastic/kibana/issues/44541 , closing as a dupe.
