### ISSUE TITLE
[docs] Create Uptime architecture diagram

### ISSUE THREAD

**Issue by bmorelli25** [elastic/uptime#57]
@formgeist created two lovely APM architecture diagrams in https://github.com/elastic/apm-server/issues/2117:

![](https://user-images.githubusercontent.com/4104278/56665497-75e62000-66aa-11e9-9232-70342de96baf.png)

![](https://user-images.githubusercontent.com/4104278/56665506-7b436a80-66aa-11e9-81e1-8b20537d729c.png)

I'd like to have something similar created for Uptime so that @Titch990 or I can add it to the documenation on this page: https://github.com/elastic/kibana/pull/40566/files#diff-8b72ff6d295eda2b92564fb350a61314R10

Not sure who to tag. Perhaps something for @katrin-freihofner?

**Comment by andrewvc** [comment]
This is a great idea. I'd like to be a part of the process here. @katrin-freihofner I'll put a meeting on your calendar to discuss this.

**Comment by Titch990** [comment]
Sounds good to me!

**Comment by andrewvc** [comment]
Some initial ASCII ART ideas for the diagrams:

```
Diag Ideas


***********************
* Simple
-----------------------

          Ping              Docs
Service <------> Heartbeat ------> [ Elasticsearch -> Uptime UI ]

**********************
* Multiple Locations
----------------------

            Ping
          /------- Heartbeat (us-east)--\   Docs
Service <                                 -------> [ Elasticsearch -> Uptime UI ]
          \------- Heartbeat (us-west)--/
           Ping
**********************
```

**Comment by katrin-freihofner** [comment]
@andrewvc @Titch990 my sketches:  
![single-location](https://user-images.githubusercontent.com/20965076/62142131-0b1e3380-b2ee-11e9-9f8b-d8134f4ea458.jpg)
![multi-location](https://user-images.githubusercontent.com/20965076/62142133-0b1e3380-b2ee-11e9-80ec-15ae9654e01f.jpg)

Just let me know if I interpreted your messages correctly. Thank you.

**Comment by andrewvc** [comment]
@katrin-freihofner I think that's a great start.

In the future we should add a discussion about how to do it within a single datacenter. My thinking is it'd look something like:


```
--------------- Webservers ------------
- |Server 1| - |Server 2| - |Server 3|
-------^-----------^-------------^-----
       \           |            /
        \          |          /
         \         |        /
          --------------------
          | Heartbeat Server |
          --------------------
```

We can have that accompany additional copy stating something like what's below. I don't think we need diagrams for all the scenarios listed below, but I'm thinking I will open a PR up to add the below copy. @Titch990 what do you think in terms of whether additional diagrams would add more, or start to detract at some point.

> Heartbeat is generally run as a centralized service within a datacenter. While it is possible to run it as a separate "sidecar" process paired with each process being monitored, it is best to run Heartbeat from a central place within or even outside your datacenter. Doing so ensures you will still be able to see monitoring data in the event of an overloaded, disconnected, or otherwise malfunctioning server. 
> 
> For further redundancy, you may want to deploy multiple Heartbeats across geographic and/or network boundaries to provide more data. [Specify Heartbeat's observer geo options](https://www.elastic.co/guide/en/beats/heartbeat/7.3/configuration-observer-options.html) to do so. Some examples might be:
> * Say you have a site served from a global CDN. You may want to have multiple heartbeats at different data-centers around the world checking to see if your site is reachable via local CDN points of presence. 
> * Imagine a service within a single data center that is accessed across multiple VPNs. You might want a heartbeat instance within the VPN the service operates from, and another within an additional VPN users access the server from. Having both will help pinpoint network errors in the event of an outage.
> Consider a single service running primarily in a datacenter on the US east coast, with a hot failover located in a US west coast datacenter. It would make sense to run a Heartbeat instance on each checking both its local copy of the service *and* its counterpart across the country. You would have two monitors in each region, one for the local service, one for the remote. In the event of a datacenter failure it would be immediately obvious if the service had a connectivity issue to the outside world or an internal failure by examining which Heartbeats could see the service as up.

**Comment by Titch990** [comment]
@katrin-freihofner Looks great to me. I'm not an exert in the area of Uptime/Heartbeat yet, but images certainly make things clearer to me too! @andrewvc If I understand correctly, you're saying there are other possible configurations too? In that case, it would be useful to add a few other common examples. At this stage, I'll leave it to you to determine which other scenarios should be mentioned because they are common/helpful/otherwise interesting.

**Comment by katrin-freihofner** [comment]
@andrewvc and @Titch990 as discussed:
![uptime-single-location-diagram](https://user-images.githubusercontent.com/20965076/62443541-75562e80-b75b-11e9-9e48-01b5d94d27be.png)
![uptime-multi-location-diagram](https://user-images.githubusercontent.com/20965076/62443542-75562e80-b75b-11e9-90b5-8fbe7a6b534e.png)

**Comment by andrewvc** [comment]
Looks great @katrin-freihofner , I think we can merge these into the docs.

**Comment by bmorelli25** [comment]
I don't want this to get forgotten about. Is there an issue open for adding this to the docs? Or should we reopen this one?

**Comment by katrin-freihofner** [comment]
@bmorelli25 I though this is the design issue - I wasn't aware that there is no follow-up. Let's reopen it. cc @Titch990

**Comment by Titch990** [comment]
@bmorelli25 @katrin-freihofner. Not forgotten yet! I was planning to open a new issue today to add this to the docs.  But since this has been reopened, I've grabbed it instead.

@katrin-freihofner Do you have a PNG of the graphic for me to include in the docs?

@bmorelli25 @katrin-freihofner Where is the source file stored for this graphic, so it's available if we need changes made in the future? Do we store it with the docs, or elsewhere?

**Comment by katrin-freihofner** [comment]
@Titch990 here is the link to the PNGs https://drive.google.com/drive/folders/1YcbQu8S07nwqGqIzNJvduczW17DPZEQ3?usp=sharing
- the design files are stored in Abstract.

**Comment by andrewvc** [comment]
I've also added the doc changes I recommended in a new PR here: https://github.com/elastic/kibana/pull/43028

**Comment by Titch990** [comment]
All done!
