### ISSUE TITLE
[Design] Improve monitor summaries visualization

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#59]
**Is your feature request related to a problem? Please describe.**
The current display for monitor summaries is not very nice. There is a lot of space left that we could utilize. The data is tabular so having headings for each column would also be nice.

Today it's using an `EuiFlexGrid` to express the data. If we were to switch to a table, we'd have a table within a table.

**Describe the solution you'd like**
A way to better utilize whitespace within the table. We may be able to show additional data within the drawer.

**Describe alternatives you've considered**
We've considered nesting a custom table element inside of here, which may ultimately be the best solution. We could attempt to show additional information if there is container-related data or additional performance info available at the check-level.

**Additional context**
![image](https://user-images.githubusercontent.com/18429259/60999708-ca07b480-a329-11e9-829f-bea67e6f8ee3.png)

**Comment by justinkambic** [comment]
cc @katrin-freihofner @alvarolobato

**Comment by katrin-freihofner** [comment]
What do you think about something like this:
![table](https://user-images.githubusercontent.com/20965076/61644212-940ced80-aca4-11e9-8950-824b4477274a.jpg)

and for smaller screens we would need to rearrange like this:
![mobile-version](https://user-images.githubusercontent.com/20965076/61644199-8ce5df80-aca4-11e9-966c-a9232130baa7.jpg)

**Comment by katrin-freihofner** [comment]
High-fidelity version:
<img width="1358" alt="Screenshot 2019-07-23 at 14 42 46" src="https://user-images.githubusercontent.com/20965076/61713162-34701a00-ad58-11e9-8b75-ff1938f8c651.png">

**Comment by katrin-freihofner** [comment]
Update with latest version:
![00-overview](https://user-images.githubusercontent.com/20965076/62128289-65aa9600-b2d4-11e9-8972-70dcc9556bdf.png)
@andrewvc

**Comment by andrewvc** [comment]
Wow, I absolutely love this new layout. Looks so much better in so many ways.

To answer your questions:

1. Yes, I think the URL is still good to show prominently. The first thing many admins will do will click on the URL to see if it's down on their workstation as well to start diagnosing the problem.
2. +1 on adding the solutions icons

**Comment by andrewvc** [comment]
One other thought, I think we should incorporate geo in a more prominent way, perhaps with a mini map? WDYT about halving the `Number of Pings` and making it a 3 column layout on top with a mini map in there somewhere?

Thinking more about the whole map idea, I've been thinking that we may be better off with a textual representation of geo, just a simple table. The rationale there is that you may have two heartbeats at the same, or very similar geo coordinates, that are logically very separate. Imagine two datacenters within a city, or two heartbeats in different VPCs within one datacenter.

Maybe we should just stick with a simple table layout like so: WDYT @katrin-freihofner / @tbragin ?

| Location | Up | Down | Mixed |
|----------|----|------|-------|
| nyc-dc1  | 20 | 10   | 0     |
| nyc-dc2  | 30 | 0    | 0     |
| lax-dc1  | 30 | 0    | 0     |

**Comment by andrewvc** [comment]
Thinking about it further we could also just show each location as `up/down/mixed` to be more compact. You could click on a location to filter by it.

**Comment by katrin-freihofner** [comment]
@andrewvc do you mean something like this:
![IMG_20190805_134929](https://user-images.githubusercontent.com/20965076/62462728-689bff80-b788-11e9-9ef7-5aa6291de445.jpg)

**Comment by andrewvc** [comment]
@katrin-freihofner yes-ish. I'm worried about the mixed state, though it is uncommon. One idea is we could flip it and say `30/30 up`. On the one hand I like the number being the number of things with problems, that's probably the number people will focus on, and in my proposal here that makes people do subtraction "11/30 up means 29 are down". However, the advantage of listing the number up is that we don't have to say `down or mixed` which is awkward. 

The final thought is maybe we just get rid of mixed and call it down. @roncohen @shahzad31 @justinkambic  @tbragin  what are your thoughts there? The `mixed` state is relatively new, and is uncommon in most setups, so we can remove it. We could simplify to a simple down vs. up dichotomy, only surfacing subtle combination states in the detail view.

This is a bit tricky, picking the right level of detail to show at each widget. We want to find the right balance of detail and clarity. Right now we may be erring on the side of detail when clarity is what's desirable.

**Comment by katrin-freihofner** [comment]
@andrewvc, I have to admit, I'm also struggling with the warning state. And I'm not sure which use case the location list is solving. In the meantime I got great feedback from @hbharding and incorporated parts of it that already in the mockups - I think they are much better now. 

One of his comments was regarding the timeline in the expandable row and details page: the coloured sections could become very tiny if the shown timeframe is very long. - what is your opinion on that?


These are the updated versions:
![00-overview](https://user-images.githubusercontent.com/20965076/62538227-92b9f400-b852-11e9-9355-473aea89fbcd.png)
![01-details](https://user-images.githubusercontent.com/20965076/62538231-96e61180-b852-11e9-8639-ca78307a92e6.png)

**Comment by katrin-freihofner** [comment]
I'm going to close this as we are already working on a redesign.
