### ISSUE TITLE
[Feature request] Provide a way to configure the Monitor Status table on the Uptime page to add/remove extra fields 

### ISSUE THREAD

**Issue by kunisen** [elastic/uptime#61]
**Is your feature request related to a problem? Please describe.**
Hi, currently it looks like the fields on the Monitor Status table on the Uptime page is not configurable.
I would like to raise a feature request to configure the Monitor Status table on the Uptime page to add/remove extra fields 
(e.g. names, tags, etc).

**Comment by andrewvc** [comment]
Does the `name` field in heartbeat work sufficiently here?

If not, can you describe this in more detail? Would tags be sufficient? Would key value pairs be preferable? 

Additionally, can you describe the use case behind this request?

**Comment by andrewvc** [comment]
I'm going to close this for two reasons:

1. Lack of response
2. I think we'll go with something more structured like a 'tags' or 'groups' feature or similar. I think this will cover most similar use cases.
