### ISSUE TITLE
Type Elasticsearch responses

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#62]
**Is your feature request related to a problem? Please describe.**
Today we have many Elasticsearch queries and they are not typed. Elasticsearch responses and requests are typed in Kibana; we should type the aggregations and results we expect and reduce our reliance on lodash `get` calls while increasing our type descriptions.

**Describe the solution you'd like**
We should describe the data we expect to receive from our Elasticsearch queries and supply those descriptions to the generic interfaces defined in ES where possible.

**Describe alternatives you've considered**
N/A

**Comment by andrewvc** [comment]
We'll do this slowly as we go, so this can close.
