### ISSUE TITLE
[META] Core Uptime Alerting

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#64]
Uptime alerting implementation:

- [x] Design Issue https://github.com/elastic/uptime/issues/102
- [x] Kibana UI Implementation https://github.com/elastic/kibana/issues/56196

Initial alerting support for queries matching the following DSL.

```
WHEN ANY PING MATCHING [kql]
IS [status] MORE THAN [numtimes] times 
WITHIN [timerange]
IN [location option]
```

an example is below

```
WHEN ANY PING MATCHING “monitor.name:customer-site”
IS down MORE THAN 2 times 
WITHIN Last 5 minutes
IN any location
```

Valid values for the various fields are:

* **kql**: Any valid KQL string. Initial value copied from overview page.
* **status**: Dropdown select of either 'up' or 'down'
* **numtimes**: Numeric field only allowing positive ints.
* **timerange**: Dropdown allowing [15s, 30s, 1m, 3m, 5m]
* **location option**: Dropdown consisting of all locations within the current query scope + "Any single location". The "Any single location" option will look for the given number of statuses being met or exceeded in the results from any single location.

**Comment by justinkambic** [comment]
A prerequisite to this discussion might be agreeing on the final format we plan to use for our data as well. If we're able to track state changes in a fast and reliable way it becomes much simpler to trigger alerts.

**Comment by shahzad31** [comment]
already done
