### ISSUE TITLE
Display TLS certificate expiration on detail pages

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#70]
We should display the TLS certificate expiration and starting validity dates on monitor detail pages. Furthermore, if the certificate is about to expire we should show a warning of some sort. If it is expired we should show the error clearly.

We should follow @katrin-freihofner 's mock below in building this:
![image](https://user-images.githubusercontent.com/131427/62816304-56a0c080-baea-11e9-89e7-dc40941b55f8.png)

**Comment by katrin-freihofner** [comment]
I think in the case where the certificate is expired, we could emphasise this with a callout https://elastic.github.io/eui/#/display/callout. But I would keep it very simple as long as it is information only (not expired).
