### ISSUE TITLE
Logical groups for uptime

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#72]
As we move toward alerting it'd be nice to be able to logically group monitors. You may not want individual alerts for each webserver, but rather alerts for the group as a whole with summarized data.

Related: https://github.com/elastic/uptime/issues/61

**Comment by justinkambic** [comment]
Does `tags` give us this without having to implement something custom? I'd imagine for alerting we will be able to specify tags of interest, and we had [another issue](https://github.com/elastic/uptime/issues/81) already looking to increase our reliance on tags for filtering. Plus, we want to [add a tags list](https://github.com/elastic/uptime/issues/84) to the UI to make filtering simpler.

**Comment by andrewvc** [comment]
I'm glad to close this in favor of tags for now.
