### ISSUE TITLE
Explore better use of location in UI

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#73]
We now integrate location info in more places in the app, but we could probably use it more thoroughly elsewhere.

Some initial ideas:

1. A map on the overview page showing the locations of all active heartbeats
2. A new page with charts per location showing up/down status on a histogram, letting users see if everything monitored by a given location is down.

**Comment by katrin-freihofner** [comment]
For example:
<img width="685" alt="Screenshot 2019-08-12 at 15 27 27" src="https://user-images.githubusercontent.com/20965076/62868351-b8913e00-bd15-11e9-88eb-234b39651534.png">
