### ISSUE TITLE
Improving state granularity

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#75]
The main goal of Uptime is to tell you when your site is up or down, however, there are many intermediate states, where it may be up for some, or down for others, or flapping etc.

Currently we report three states:

1. Up
2. Mixed (when some subset of DNS resolved IPs are up but others are down)
3. Down

In the future, with timelines, we may have even more subtle states like flapping (state isn't up consistently), or unstable (too many state transitions to compute within a window). There is a trade-off here between detail and simplicity/clarity. 

This is a lot for users to absorb. This issue proposes that we should simplify status to "up/down" across the app, making the UI only show things in a binary up/down state. We would no longer have a 'yellow' status. We should add a new `outage_reasons` field to API calls for monitors that lists the outage criteria it matches, that would be one or more of the following

* *flapping*: Monitor is not staying consistently up as defined by heartbeat flapping threshold
* *ip-mixed* some resolved IPs down
* *geo-mixed* some geo-locations down
* *unstable*: Only in timelines. Used for blocks of time where too many state transitions occur to enumerate individually.

From a UI perspective we would generally only surface this level of detail on monitor detail pages (although maybe there'd be a way to show it on the overview page without too much clutter).

This might get confusing with the existing `Error Type` column we have, but maybe we can combine all this into a human readable piece of text, like: *Endpoint is down in some geo locations (us-east) and flapping*, if the `outage_reasons` field was `flapping,geo-mixed`.

There's no specific reason I can think of for a user to sort / aggregate on these values vs. more generally on up/down.

Would love feedback and alternate takes on this proposal. @roncohen @justinkambic @katrin-freihofner @shahzad31  @tbragin

**Comment by justinkambic** [comment]
> From a UI perspective we would generally only surface this level of detail on monitor detail pages (although maybe there'd be a way to show it on the overview page without too much clutter).

From my side, I like the idea of this added simplicity. I do think we can find a subtle way of including _some_ outage information if we went this route. A tooltip (displaying the latest `outage_reason`'s name) when hovering over a monitor's health indicator for example, or designating a space where the latest outage reason can be shown in the summary drawer.

The idea of telling people quickly what is down, vs. requiring the user to understand a growing set of potential states, seems nicer to me. It is easy to get off track and excited by the possibility of designing and writing code to show a myriad of states, it's important to remember that for most of our users, anything less than a small subset of `down` monitors represents a critical outage problem, and they're probably most interested in having that info available at a glance.

**Comment by andrewvc** [comment]
We've decided in a meeting to only show up/down on the main page, and potentially more states on the details page in the future. Closing this issue.
