### ISSUE TITLE
Monitor page doesn't fail gracefully when it should

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#8]
This just occurred to me when I started up the app by refreshing a stale _Monitor page_ URL that still had a `6.7`-style ID specified in the query string. Obviously this ID was no longer present in my cluster because I was running `master` versions of the stack.

![image](https://user-images.githubusercontent.com/18429259/52800714-58f9f480-304a-11e9-8ad7-dc602e832dd2.png)

This is something I think we could fix for `6.7.0`/`7.0`. We can display a simple `EuiEmptyPrompt` like we do for data-related issues on the `Overview page`. That said.. it could be interpreted as a feature, normal operation of the application should not cause this state to occur.

**Comment by andrewvc** [comment]
@dov0211 would you be able to help us out with a mock here? Once we have that we should move this to a Kibana issue.

**Comment by justinkambic** [comment]
This issue is referencing a very outdated version of the UI and we are ok to close it for now.
