### ISSUE TITLE
SSH Type Polling

### ISSUE THREAD

**Issue by robgil** [elastic/uptime#80]
**Is your feature request related to a problem? Please describe.**
There are a lot of cases where a service is not publishing a public port nor is accessible via other means. Some examples of this would be checking if processes are running that are not publicly accessible or don't have a listening port. 

The simplest example would be something like crond.

**Describe the solution you'd like**
A way to run a command via ssh and do string checks to define whether the service is healthy. It would also be nice to be able to parse the output of a command to ingest uptime statistics around a particular process.

Ex. `ps -ef|grep crond|grep -v grep` If there is output, its running, if not its down.

This should check for multiple processes also and have a configurable count of what _should_ be running. So if 2 cron daemons are running, that's bad.

Another example is networking devices.

You may want to check if BGP peers are established.

via ssh you might run a command similar to the following

`show ip bgp <neighbor>|grep ESTABLISHED`. If nothing returns, the peer is down.

**Describe alternatives you've considered**
Most other monitoring systems provide a method of using ssh for polling

**Additional context**
In cloud we will be working toward doing more internal monitoring of hosts via the internal network. Not all services are exposed publicly. Sometimes its nice to ssh and hit the docker socket to see if docker is indeed responding. In the past we've had issues where docker stopped responding (now fixed via kernel patch). We needed to identify these hosts quickly and vacate the deployments on them. We ended up running this as an ansible job from rundeck. It wasn't the most friendly solution but did the job. It also didn't log to ES although could be configured to do so.

**Comment by robgil** [comment]
I should also note that in the BGP example, SNMP polling would work as well if the data was exposed via SNMP.

**Comment by andrewvc** [comment]
This is a pretty nifty idea. It would be a substantial change in that this would not be a protocol-based monitor per-se. I'd love to hear an opinion on this from @tbragin and @roncohen  in particular.

**Comment by andrewvc** [comment]
I'll just add that I'm on the fence on this. I'm not sure heartbeat should try and be expansive in the protocols it supports. The current ICMP/TCP/HTTP set feels very tightly focused, but loosening that could be a slippery slope, and I worry about maintainability.

**Comment by justinkambic** [comment]
I think that this is a cool idea, but that it is kind of far off in terms of where our current focus is. I almost wonder if long-term we could consider providing a mechanism by which folks can implement their own "plugins" for generating heartbeat monitor docs for custom cases such as this.

**Comment by andrewvc** [comment]
Hi @robgil after discussing this with the team, this would widen the scope of the project more than we can currently handle. If you'd like you could still accomplish this by coding up a web service with an HTTP endpoint that does this, then using heartbeat to ping that.

We're going to close this now because we don't think we'll do this in the near to medium term. Closing issues helps us keep our issue tracking clean, but doesn't mean we won't reconsider this at a future point.

Thanks for the well written suggestion!

**Comment by robgil** [comment]
Thanks for the consideration @andrewvc.

**Comment by RobDTech** [comment]
How about allowing users to plug in modules?
