### ISSUE TITLE
Autocomplete for custom fields

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#82]
**Is your feature request related to a problem? Please describe.**
We're adding the ability to use the Kuery Bar and its autocomplete goodness in `7.5.0`.

![Sep-19-2019 13-55-42](https://user-images.githubusercontent.com/18429259/65268480-3c90cf80-dae5-11e9-8e15-67b06f5bf719.gif)

One drawback to the current implementation is the mapping utilized for this functionality is static and controlled by us. If users specify custom fields for their mappings, they won't be displayed, which can make the search bar more painful to use:

![Sep-19-2019 14-00-05](https://user-images.githubusercontent.com/18429259/65268925-25061680-dae6-11e9-9df1-466cf759c9d1.gif)

**Describe the solution you'd like**
We need a good way of allowing our users to persist the mapping they'd like to load. This is a topic that's been examined from a lot of angles by many folks, but even a naive implementation could add value for certain users. We're already using the Saved Objects API to maintain a custom index pattern, we could create a JSON schema and allow users to store the setting for the targeted index mapping using our existing infrastructure.

**Describe alternatives you've considered**
There's a long list of other proposals, and ideally in the future we'd utilize Fleet to accomplish this, but for the time being we can probably provide this limited functionality, and do it in a way that it's easy to replace when more robust solutions are ready.

**Additional context**
I'm creating this issue as initiative driven by [feedback from a user on our forums](https://discuss.elastic.co/t/missing-data-when-using-using-fields-and-tags-in-uptime-7-3-0/199460).

**Comment by andrewvc** [comment]
Reading through the linked issue, I think the ultimate solution here is for us to support arbitrary metadata through k/v pairs. We'd implement this probably as nested documents, with a key/value property (both strings). This could be supported directly in heartbeat, something like:

```yaml
- type: http
  urls: ["http://elastic.co"]
  metadata:
    mykey: myvalue
    multikey: ["multi", "value"]
```

The advantage here is that the user wouldn't need to deal with custom ES mappings at all.

This might be a bit awkward to support in the kuery bar, though it's doable (it'd need to gain support for nested documents). It'd probably be easier to add a filter widget that had first class support for this use case.

**Comment by justinkambic** [comment]
I'm fine with using a filter widget. We could employ a combo box or some other EUI component that allows us to find the fields and display those the user has selected. We will probably want some design help on the implications for the layout.

**Comment by andrewvc** [comment]
Great, then I'll close this issue out. Thanks for writing it up however!
