### ISSUE TITLE
Stop dropping current bucket before it's filled

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#83]
Presently, we drop the latest bucket from our visualizations. The thinking at the time of implementation was that an "unfinished" bucket results in a misleading visualization, where the most recent data looks like it has changed in some significant way when in reality we are simply waiting for the bucket to fill up and and flow into the next one.

This is particularly unsettling in newly-started deployments of Heartbeat + Uptime UI because the chart is simply empty, like below:
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/18429259/65329925-7fa37f00-db87-11e9-800b-be1558a7e469.png">

Another case where this happens is if you set the date range domain to too wide of a size. For example, if there are 3 weeks' worth of data accumulated in Heartbeat indices, and the domain is set to `last three years`, we'd end up with a blank chart.

The tradeoff is, like mentioned before, that the current bucket can appear unsettling to the user. Perhaps it would be worthwhile to devise a way that we can display to the user that the current bucket is in an intermediate state. There is precedence for dropping the latest bucket in other areas of Kibana, so whichever solution we choose requires careful consideration.

cc @katrin-freihofner @shahzad31 @andrewvc

**Comment by katrin-freihofner** [comment]
<img width="1532" alt="Screenshot 2019-09-23 at 11 15 25" src="https://user-images.githubusercontent.com/20965076/65414185-7880a900-ddf3-11e9-92d5-aefdc18fe86b.png">
Could we calculate an expected value via ML and draw that in the chart?

**Comment by andrewvc** [comment]
I think we should just draw it. If you use any monitoring software you're pretty used to charts having a short right-most bucket.

I like the ML @katrin-freihofner , but I'm not sure the value it'd add would be worth the cost. Also, it's not a common pattern, I assume users would be confused by it.

@grabowskit WDYT?

**Comment by justinkambic** [comment]
It's a really good and interesting solution to the problem! We don't really have an infrastructure built around ML to leverage it like that today, so it might be really complex for minimal gain.

**Comment by grabowskit** [comment]
I agree... I think it could cause confusion and might not be worth the cost.  I'm pretty use to the short right-most bucket and I think that is consistent even in how ML represents the "current" bucket span.

**Comment by justinkambic** [comment]
Just drawing whatever is accumulated is definitely the simplest and cheapest solution to this issue.
