### ISSUE TITLE
Provide tag filtering dropdown

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#84]
**Is your feature request related to a problem? Please describe.**
We had recently discussed with a user the lack of support for tag filtering in our KueryBar implementation. We think it would be useful to add tags to the list of items users can select from in the UI's filter dropdowns.

**Describe the solution you'd like**
Add additional filter dropdown and server-side fetching code for any tags in the index, and provide this to make it quick for users to filter by one or more tags.

**Describe alternatives you've considered**
It'd be a new addition to an existing feature so there aren't really alternatives; we'd either do this or not.

**Additional context**
N/A

**Comment by andrewvc** [comment]
This is a great idea, I think it'd be a quick easy win.

The user has a pretty common setup that is a good example of how you'd use this. They have sites in either `production`, or `staging`. Being able to quickly filter by either makes a ton of sense.

**Comment by justinkambic** [comment]
From a design perspective we'd just add another dropdown to the existing list, with some additional hookup code on the backend. Given the simplicity, are you ok with moving forward to an implementation issue?

cc @shahzad31

**Comment by andrewvc** [comment]
Pinging @katrin-freihofner on this for design considerations

**Comment by justinkambic** [comment]
Do we think it'd be ok to add this so the functionality is there, and we can roll any design considerations into the future of the app's filtering?

**Comment by katrin-freihofner** [comment]
Quick question: Do we want to use this only for filtering the environment? In APM we have something like this:
<img width="430" alt="Screenshot 2019-10-04 at 11 25 15" src="https://user-images.githubusercontent.com/20965076/66197027-d5088180-e699-11e9-82c1-48eabf9142a6.png">
And yes @justinkambic I think it would be ok to add the functionality and combine it's design with other filter considerations.

**Comment by justinkambic** [comment]
Tags are user-defined so they aren't specific to the environment.

**Comment by justinkambic** [comment]
@andrewvc I'm assuming ECS supports this, but I can't find the appropriate field. I'm thinking we should create a separate issue to add this.

**Comment by andrewvc** [comment]
@justinkambic I don't believe ECS supports this. To be clear, I'm not saying that we should add the environment dropdown, I'm saying it'd be a separate issue that would be part of a larger change across observability. I don't think we need to do anything about this here for now.

**Comment by tbragin** [comment]
@andrewvc I agree a dedicated environment filter across Observability is probably a separate issue. Worthwhile effort, and if we go down that path, it'd make sense to standardize the field we use.

**Comment by justinkambic** [comment]
Regarding tags - are we ok to add this filter group to our existing filters at any time, with the understanding that future changes to Uptime's filtering UX will wrap this addition?

**Comment by katrin-freihofner** [comment]
From my perspective, this is fine, we can add it to our existing filters. 👍

**Comment by justinkambic** [comment]
Another concern we are addressing in the patch associated with this enhancement is allowing our filters to cross-apply to each other. We can't simply `AND` everything because there could be multiple options the user wants to filter on.

Example:
```json
{
  "port": [80, 443],
  "location": ["fair banks", "berlin", "tokyo"],
  "scheme": ["http", "https"]
}
```

In the above list of filters, if the user wants to apply port 80, they'd lose the option to apply the port 443 today. We're looking to amend the overview filters query so that the available filters aren't impacted when a sibling is selected. It's possible that this update to the query should be tracked in a separate issue.
