### ISSUE TITLE
Down sites listing does not tally 

### ISSUE THREAD

**Issue by lukelee1987** [elastic/uptime#88]
**Describe the bug**
the summary and the listing of sites went down does not tally 

**To Reproduce**
 heartbeat.config.monitors:
  3   path: ${path.config}/monitors.d/*.yml
  4   reload.enabled: true
  5   reload.period: 5s
  6
  7 max_retries: 100
  8
  9 heartbeat.monitors:
 10 - type: icmp
 11   schedule: '* 1 * * * * *'
 12   hosts: ["10.0.106.144"]
 13   ipv4: true
 14   ipv6: true
 15   mode: any
 16   timeout: 16s
 17   wait: 1s
 18 - type: tcp
 19   schedule: '@every 1800s'
 20   hosts: ["10.0.106.144:9200"]
 21   mode: any
 22
 23 setup.dashboards.enabled: false
 24
 25 setup.template.settings:
 26   index.number_of_shards: 1
 27   index.codec: best_compression
 28   index.number_of_replicas: 0

**Expected behavior**
the number of server down will be the same as the number of row of records. 

**Debug logs**
NA

![image](https://user-images.githubusercontent.com/29053050/66363027-6425da00-e9b7-11e9-897d-714c83a36b18.png)

**Comment by andrewvc** [comment]
Thanks for the report! 

This should be fixed with https://github.com/elastic/kibana/pull/42933 which will be released in version 7.5.0 . Sorry for the poor experience here, a fix is coming!

**Comment by lukelee1987** [comment]
Thank you for your kind reply and updates.

**Comment by lukelee1987** [comment]
> Thanks for the report!
> 
> This should be fixed with [elastic/kibana#42933](https://github.com/elastic/kibana/pull/42933) which will be released in version 7.5.0 . Sorry for the poor experience here, a fix is coming!

Dear Andrew, may I know will it be possible that you guys can release a patch rather than an upgrade to the entire ELKS?  We are facing this issue whereby one part of the system is having bug and causing a major system upgrade, thereafter will cause other parts to break.

**Comment by andrewvc** [comment]
@lukelee1987 unfortunately the scope of this change is large and does change some behavior, so we feel that it is better suited for a minor release than a patch level release.
