### ISSUE TITLE
"Monitor duration" panel doesn't show data for last 1.5 hours

### ISSUE THREAD

**Issue by SlavikCA** [elastic/uptime#93]
**Describe the bug**
"Monitor duration" panel doesn't show data for last 1.5 hours

**To Reproduce**
I have this monitor:
```
- type: http
  id: "http-jabfloors.slavikf.com"
  name: "http://jabfloors.slavikf.com"
  urls: [        "http://jabfloors.slavikf.com:8000" ]
  schedule: '@every 1m'
  timeout: 30s
  check.request.method: GET
  check.response.status: 200
  check.response.body: "jabfloors"
```
As you can see it probes every minute.
Looking at the raw data - It work, as expected.
The issue is that "Monitor duration" panel doesn't show data for last 1.5 hours, as you can see on this screenshot:
![Screen Shot 2019-10-11 at 12 27 52 PM](https://user-images.githubusercontent.com/6293679/66679447-0ac1e300-ec23-11e9-9819-5c60b93d5aa1.jpg)

On screenshot:
- current time is 12:27pm,
- Looking at the "History" - last few pings are fine, ok
- but "Monitor duration" data goes only to 11am.
- "Pings over time" is little bit better - it goes to 12pm.

I didn't capture the most problematic screenshot, but around 12pm, I had situation when last few pings (according to History were ok), but "Monitor Duration" ended high above, like it still failing.

**Expected behavior**
Expecting, that "Monitor duration" and "Pings over time" would have latest timepoint on the right showing actual latest state.
Latest (current) state is very important to understand current state of the system.

**Environment**
- ELK 7.4 running in the Docker.

**Comment by SlavikCA** [comment]
Also, as you can see on the screenshot, that data on the screen is for "Last 2 days".

If I switch to "Last 2 hours" - I will see last few minutes. It will not miss last 1.5 hours. But it will miss last few minutes.

So, I would still say: the latest data point on all panels are most important data and needs to be rendered.

**Comment by SlavikCA** [comment]
One more example:
- one of my site just went down
- you can see, that it is down in the "History", as expected
- But neither "Monitor duration", not "Pings over time" shows any failure. Because these panel doesn't show latest samples. Expected result: every panel shall show latest sample.

![KibanaUptime](https://user-images.githubusercontent.com/6293679/66706466-c1879700-ece7-11e9-8029-9137c1b94e60.png)

**Comment by andrewvc** [comment]
Tested the fix in https://github.com/elastic/kibana/pull/48157 , which wound up solving this.
