### ISSUE TITLE
Update messaging for zero down monitors

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#95]
**Is your feature request related to a problem? Please describe.**
We recently updated the messaging for down monitors on our overview page. It doesn't look the greatest if there are *no* down monitors though:

![image](https://user-images.githubusercontent.com/18429259/66850248-6c958c00-ef46-11e9-8300-ca4505bf6019.png)

**Describe the solution you'd like**
Simply update the messaging to give a more concise and tailored heading:
![image](https://user-images.githubusercontent.com/18429259/66850843-98654180-ef47-11e9-9586-ce20def34a69.png)

**Describe alternatives you've considered**
We have discussed in the past creating a default viz for the case where *no* monitors are down. This might be worth revisiting for this component. We may also want to hide the *down* legend row.

**Additional context**
N/A

**Comment by katrin-freihofner** [comment]
I think we should also consider adding the green checkmark if all monitors are up.

<img width="444" alt="Screenshot 2019-10-21 at 13 09 38" src="https://user-images.githubusercontent.com/20965076/67200443-0efcb600-f404-11e9-97f7-9956257dc752.png">

**Comment by justinkambic** [comment]
@andrewvc @shahzad31 thoughts on the green checkmark?

**Comment by shahzad31** [comment]
Green all the way , i love green color anyway :) 

I think yes it makes sense.

Btw what if all monitors are down? Are we devising any state for that? though all red is already probably highlighted enough.

**Comment by andrewvc** [comment]
@shahzad31 IMHO the current design works for all monitors being down. Glad to hear what others think!

**Comment by andrewvc** [comment]
To clarify my thinking, there are broadly two states:

1. Everything OK
2. Something not OK

Everything being down is a subset of "Something not OK" IMHO

**Comment by shahzad31** [comment]
Yes i agree as well, whole red pie(current design) is enough for all down monitors. I was just trying to see if anyone else has any idea.

**Comment by justinkambic** [comment]
I agree that a pure-red circle is a pretty strong indicator. I think it will be rare that users are seeing _everything_ being down, it almost comes across more as an indicator that the Heartbeat agent itself is having a problem; alternatively they could be monitoring only one or two things, which is also probably less common.

**Comment by andrewvc** [comment]
Closing this design issue, implementation issue here: https://github.com/elastic/kibana/issues/49640
