### ISSUE TITLE
[Tech debt] Test `Saved Objects` interactions

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#97]
Today we're leveraging `Saved Objects` for our Kuery Bar mapping storage. This adapter is untested. We should avoid writing tests for it until we've migrated to the New Platform saved objects client, because the tests would likely need to change as well. Part of our migration to the new client should include the writing of tests.

**Comment by andrewvc** [comment]
We now use the official adapter, not relevant anymore.
