### ISSUE TITLE
[Uptime] Design for display of redirects

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#99]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)

With https://github.com/elastic/beats/pull/14125 we will now include a list of redirects traversed in checking a URL. There's currently no way to see this info. A check that involves redirects may be interpreted differently than one that does not, so we should indicate this. One key difference is that redirects can be slower than a non-redirects, so one may interpret latency differently.

**Ideal solution** (optional)
 We should probably display that somewhere in the UI. Perhaps in the history detail view. We could also maybe have a little icon or flag indicating that redirects were encountered.

**List known (technical) restrictions and requirements**

The data available is a simple list of string URLs.

**Are there any pages or actions that relate to this feature?**

Uptime overview and detail

**Comment by andrewvc** [comment]
@katrin-freihofner yes, exactly. We also have the order in which they were traversed. Internally, it's an ordered list of redirects we followed.

**Comment by katrin-freihofner** [comment]
I'm not sure if we even need this information on the overview page. But for the details, for sure.

I have tried two options

**Text + Icon**
<img width="844" alt="Screenshot 2019-11-12 at 12 38 13" src="https://user-images.githubusercontent.com/20965076/68668902-862bf280-0549-11ea-9e76-67ae51616da6.png">

**Accordion**
<img width="675" alt="Screenshot 2019-11-12 at 12 38 24" src="https://user-images.githubusercontent.com/20965076/68668913-8d530080-0549-11ea-9f0a-b733f395fd2c.png">

I'm wondering if the information should be within the duration panel, as it might affect the duration?

**Comment by katrin-freihofner** [comment]
@shahzad31 @justinkambic @andrewvc do you have any feedback on my proposal?

**Comment by katrin-freihofner** [comment]
@shahzad31 @justinkambic @andrewvc do you have any feedback on my proposal?

**Comment by shahzad31** [comment]
Looks great, i don't have preference between popover or accordion for this to be honest. 
One change i would like is to display links as breadcrumbs chain

link1 > link2 > link3 etc

Or 

use list with arrow down icons, instead of 1,2 ,3 , something like

&#8675; Home link
&#8675; Details link
&#8675; Table link

it can also be one way full expanded EUI tree view
![image](https://user-images.githubusercontent.com/3505601/69143073-7a4fab80-0ac8-11ea-8d85-f4f5026df17d.png)

**Comment by katrin-freihofner** [comment]
> 
> ⇣ Home link
> ⇣ Details link
> ⇣ Table link
> 

I like this proposal very much! We have a sort down icon we could use here.

**Comment by andrewvc** [comment]
I love where we've wound up here with the down arrows. I think we can omit the copy "This may have a negative effect on duration". Maybe we can replace the copy with:

"Heartbeat followed N redirects while executing ping.", which is more concise and implies that those checks occurred within the ping, and hence its timing measurement.

**Comment by andrewvc** [comment]
We also need to show this in the ping history. I'm thinking we can make this another section in the expanded rows for each entry. WDYT @katrin-freihofner ?

**Comment by katrin-freihofner** [comment]
@andrewvc you mean here?

<img width="890" alt="Screenshot 2019-11-20 at 10 36 06" src="https://user-images.githubusercontent.com/20965076/69227396-083b9d00-0b82-11ea-8264-c6b9de4c63c5.png">

**Comment by andrewvc** [comment]
@katrin-freihofner yes, exactly! I was thinking we could add a sibling of "Response Body" called "Redirects" WDYT?

**Comment by shahzad31** [comment]
Well thinking ahead, maybe once we do that, we can also says how much each redirect took?
@andrewvc are we tracking that in heartbeat?

**Comment by katrin-freihofner** [comment]
@shahzad31 @andrewvc maybe like this?

<img width="742" alt="Screenshot 2019-11-21 at 08 51 08" src="https://user-images.githubusercontent.com/20965076/69317827-13eb9a00-0c3c-11ea-81c0-84b8b16449ed.png">

**Comment by andrewvc** [comment]
@katrin-freihofner I think with real URL values we'll need them across separate lines. They'll be too long to look right side by side.

**Comment by katrin-freihofner** [comment]
Yes, let's better stack them. 

<img width="547" alt="Screenshot 2019-11-21 at 14 18 57" src="https://user-images.githubusercontent.com/20965076/69341445-e0276900-0c69-11ea-938b-fa43d5fb3327.png">

For smaller screens: If the URL is too long, I suggest to use no-wrap + ellipsis.
